Audit and Authentication Policy Change Events
elastic/beats pull request #20684
Opened 2020-08-19 10:33 UTC by janniten

## What does this PR do?

* Adds support for _**Audit and Authentication Policy Change Events**_

**Audit Audit   Policy Change** | **Audit Authentication Policy Change**
-- | --
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-audit-policy-change | https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-authentication-policy-change
4719(S): System audit policy was changed. | 4670(S): Permissions on an object were changed
4817(S): Auditing settings on object were   changed. | 4706(S): A new trust was created to a domain.
4902(S): The Per-user audit policy table   was created. | 4707(S): A trust to a domain was removed.
4906(S): The CrashOnAuditFail value has   changed. | 4716(S): Trusted domain information was modified.
4907(S): Auditing settings on object were   changed. | 4713(S): Kerberos policy was changed.
4908(S): Special Groups Logon table   modified. | 4717(S): System security access was granted to an account.
4912(S): Per User Audit Policy was   changed. | 4718(S): System security access was removed from an account.
4904(S): An attempt was made to register   a security event source. | 4739(S): Domain Policy was changed.
4905(S): An attempt was made to   unregister a security event source. |  

Note:  Although processing of  Event 4715 (The audit policy (SACL) on an object was changed) seems to be identical to 4670, event 4715 was not included due I was not able to generate an example event.

For events where exists information of DACLs or SACLs those ACL are translated from the SDDL (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/f4296d69-1c0f-491f-9587-a960b292d070) to a human-readable from. For example:

![image](https://user-images.githubusercontent.com/33020901/90624143-c9716b00-e217-11ea-8193-e04e1792ff27.png)

* Adds **related.ip** information in existing events where source.ip is present.

## Why is it important?
-  Auditing the changes in policies and event sources is crucial when we want to have a strong security monitoring system. Monitor these kinds of events are also important when we address compliance (SOX, PCI. HIPAA, etc )

- The related.ip information is useful when we want to pivot data between different sources. For example
- a Fortinet Event (37141) indicating a user is connected to a VPN SSL when tunnelip is the asigned address.  Tunnelip is also in the related.ip field
- a Windows Event 4624 indicating a windows login from a source.ip. If we have source.ip in the related.ip it is easy to match the user connected through VPN with a windows logon

## Checklist

- [x ] My code follows the style guidelines of this project
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2020-08-19 10:33 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-08-19 10:33 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-08-19 10:38 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20684/detail/PR-20684/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20684/detail/PR-20684/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20684/detail/PR-20684/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20684/detail/PR-20684/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #20684 opened]`

* Reason: `The PR is not allowed to run in the CI yet`

* Start Time: 2020-08-19T10:34:29.879+0000

* Duration: 4 min 38 sec


* Commit: 3e216df55ef1b708952436022b3e6c42d4583892




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Error signal`
    * Description: githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permission
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-08-19T10:37:54.823+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-20684/runs/1/steps/77/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-08-19T10:37:59.013Z] Stage "Filebeat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.025Z] Stage "Filebeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.037Z] Stage "Filebeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.049Z] Stage "Filebeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.060Z] Stage "Heartbeat oss" skipped due to earlier failure(s)
[2020-08-19T10:37:59.071Z] Stage "Heartbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.082Z] Stage "Heartbeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.095Z] Stage "Auditbeat oss Linux" skipped due to earlier failure(s)
[2020-08-19T10:37:59.108Z] Stage "Auditbeat crosscompile" skipped due to earlier failure(s)
[2020-08-19T10:37:59.121Z] Stage "Auditbeat oss Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.133Z] Stage "Auditbeat oss Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.145Z] Stage "Auditbeat x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.157Z] Stage "Auditbeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.168Z] Stage "Auditbeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.179Z] Stage "Libbeat" skipped due to earlier failure(s)
[2020-08-19T10:37:59.185Z] Stage "Libbeat x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.197Z] Stage "Metricbeat OSS Unit tests" skipped due to earlier failure(s)
[2020-08-19T10:37:59.208Z] Stage "Metricbeat OSS Go Integration tests" skipped due to earlier failure(s)
[2020-08-19T10:37:59.220Z] Stage "Metricbeat OSS Python Integration tests" skipped due to earlier failure(s)
[2020-08-19T10:37:59.232Z] Stage "Metricbeat x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.238Z] Stage "Metricbeat crosscompile" skipped due to earlier failure(s)
[2020-08-19T10:37:59.250Z] Stage "Metricbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.260Z] Stage "Metricbeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.271Z] Stage "Metricbeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.282Z] Stage "Metricbeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.294Z] Stage "Packetbeat Linux" skipped due to earlier failure(s)
[2020-08-19T10:37:59.306Z] Stage "Packetbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.316Z] Stage "Packetbeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.328Z] Stage "dockerlogbeat" skipped due to earlier failure(s)
[2020-08-19T10:37:59.339Z] Stage "Winlogbeat oss" skipped due to earlier failure(s)
[2020-08-19T10:37:59.349Z] Stage "Winlogbeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.360Z] Stage "Winlogbeat Windows x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.372Z] Stage "Functionbeat x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.383Z] Stage "Functionbeat Mac OS X x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.395Z] Stage "Functionbeat Windows" skipped due to earlier failure(s)
[2020-08-19T10:37:59.406Z] Stage "Journalbeat" skipped due to earlier failure(s)
[2020-08-19T10:37:59.416Z] Stage "Generators" skipped due to earlier failure(s)
[2020-08-19T10:37:59.423Z] Stage "Generators Metricbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.434Z] Stage "Generators Beat Mac OS X" skipped due to earlier failure(s)
[2020-08-19T10:37:59.445Z] Stage "Kubernetes" skipped due to earlier failure(s)
[2020-08-19T10:37:59.567Z] Stage "Libbeat" skipped due to earlier failure(s)
[2020-08-19T10:37:59.577Z] Stage "Metricbeat x-pack" skipped due to earlier failure(s)
[2020-08-19T10:37:59.587Z] Stage "Generators" skipped due to earlier failure(s)
[2020-08-19T10:38:01.312Z] Failed in branch Elastic Agent x-pack
[2020-08-19T10:38:01.322Z] Failed in branch Elastic Agent x-pack Windows
[2020-08-19T10:38:01.333Z] Failed in branch Elastic Agent Mac OS X
[2020-08-19T10:38:01.344Z] Failed in branch Filebeat oss
[2020-08-19T10:38:01.355Z] Failed in branch Filebeat x-pack
[2020-08-19T10:38:01.365Z] Failed in branch Filebeat Mac OS X
[2020-08-19T10:38:01.375Z] Failed in branch Filebeat x-pack Mac OS X
[2020-08-19T10:38:01.385Z] Failed in branch Filebeat Windows
[2020-08-19T10:38:01.395Z] Failed in branch Filebeat x-pack Windows
[2020-08-19T10:38:01.405Z] Failed in branch Heartbeat oss
[2020-08-19T10:38:01.414Z] Failed in branch Heartbeat Mac OS X
[2020-08-19T10:38:01.427Z] Failed in branch Heartbeat Windows
[2020-08-19T10:38:01.438Z] Failed in branch Auditbeat oss Linux
[2020-08-19T10:38:01.448Z] Failed in branch Auditbeat crosscompile
[2020-08-19T10:38:01.458Z] Failed in branch Auditbeat oss Mac OS X
[2020-08-19T10:38:01.472Z] Failed in branch Auditbeat oss Windows
[2020-08-19T10:38:01.484Z] Failed in branch Auditbeat x-pack
[2020-08-19T10:38:01.495Z] Failed in branch Auditbeat x-pack Mac OS X
[2020-08-19T10:38:01.505Z] Failed in branch Auditbeat x-pack Windows
[2020-08-19T10:38:01.517Z] Failed in branch Libbeat x-pack
[2020-08-19T10:38:01.531Z] Failed in branch Metricbeat OSS Unit tests
[2020-08-19T10:38:01.543Z] Failed in branch Metricbeat OSS Go Integration tests
[2020-08-19T10:38:01.554Z] Failed in branch Metricbeat OSS Python Integration tests
[2020-08-19T10:38:01.565Z] Failed in branch Metricbeat crosscompile
[2020-08-19T10:38:01.576Z] Failed in branch Metricbeat Mac OS X
[2020-08-19T10:38:01.586Z] Failed in branch Metricbeat x-pack Mac OS X
[2020-08-19T10:38:01.596Z] Failed in branch Metricbeat Windows
[2020-08-19T10:38:01.606Z] Failed in branch Metricbeat x-pack Windows
[2020-08-19T10:38:01.618Z] Failed in branch Packetbeat Linux
[2020-08-19T10:38:01.629Z] Failed in branch Packetbeat Mac OS X
[2020-08-19T10:38:01.640Z] Failed in branch Packetbeat Windows
[2020-08-19T10:38:01.650Z] Failed in branch dockerlogbeat
[2020-08-19T10:38:01.661Z] Failed in branch Winlogbeat oss
[2020-08-19T10:38:01.671Z] Failed in branch Winlogbeat Windows
[2020-08-19T10:38:01.680Z] Failed in branch Winlogbeat Windows x-pack
[2020-0 [...]

2020-08-19 12:20 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-08-19 12:20 UTC, andrewkroh commented
jenkins, test this

2020-09-18 15:55 UTC, janniten commented
I confirm 👍

2020-10-21 13:43 UTC, janniten commented
I still believe that those kind of events are important.
@andrewkroh what do you think?

Thank you

2020-10-21 19:19 UTC, andrewkroh commented
💯 agree. Sorry it's taking so long to look these changes over.

2020-11-18 16:28 UTC, janniten commented
New ECS 1.7.0 event category configuration used for auditory configuration and changes

https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html#ecs-event-category-configuration

2020-12-21 16:25 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2020-12-21 16:34 UTC, janniten commented
Events related to audit configuration/changes are relevant when talking about defense evasion and also when you are under  strong security regulations.
New ECS 1.7.0 event category configuration used for auditory configuration and changes of this PR and in events from older PRs

2021-01-08 08:33 UTC, janniten commented
Pinging @elastic/security-external-integrations , @andrewkroh 
Do you consider that this PR is still relevant? If not I can close it
Thank you!

2021-01-19 21:16 UTC, leehinman commented
@janniten do you mind if I rebase off master and fix some conflicts.  There are a bunch in eventActionTypes, to support multiple values for event.category and event.type those are now arrays, so conflicts like:

```
"4697": [["iam", "configuration"], ["admin", "change"],"service-installed"],
vs
"4697": ["iam","admin","service-installed"]
```

2021-01-19 21:30 UTC, janniten commented
> @janniten do you mind if I rebase off master and fix some conflicts. There are a bunch in eventActionTypes, to support multiple values for event.category and event.type those are now arrays, so conflicts like:
> 
> ```
> "4697": [["iam", "configuration"], ["admin", "change"],"service-installed"],
> vs
> "4697": ["iam","admin","service-installed"]
> ```

Hi @leehinman. No problem! Go ahead!
Thank you

2021-01-19 21:39 UTC, janniten commented
> > @janniten do you mind if I rebase off master and fix some conflicts. There are a bunch in eventActionTypes, to support multiple values for event.category and event.type those are now arrays, so conflicts like:
> > ```
> > "4697": [["iam", "configuration"], ["admin", "change"],"service-installed"],
> > vs
> > "4697": ["iam","admin","service-installed"]
> > ```
> 
> Hi @leehinman. No problem! Go ahead!
> Thank you

I use in array values un order to suppport múltiples categoriew/types, but It is added later in code the when process the event.
It is better to define It in the way you propose.
Thank you!

2021-01-20 21:28 UTC, leehinman commented
@janniten I couldn't push to your repo so I uploaded my changes here https://github.com/leehinman/beats/tree/janniten_aa_policy_change

Can you take a quick look and see if that looks right?  The intent was just address the eventActionTypes and to add golden files.

2021-01-21 13:50 UTC, janniten commented
> @janniten I couldn't push to your repo so I uploaded my changes here https://github.com/leehinman/beats/tree/janniten_aa_policy_change
> 
> Can you take a quick look and see if that looks right? The intent was just address the eventActionTypes and to add golden files.

@leehinman , LGTM
I've noticed that there are some events defined in the eventActionTypes but not being processed (events 4616,4657 for example). Once finishished this PR I can add those ones.
Thank you!

2021-01-23 03:41 UTC, leehinman requested changes

2021-01-23 03:41 UTC, leehinman commented on x-pack/winlogbeat/module/security/config/winlogbeat-security.js
> +                {from: "winlog.event_data.ClientAddress", to: "related.ip"},
I think we want to add `type: "ip"`, I know we had at least one bug with this for with `source.ip`

2021-01-23 03:41 UTC, leehinman commented on x-pack/winlogbeat/module/security/config/winlogbeat-security.js
> +                {from: "winlog.event_data.ClientAddress", to: "related.ip"},
I think we want to add `type: "ip"`

2021-01-23 21:12 UTC, leehinman approved these changes

2021-01-25 14:47 UTC, leehinman commented
run tests

2021-01-25 15:30 UTC, merged

2021-01-26 02:40 UTC, andrewkroh commented
The new event IDs from this PR will need added to the list in https://www.elastic.co/guide/en/beats/winlogbeat/master/winlogbeat-module-security.html#winlogbeat-module-security.

2021-01-26 07:59 UTC, janniten commented
> The new event IDs from this PR will need added to the list in https://www.elastic.co/guide/en/beats/winlogbeat/master/winlogbeat-module-security.html#winlogbeat-module-security.

Hi @andrewkroh. Done it https://github.com/elastic/beats/pull/23674

2021-01-26 08:46 UTC, janniten commented
> The new event IDs from this PR will need added to the list in https://www.elastic.co/guide/en/beats/winlogbeat/master/winlogbeat-module-security.html#winlogbeat-module-security.

@andrewkroh , @leehinman Doc updated in https://github.com/elastic/beats/pull/23674