Avoid edge cases in activitylogs pipeline
elastic/beats pull request #20865
Opened 2020-08-31 16:12 UTC by narph

## What does this PR do?

Fixing pipeline breaking on some edge cases inside the azure activitylogs

## Why is it important?

>  There are some edge cases that result into failures for the ingest pipeline.
> 2.a) In my example I had \e characters in the log file which resulted into the error
> "Illegal unquoted character ((CTRL-CHAR, code 27)): has to be escaped using backslash to be included in string value\n at [Source: (org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 2848]"
> 
> 2.b) Also the source.ip field is not always filled

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes https://github.com/elastic/beats/issues/20797

2020-08-31 16:15 UTC, elasticmachine commented
Pinging @elastic/integrations-platforms (Team:Platforms)

2020-08-31 16:18 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20865/detail/PR-20865/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20865/detail/PR-20865/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20865/detail/PR-20865/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20865/detail/PR-20865/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #20865 opened]`

* Reason: `Aborted from #2`

* Start Time: 2020-08-31T16:14:53.881+0000

* Duration: 3 min 25 sec


* Commit: 53e98724e443ace5d2cb43a83c20b3475bb0f981




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->




<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-08-31T16:18:10.301Z] Stage "Filebeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.317Z] Stage "Filebeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.332Z] Stage "Filebeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.348Z] Stage "Heartbeat oss" skipped due to earlier failure(s)
[2020-08-31T16:18:10.362Z] Stage "Heartbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.377Z] Stage "Heartbeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.392Z] Stage "Auditbeat oss Linux" skipped due to earlier failure(s)
[2020-08-31T16:18:10.414Z] Stage "Auditbeat crosscompile" skipped due to earlier failure(s)
[2020-08-31T16:18:10.429Z] Stage "Auditbeat oss Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.444Z] Stage "Auditbeat oss Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.458Z] Stage "Auditbeat x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.473Z] Stage "Auditbeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.491Z] Stage "Auditbeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.506Z] Stage "Libbeat" skipped due to earlier failure(s)
[2020-08-31T16:18:10.513Z] Stage "Libbeat x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.528Z] Stage "Metricbeat OSS Unit tests" skipped due to earlier failure(s)
[2020-08-31T16:18:10.543Z] Stage "Metricbeat OSS Go Integration tests" skipped due to earlier failure(s)
[2020-08-31T16:18:10.557Z] Stage "Metricbeat OSS Python Integration tests" skipped due to earlier failure(s)
[2020-08-31T16:18:10.570Z] Stage "Metricbeat x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.577Z] Stage "Metricbeat crosscompile" skipped due to earlier failure(s)
[2020-08-31T16:18:10.591Z] Stage "Metricbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.604Z] Stage "Metricbeat x-pack Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.618Z] Stage "Metricbeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.636Z] Stage "Metricbeat x-pack Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.650Z] Stage "Packetbeat Linux" skipped due to earlier failure(s)
[2020-08-31T16:18:10.664Z] Stage "Packetbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.678Z] Stage "Packetbeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.693Z] Stage "dockerlogbeat" skipped due to earlier failure(s)
[2020-08-31T16:18:10.708Z] Stage "Winlogbeat oss" skipped due to earlier failure(s)
[2020-08-31T16:18:10.721Z] Stage "Winlogbeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.739Z] Stage "Winlogbeat Windows x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.756Z] Stage "Functionbeat x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.771Z] Stage "Functionbeat Mac OS X x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:10.786Z] Stage "Functionbeat Windows" skipped due to earlier failure(s)
[2020-08-31T16:18:10.801Z] Stage "Journalbeat" skipped due to earlier failure(s)
[2020-08-31T16:18:10.815Z] Stage "Generators" skipped due to earlier failure(s)
[2020-08-31T16:18:10.822Z] Stage "Generators Metricbeat Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.838Z] Stage "Generators Beat Mac OS X" skipped due to earlier failure(s)
[2020-08-31T16:18:10.852Z] Stage "Kubernetes" skipped due to earlier failure(s)
[2020-08-31T16:18:10.985Z] Stage "Libbeat" skipped due to earlier failure(s)
[2020-08-31T16:18:10.997Z] Stage "Metricbeat x-pack" skipped due to earlier failure(s)
[2020-08-31T16:18:11.009Z] Stage "Generators" skipped due to earlier failure(s)
[2020-08-31T16:18:12.814Z] Failed in branch Elastic Agent x-pack
[2020-08-31T16:18:12.824Z] Failed in branch Elastic Agent x-pack Windows
[2020-08-31T16:18:12.834Z] Failed in branch Elastic Agent Mac OS X
[2020-08-31T16:18:12.844Z] Failed in branch Filebeat oss
[2020-08-31T16:18:12.854Z] Failed in branch Filebeat x-pack
[2020-08-31T16:18:12.864Z] Failed in branch Filebeat Mac OS X
[2020-08-31T16:18:12.874Z] Failed in branch Filebeat x-pack Mac OS X
[2020-08-31T16:18:12.884Z] Failed in branch Filebeat Windows
[2020-08-31T16:18:12.893Z] Failed in branch Filebeat x-pack Windows
[2020-08-31T16:18:12.902Z] Failed in branch Heartbeat oss
[2020-08-31T16:18:12.912Z] Failed in branch Heartbeat Mac OS X
[2020-08-31T16:18:12.922Z] Failed in branch Heartbeat Windows
[2020-08-31T16:18:12.931Z] Failed in branch Auditbeat oss Linux
[2020-08-31T16:18:12.943Z] Failed in branch Auditbeat crosscompile
[2020-08-31T16:18:12.953Z] Failed in branch Auditbeat oss Mac OS X
[2020-08-31T16:18:12.965Z] Failed in branch Auditbeat oss Windows
[2020-08-31T16:18:12.976Z] Failed in branch Auditbeat x-pack
[2020-08-31T16:18:12.987Z] Failed in branch Auditbeat x-pack Mac OS X
[2020-08-31T16:18:12.998Z] Failed in branch Auditbeat x-pack Windows
[2020-08-31T16:18:13.009Z] Failed in branch Libbeat x-pack
[2020-08-31T16:18:13.019Z] Failed in branch Metricbeat OSS Unit tests
[2020-08-31T16:18:13.029Z] Failed in branch Metricbeat OSS Go Integration tests
[2020-08-31T16:18:13.040Z] Failed in branch Metricbeat OSS Python Integration tests
[2020-08-31T16:18:13.050Z] Failed in branch Metricbeat crosscompile
[2020-08-31T16:18:13.060Z] Failed in branch Metricbeat Mac OS X
[2020-08-31T16:18:13.070Z] Failed in branch Metricbeat x-pack Mac OS X
[2020-08-31T16:18:13.080Z] Failed in branch Metricbeat Windows
[2020-08-31T16:18:13.091Z] Failed in branch Metricbeat x-pack Windows
[2020-08-31T16:18:13.101Z] Failed in branch Packetbeat Linux
[2020-08-31T16:18:13.113Z] Failed in branch Packetbeat Mac OS X
[2020-08-31T16:18:13.124Z] Failed in branch Packetbeat Windows
[2020-08-31T16:18:13.133Z] Failed in branch dockerlogbeat
[2020-08-31T16:18:13.144Z] Failed in branch Winlogbeat oss
[2020-08-31T16:18:13.153Z] Failed in branch Winlogbeat Windows
[2020-08-31T16:18:13.163Z] Failed in branch Winlogbeat Windows x-pack
[2020-08-31T16:18:13.173Z] Failed in branch Functionbeat x-pack
[2020-08-31T16:18:13.183Z] Failed in branch Functionbeat Mac OS X x-pack
[2020-08-31T16:18:13.194Z] Failed in branch Functionbeat Windows
[2020-08-31T16:18:13.204Z] Failed in branch Journalbeat
[2020-08-31T16:18:13.215Z] Failed in branch Generators Metricbeat Mac OS X
[2020-08-31T16:18:13.225Z] Failed in branch Generators Beat Mac OS X
[2020-08-31T16:18:13.235Z] Failed in branch Kubernetes
[2020-08-31T16:18:13.482Z] Stage "Libbeat" skipped due to earlier failure(s)
[2020-08-31T16:18:13.494Z] Stage "Metricbeat x-pack"  [...]

2020-09-04 14:53 UTC, jsoriano requested changes

2020-09-04 14:53 UTC, jsoriano commented on CHANGELOG.next.asciidoc
> +- Add checks in the azure activitylogs pipeline for several edge cases. {issue}20797[20797]{pull}20865[20865]
Could you add some test files for these edge cases?

2021-06-02 11:25 UTC, narph commented
new PR coming soon, closing this since some of the issues have been fixed already

2021-06-02 11:25 UTC, closed without merging