[Filebeat][santa] Map x509 fields in santa module
elastic/beats pull request #20976
Opened 2020-09-04 09:06 UTC by marc-gr

## What does this PR do?

Maps x509 fields in santa module.

## Why is it important?

To keep modules up to date with ecs 1.6.

## Checklist

~- [ ] My code follows the style guidelines of this project~
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates #19472

2020-09-04 09:07 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-09-04 10:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20976/detail/PR-20976/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20976/detail/PR-20976/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20976/detail/PR-20976/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-20976/detail/PR-20976/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_20976.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #20976 opened]`

* Start Time: 2020-09-04T09:07:34.887+0000

* Duration: 55 min 55 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5583  |
| Skipped      | 825 |
| Total        | 6408   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-09-04 14:06 UTC, leehinman requested changes
Changes to pipeline look great.

But I forgot about this on the zeek x509 changes.  We should be bumping the ecs.version in the config file:

```
processors:
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
```

2020-09-04 15:16 UTC, marc-gr commented
> Changes to pipeline look great.
> 
> But I forgot about this on the zeek x509 changes. We should be bumping the ecs.version in the config file:
> 
> ```
> processors:
>   - add_fields:
>       target: ''
>       fields:
>         ecs.version: 1.6.0
> ```

true! will bundle the missing ones, thanks!

2020-09-08 01:40 UTC, leehinman approved these changes
LGTM

2020-09-08 09:00 UTC, merged