Remove duplicate line from the reference config
elastic/beats pull request #21093
Opened 2020-09-15 07:59 UTC by TheFakeStefan

Remote the duplicate line from the reference config of Auditbeat.

## What does this PR do?

## Why is it important?

## Checklist

- [X] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- Validate that the duplicate line is removed.

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2020-09-15 07:59 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-15 07:59 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-15 08:19 UTC, TheFakeStefan commented
CLA signed.

2020-09-16 05:29 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-09-16 10:13 UTC, adriansr requested changes
The `auditbeat.reference.yml` file is autogenerated. You must apply this change to `auditbeat/_meta/beat.reference.yml` and then run `make update` in the repo's top-level directory.

2020-09-18 10:31 UTC, TheFakeStefan commented
I was unable to mofiy this pull request and submitted a new change #21165

2020-09-18 10:31 UTC, closed without merging