Cherry-pick #21160 to 7.x:  [ECS] Adds related.hosts to capture all hostnames and host identifiers on an event.
elastic/beats pull request #21257
Opened 2020-09-23 15:31 UTC by marc-gr

Cherry-pick of PR #21160 to 7.x branch. Original message: 

## What does this PR do?

Added related.hosts to capture all hostnames and host identifiers on an event.

## Why is it important?

To keep the modules up to date with ecs 1.6

## Checklist

~- [ ] My code follows the style guidelines of this project~
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] rsa2elk modules
- [x] Filebeat panw
- [x] Filebeat osquery
- [x] Filebeat system
- [x] Filebeat microsoft/defender_atp
- [x] Filebeat suricat
- [x] Filebeat cisco

## Related issues

- Relates elastic/beats#19472

2020-09-23 15:31 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-09-23 15:47 UTC, leehinman requested changes

2020-09-23 15:47 UTC, leehinman commented on CHANGELOG.next.asciidoc
> +- Always attempt community_id processor on zeek module {pull}21155[21155]
Looks like cherry_pick script pulled in zeek changelog entry

2020-09-23 17:56 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21257/detail/PR-21257/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21257/detail/PR-21257/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21257/detail/PR-21257/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21257/detail/PR-21257/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21257.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21257 updated]`

* Start Time: 2020-09-23T16:28:27.184+0000

* Duration: 88 min 3 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 258  |
| Passed       | 5372  |
| Skipped      | 833 |
| Total        | 6463   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors
  <details><summary>Expand to view the tests failures</summary>
  <p>
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_097_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 90.003
  * Error Details: Failed: Timeout >90.0s
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_098_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.205
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_099_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.177
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_100_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.18
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_101_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.263
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_102_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.252
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_103_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.177
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_104_system – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.235
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_105_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.144
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_106_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.255
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_107_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.215
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_108_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.198
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_109_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.157
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_110_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.165
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_111_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.159
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_112_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.153
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_113_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.229
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_114_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.169
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_115_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.156
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_116_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.183
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_117_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.205
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_118_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.193
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_119_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.155
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_120_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.183
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_fileset_file_121_kafka – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.178
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build and Test / Filebeat oss / test_stdin_eof – filebeat.tests.system.test_stdin.Test`
  * Age: 1
  * Duration: 10.129
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited  [...]

2020-09-29 11:21 UTC, andrewkroh approved these changes

2020-09-29 13:15 UTC, merged