[packaging] run on a daily basis for branches only
elastic/beats pull request #21250
Opened 2020-09-23 13:31 UTC by v1v

## What does this PR do?

As agreed let's run the packaging pipeline for the master/release branches on a daily basis, then snapshot binaries are at least generated once a day in the worst case scenario.

## Why is it important?

Current workflow consists on three different pipelines that run sequentially, if any of those pipelines got broken then the following pipelines won't be triggered.

In other words, for every commit that's merged to master, the multibranch pipeline is triggered, and only if it ran successfully the packaging pipeline will be triggered, and only if that pipeline is successfully the `beats-tester` pipeline will run.

2020-09-23 13:35 UTC, mdelapenya approved these changes

2020-09-23 13:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21250/detail/PR-21250/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21250/detail/PR-21250/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21250/detail/PR-21250/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21250/detail/PR-21250/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21250.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21250 opened]`

* Start Time: 2020-09-23T13:32:43.136+0000

* Duration: 25 min 11 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-09-23 14:09 UTC, kuisathaverat approved these changes

2020-09-23 14:11 UTC, kuisathaverat commented
if the job is building with every successful build on the Beats master branch Why we need to run it on schedule? it should be triggered several times a day, so trigger it on schedule will generate binaries for the same las successful build or if the beats master is broken probably broken binaries.

2020-09-23 14:22 UTC, v1v commented
> if the job is building with every successful build on the Beats master branch Why we need to run it on schedule? it should be triggered several times a day, so trigger it on schedule will generate binaries for the same las successful build or if the beats master is broken probably broken binaries.

We agreed in the weekly beats-ci meeting to provide this approach. A bit more of context, this is a short term proposal to generate the packages since the flakiness in the test might cause a bunch of commit builds without a binary. For instance for the last 6 days there was no successful build:

![image](https://user-images.githubusercontent.com/2871786/94025145-1a90f380-fdb0-11ea-8fa7-f36748a06647.png)

It's not ideal to have flaky tests, but as long as there are there is no way to build the packaging unless we enforce this scheduled run that will help to run the beats-tester on the other hand.

Long term proposal, I guess to avoid flakiness

2020-09-23 16:30 UTC, kuisathaverat commented
I think that it is the wrong way to fix the problem, and add a new one on top, generate invalid binaries. The flaky tests are not new, now we have the [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures#re-run-individual-failures) they can rerun the flaky test only, they only have to mark then, they are 4-5 tests no more the pipeline fails always in the same test.

2020-09-23 16:31 UTC, kuisathaverat requested changes
It can generate invalid binaries

2020-09-23 16:49 UTC, v1v commented
Is the unified release process generating binaries from master/7.x branches? If so, we got the same issue.

We could potentially create two folders:
- unstable folder where the packaging runs and generate binaries from commit that got flaky tests.

- stable folder where the packaging runs and generates binaries from commit that didng have any flaky test.

Probably we should work on no merge to master allowed policy if master is broken, but we are not the owners. Meanwhile I'd say to enable generating binaries and test them with the beats-tester once a day, so I can work on supporting that particular case in another pipeline/workflow.

What do you think?

2020-09-24 16:06 UTC, kuisathaverat commented
flaky and broken test based on the latest 21 builds https://github.com/elastic/beats/pull/21300, we are talking about 5 flaky tests and 2 broken tests.

[TestClientPublishEventKerberosAware](https://github.com/elastic/beats/blob/7864a40ede50b77c5d762fe5e27915b52c1a01c3/libbeat/outputs/elasticsearch/client_integration_test.go#L60) (21/21) and [test_default_settings](https://github.com/elastic/beats/blob/7864a40ede50b77c5d762fe5e27915b52c1a01c3/filebeat/tests/system/test_autodiscover.py#L53) (16/21) are directly broken for 6 days.

2020-10-15 09:24 UTC, v1v commented
I'll close this PR now as we have agreed to fix the issues instead workaround it

2020-10-15 09:24 UTC, closed without merging