Cherry-pick #21113 to 7.x: libbeat/cmd/instance: report cgroup stats
elastic/beats pull request #21334
Opened 2020-09-26 07:46 UTC by axw

Cherry-pick of PR #21113 to 7.x branch. Original message: 

## What does this PR do?

Report cgroup limits/stats on Linux, similar to what Elasticsearch reports through node stats: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

Metric names are based on (but not exactly the same as) the [`system.process.cgroup.*`](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html#_cgroup) fields.

## Why is it important?

This is important for reporting accurate resource usage in containerised environments.

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

I couldn't see docs or tests to update - please point me to them if there are any.

## How to test this PR locally

1. Build and run a beat on Linux, with monitoring enabled
2. Observe that cgroup metrics are reported

## Related issues

Closes #14691

2020-09-26 07:47 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2020-09-26 09:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21334/detail/PR-21334/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21334/detail/PR-21334/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21334/detail/PR-21334/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21334/detail/PR-21334/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21334.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21334 opened]`

* Start Time: 2020-09-26T07:48:19.970+0000

* Duration: 75 min 15 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 20256  |
| Skipped      | 1862 |
| Total        | 22118   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-09-28 13:48 UTC, fearful-symmetry approved these changes
LGTM.

2020-09-28 19:46 UTC, adriansr requested changes
The changes in this PR have been causing a crash in master version for some days. I sent a fix in https://github.com/elastic/beats/pull/21355, maybe you want to add the extra check to this backport.

2020-09-29 01:15 UTC, axw commented
Thanks @adriansr, I've cherry-picked your commit.

2020-09-29 09:27 UTC, adriansr approved these changes

2020-09-30 02:35 UTC, merged