Cherry-pick #21450 to 7.x: Add new log file reader for filestream input
elastic/beats pull request #21470
Opened 2020-10-02 11:14 UTC by kvch

Cherry-pick of PR #21450 to 7.x branch. Original message: 

## What does this PR do?

This PR adds the new refactored version of the previous `Log` reader of the `log` input called `logFile`. The differences between the two readers are the following:

* `logFile` calls `Stat` only once to avoid too many system calls (`Log` calls `Stat` 3 times after every read)
* `logFile` starts separate go routines to check if `close.after_interval` or `close.inactive` has elapsed. `Log` checks `close_inactive` after every `Read`. Thus, if the output is blocked, it cannot stop the reader.
* `logFile` does not check if the file has been removed or renamed if `close_removed` or `close_renamed` are enabled. Instead it is checked separately in the prospector, so if the output blocks, the reader can be closed. This prevents Filebeat keeping too many open files if the output is blocked. (The code mentioned is not yet included in any PR.)

## Why is it important?

This is the improved version of the previous `log` reader.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

Rebased on #21444

2020-10-02 11:14 UTC, elasticmachine commented
Pinging @elastic/integrations-services (Team:Services)

2020-10-02 11:48 UTC, v1v requested changes
This breaks the windows builds

2020-10-02 11:56 UTC, faec approved these changes

2020-10-02 12:42 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21470.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21470 opened]`

* Start Time: 2020-10-02T11:15:22.140+0000

* Duration: 87 min 23 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 319  |
| Passed       | 4084  |
| Skipped      | 564 |
| Total        | 4967   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors
  <details><summary>Expand to view the tests failures</summary>
  <p>
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_034_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 90.003
  * Error Details: Failed: Timeout >90.0s
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_035_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.204
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_036_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.196
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_037_osquery – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.193
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_038_redis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.168
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_039_redis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.203
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_040_redis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.209
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_041_redis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.231
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_042_redis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.211
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_043_haproxy – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.121
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_044_haproxy – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.165
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_045_haproxy – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.167
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_046_haproxy – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.125
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_047_nats – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.117
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_048_santa – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.132
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_049_icinga – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.139
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_050_icinga – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.121
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_051_icinga – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.155
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_052_traefik – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.109
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_053_logstash – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.103
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_054_logstash – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.099
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_055_logstash – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.155
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_056_logstash – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.165
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_057_logstash – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.095
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_058_elasticsearch – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.123
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_059_elasticsearch – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 10.121
  * Error Details: beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 1 [...]

2020-10-05 12:33 UTC, v1v approved these changes

2020-10-05 13:21 UTC, merged

2020-10-05 13:32 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21470/detail/PR-21470/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21470.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21470 updated]`

* Start Time: 2020-10-05T12:07:39.565+0000

* Duration: 85 min 54 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 327  |
| Passed       | 4109  |
| Skipped      | 564 |
| Total        | 5000   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors
  <details><summary>Expand to view the tests failures</summary>
  <p>
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_001_iis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 2.854
  * Error Details: AssertionError: The following expected object doesn't match:    Diff:   {'dictionary_item_added': [root['source.geo.country_name']]}, full object:    {'log.offset': 257, 'destination.address': '127.0.0.1', 'destination.port': 80, 'destination.ip': '127.0.0.1', 'source.geo.continent_name': 'Europe', 'source.geo.region_iso_code': 'DE-BE', 'source.geo.city_name': 'Berlin', 'source.geo.country_iso_code': 'DE', 'source.geo.country_name': 'Germany', 'source.geo.region_name': 'Land Berlin', 'source.geo.location.lon': 13.4531, 'source.geo.location.lat': 52.4473, 'source.as.number': 6805, 'source.as.organization.name': 'Telefonica Germany', 'source.address': '85.181.35.98', 'source.ip': '85.181.35.98', 'fileset.name': 'access', 'url.path': '/', 'url.query': 'q=100', 'input.type': 'log', 'iis.access.sub_status': 0, 'iis.access.win32_status': 0, '@timestamp': '2018-01-01T08:09:10.000Z', 'related.ip': ['85.181.35.98', '127.0.0.1'], 'service.type': 'iis', 'http.request.method': 'GET', 'http.response.status_code': 200, 'event.duration': 123000000, 'event.kind': 'event', 'event.module': 'iis', 'event.category': ['web', 'network'], 'event.type': ['connection'], 'event.dataset': 'iis.access', 'event.outcome': 'success', 'user_agent.original': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0', 'user_agent.os.name': 'Windows', 'user_agent.os.version': '7', 'user_agent.os.full': 'Windows 7', 'user_agent.name': 'Firefox', 'user_agent.device.name': 'Other', 'user_agent.version': '57.0.'} assert 1 == 0  +  where 1 = len({'dictionary_item_added': [root['source.geo.country_name']]})
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_004_iis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 2.188
  * Error Details: AssertionError: The following expected object doesn't match:    Diff:   {'dictionary_item_added': [root['source.geo.country_name']]}, full object:    {'log.offset': 286, 'destination.address': '127.0.0.1', 'destination.port': 80, 'destination.ip': '127.0.0.1', 'source.geo.continent_name': 'Europe', 'source.geo.region_iso_code': 'DE-BE', 'source.geo.city_name': 'Berlin', 'source.geo.country_iso_code': 'DE', 'source.geo.country_name': 'Germany', 'source.geo.region_name': 'Land Berlin', 'source.geo.location.lon': 13.4531, 'source.geo.location.lat': 52.4473, 'source.as.number': 6805, 'source.as.organization.name': 'Telefonica Germany', 'source.address': '85.181.35.98', 'source.port': 2780, 'source.ip': '85.181.35.98', 'fileset.name': 'error', 'url.original': '/ThisIsMyUrl.htm', 'input.type': 'log', 'iis.error.reason_phrase': 'Hostname', '@timestamp': '2018-01-01T09:10:11.000Z', 'related.ip': ['85.181.35.98', '127.0.0.1'], 'service.type': 'iis', 'http.request.method': 'GET', 'http.response.status_code': 400, 'http.version': '1.1', 'event.kind': 'event', 'event.module': 'iis', 'event.category': ['web', 'network'], 'event.type': ['connection'], 'event.dataset': 'iis.error', 'event.outcome': 'failure'} assert 1 == 0  +  where 1 = len({'dictionary_item_added': [root['source.geo.country_name']]})
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_006_iis – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 2.107
  * Error Details: AssertionError: The following expected object doesn't match:    Diff:   {'dictionary_item_added': [root['source.geo.country_name']]}, full object:    {'log.offset': 0, 'destination.address': '192.168.101.101', 'destination.port': 443, 'destination.ip': '192.168.101.101', 'source.geo.continent_name': 'North America', 'source.geo.country_iso_code': 'US', 'source.geo.country_name': 'United States', 'source.geo.location.lon': -97.822, 'source.geo.location.lat': 37.751, 'source.address': '149.42.83.135', 'source.port': 12345, 'source.ip': '149.42.83.135', 'fileset.name': 'error', 'url.original': '12.2.1', 'input.type': 'log', 'iis.error.reason_phrase': 'URL', '@timestamp': '2018-05-05T05:05:55.000Z', 'related.ip': ['149.42.83.135', '192.168.101.101'], 'service.type': 'iis', 'http.request.method': 't3', 'http.response.status_code': 400, 'http.version': '0.9', 'event.kind': 'event', 'event.module': 'iis', 'event.category': ['web', 'network'], 'event.type': ['connection'], 'event.dataset': 'iis.error', 'event.outcome': 'failure'} assert 1 == 0  +  where 1 = len({'dictionary_item_added': [root['source.geo.country_name']]})
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_029_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 2.446
  * Error Details: AssertionError: The following expected object doesn't match:    Diff:   {'dictionary_item_added': [root['source.geo.country_name']]}, full object:    {'nginx.access.remote_ip_list': ['10.0.0.2', '10.0.0.1', '85.181.35.98'], 'log.offset': 341, 'source.geo.continent_name': 'Europe', 'source.geo.region_iso_code': 'DE-BE', 'source.geo.city_name': 'Berlin', 'source.geo.country_iso_code': 'DE', 'source.geo.country_name': 'Germany', 'source.geo.region_name': 'Land Berlin', 'source.geo.location.lon': 13.4531, 'source.geo.location.lat': 52.4473, 'source.as.number': 6805, 'source.as.organization.name': 'Telefonica Germany', 'source.address': '85.181.35.98', 'source.ip': '85.181.35.98', 'fileset.name': 'access', 'url.original': '/ocelot', 'input.type': 'log', '@timestamp': '2016-12-07T10:05:07.000Z', 'related.ip': ['85.181.35.98'], 'service.type': 'nginx', 'http.request.method': 'GET', 'http.response.status_code': 200, 'http.response.body.bytes': 571, 'http.version': '1.1', 'event.timezone': '-02:00', 'event.kind': 'event', 'event.module': 'nginx', 'event.category': ['web'], 'event.type': ['access'], 'event.dataset': 'nginx.access', 'event.outcome': 'success', 'user_agent.original': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0', 'user_agent.os.name': 'Mac OS X', 'user_agent.os.version': '10.12', 'user_agent.os.full': 'Mac OS X 10.12', 'user_agent.name': 'Firefox', 'user_agent.device.name': 'Mac', 'user_agent.version': '49.0.'} assert 1 == 0  +  where 1 = len({'dictionary_item_added': [root['source.geo.country_name']]})
    
* **Name**: `Build&Test / filebeat-build / test_fileset_file_030_nginx – filebeat.tests.system.test_modules.Test`
  * Age: 1
  * Duration: 2.212
  * Error Details: AssertionError: The following expected object doesn't match:    D [...]