[Filebeat][New Fileset] Cisco Umbrella support
elastic/beats pull request #21504
Opened 2020-10-04 15:14 UTC by P1llus

## What does this PR do?

This adds support for Cisco Umbrella logs to filebeat

## Why is it important?

Adds support for new OOTB integrations for filebeat

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #20694

2020-10-04 15:14 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-10-04 16:16 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21504/detail/PR-21504/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21504/detail/PR-21504/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21504/detail/PR-21504/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21504/detail/PR-21504/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21504.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21504 opened]`

* Start Time: 2020-10-04T15:15:39.114+0000

* Duration: 61 min 47 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2210  |
| Skipped      | 265 |
| Total        | 2475   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `mage build test`
    * Description: mage build test
    
    * Duration: 10 min 36 sec
    
    * Start Time: 2020-10-04T15:42:03.217+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21504/runs/1/steps/778/log)
    
  
  * **Name**: `Extract`
    * Description:  tar  -xpf source.tgz
    
    * Duration: 1 min 32 sec
    
    * Start Time: 2020-10-04T15:43:32.623+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21504/runs/1/steps/799/log)
    
  
  * **Name**: `Error signal`
    * Description: untar: step failed with error script returned exit code 1
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-04T15:44:05.133+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21504/runs/1/steps/803/log)
    
  
  * **Name**: `Extract`
    * Description:  tar  -xpf source.tgz
    
    * Duration: 1 min 34 sec
    
    * Start Time: 2020-10-04T15:46:01.189+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21504/runs/1/steps/826/log)
    
  
  * **Name**: `Error signal`
    * Description: untar: step failed with error script returned exit code 1
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-04T15:46:35.662+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21504/runs/1/steps/830/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-04T16:14:42.964Z] Unable to find image 'alpine:3.4' locally
[2020-10-04T16:14:43.905Z] 3.4: Pulling from library/alpine
[2020-10-04T16:14:44.166Z] c1e54eec4b57: Pulling fs layer
[2020-10-04T16:14:44.429Z] c1e54eec4b57: Verifying Checksum
[2020-10-04T16:14:44.430Z] c1e54eec4b57: Download complete
[2020-10-04T16:14:44.690Z] c1e54eec4b57: Pull complete
[2020-10-04T16:14:44.690Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
[2020-10-04T16:14:44.691Z] Status: Downloaded newer image for alpine:3.4
[2020-10-04T16:14:46.923Z] + python .ci/scripts/pre_archive_test.py
[2020-10-04T16:14:48.838Z] Copy ./x-pack/filebeat/build into build/x-pack/filebeat/build
[2020-10-04T16:14:48.859Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21504/src/github.com/elastic/beats/build
[2020-10-04T16:14:48.891Z] WARNING: Unknown parameter(s) found for class type 'hudson.tasks.junit.pipeline.JUnitResultsStep': id,stashedTestReports
[2020-10-04T16:14:48.895Z] Recording test results
[2020-10-04T16:14:50.349Z] Stashed 4 file(s)
[2020-10-04T16:14:50.369Z] Archiving artifacts
[2020-10-04T16:14:51.090Z] + python .ci/scripts/search_system_tests.py
[2020-10-04T16:14:51.115Z] [INFO] system-tests='build/x-pack/filebeat/build/system-tests'. If no empty then let's create a tarball
[2020-10-04T16:14:51.453Z] + tar --version
[2020-10-04T16:14:51.802Z] + tar --exclude=x-pack-filebeat--system-tests-linux.tgz -czf x-pack-filebeat--system-tests-linux.tgz build/x-pack/filebeat/build/system-tests
[2020-10-04T16:15:18.420Z] Archiving artifacts
[2020-10-04T16:15:31.020Z] Client: Docker Engine - Community
[2020-10-04T16:15:31.021Z]  Version:           19.03.13
[2020-10-04T16:15:31.021Z]  API version:       1.40
[2020-10-04T16:15:31.021Z]  Go version:        go1.13.15
[2020-10-04T16:15:31.021Z]  Git commit:        4484c46d9d
[2020-10-04T16:15:31.021Z]  Built:             Wed Sep 16 17:02:36 2020
[2020-10-04T16:15:31.021Z]  OS/Arch:           linux/amd64
[2020-10-04T16:15:31.021Z]  Experimental:      false
[2020-10-04T16:15:31.021Z] 
[2020-10-04T16:15:31.021Z] Server: Docker Engine - Community
[2020-10-04T16:15:31.021Z]  Engine:
[2020-10-04T16:15:31.021Z]   Version:          19.03.13
[2020-10-04T16:15:31.021Z]   API version:      1.40 (minimum version 1.12)
[2020-10-04T16:15:31.021Z]   Go version:       go1.13.15
[2020-10-04T16:15:31.021Z]   Git commit:       4484c46d9d
[2020-10-04T16:15:31.021Z]   Built:            Wed Sep 16 17:01:06 2020
[2020-10-04T16:15:31.021Z]   OS/Arch:          linux/amd64
[2020-10-04T16:15:31.021Z]   Experimental:     false
[2020-10-04T16:15:31.021Z]  containerd:
[2020-10-04T16:15:31.021Z]   Version:          1.3.7
[2020-10-04T16:15:31.021Z]   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
[2020-10-04T16:15:31.021Z]  runc:
[2020-10-04T16:15:31.021Z]   Version:          1.0.0-rc10
[2020-10-04T16:15:31.021Z]   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
[2020-10-04T16:15:31.021Z]  docker-init:
[2020-10-04T16:15:31.021Z]   Version:          0.18.0
[2020-10-04T16:15:31.021Z]   GitCommit:        fec3683
[2020-10-04T16:15:44.090Z] [INFO] unstashV2: JOB_GCS_BUCKET is set. bucket param got precedency instead.
[2020-10-04T16:15:44.115Z] [INFO] unstashV2: JOB_GCS_CREDENTIALS is set. credentialsId param got precedency instead.
[2020-10-04T16:15:44.208Z] [Google Cloud Storage Plugin] Found 1 files to download from pattern: gs://beats-ci-temp/Beats/beats/PR-21504-1/source/source.tgz
[2020-10-04T16:15:44.226Z] [Google Cloud Storage Plugin] Downloading: Beats/beats/PR-21504-1/source/source.tgz to local path: /var/lib/jenkins/workspace/Beats_beats_PR-21504/source.tgz
[2020-10-04T16:15:53.421Z] + tar --version
[2020-10-04T16:15:53.733Z] + tar -xpf source.tgz
[2020-10-04T16:16:04.067Z] + rm source.tgz
[2020-10-04T16:16:04.256Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21504/src/github.com/elastic/beats
[2020-10-04T16:16:04.287Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21504/src/github.com/elastic/beats/uncategorized-1601825894162
[2020-10-04T16:16:04.387Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21504/src/github.com/elastic/beats/filebeat-build-1601826703974
[2020-10-04T16:16:04.480Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21504/src/github.com/elastic/beats/x-pack-filebeat-build-1601828089941
[2020-10-04T16:16:04.901Z] + cat
[2020-10-04T16:16:04.901Z] + /usr/local/bin/runbld ./runbld-test-reports --job-name elastic+beats+pull-request
[2020-10-04T16:16:04.901Z] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[2020-10-04T16:16:11.510Z] runbld>>> runbld started
[2020-10-04T16:16:11.510Z] runbld>>> 1.6.12/f45d832f2ba0aa2722ab4ec1fda8ad140f027f8b
[2020-10-04 [...]

2020-10-04 20:56 UTC, P1llus commented
jenkins test this please

2020-10-05 07:41 UTC, marc-gr approved these changes

2020-10-05 10:45 UTC, adriansr requested changes
Just some suggestions for docs

2020-10-05 10:45 UTC, adriansr commented on filebeat/docs/modules/cisco.asciidoc
> +The Cisco Umbrella fileset is dependant on that the original file path structure is to be followed. This structure is documented https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-ver
First phrase sounds a little odd to me. What about:
```suggestion
The Cisco Umbrella fileset depends on the original file path structure being followed. This structure is documented https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-versioning[Umbrella Log Formats and Versioning]:
```

2020-10-05 10:45 UTC, adriansr commented on filebeat/docs/modules/cisco.asciidoc
> +When configuring the fileset, please ensure that the Queue url is set to the root folder that includes each of these subfolders above.
```suggestion
When configuring the fileset, please ensure that the Queue URL is set to the root folder that includes each of these subfolders above.
```

2020-10-05 10:45 UTC, adriansr commented on filebeat/docs/modules/cisco.asciidoc
> +- `meraki` fileset: supports Cisco Meraki logs.
Thanks for adding this missing entry.

2020-10-05 10:59 UTC, P1llus commented
Thanks for the pointers @adriansr, the doc changes totally made sense! Added them in :)

2020-10-05 11:02 UTC, adriansr approved these changes

2020-10-05 14:52 UTC, merged