adding setTags function to convert MISP tags to elastic event tags
elastic/beats pull request #21664
Opened 2020-10-07 21:55 UTC by hungnguyen-elastic

//Converting tags from MISP event to elastic event tags
    var setTags = function (evt) {
      var mispTags = evt.Get("json.Tag");
      var elasticTags = [];
      mispTags.forEach(function(item){
        elasticTags.push(item.name);
      });
      evt.Put("tags", elasticTags);
   };

.Add(setTags)

## What does this PR do?

This PR adds the code to convert MISP tags to Elastic event Tags. This will open up automation opportunity in Elastic from MISP

## Why is it important?

This will open up automation opportunity in Elastic from MISP. This also can allow threat content engineers to create threat matching or SIEM signal rules based on the MISP tags that are now added to the Elastic event through the MISP module

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [hung.nguyen@elastic.co ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

![image](https://user-images.githubusercontent.com/70958189/95392089-c4e33d80-08bd-11eb-89af-847bf2ae8558.png)
![image](https://user-images.githubusercontent.com/70958189/95392182-ea704700-08bd-11eb-833e-738105f82726.png)

## Logs

2020-10-07 23:00 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_21664.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #21664 opened]`

* Start Time: 2020-10-07T21:56:01.773+0000

* Duration: 65 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 1946  |
| Skipped      | 259 |
| Total        | 2206   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//tests)
  <details><summary>Expand to view the tests failures</summary>
  <p>
    
* **Name**: `Build&Test / x-pack/filebeat-build / test_fileset_file_237_misp – x-pack.filebeat.tests.system.test_xpack_modules.XPackTest`
  * Age: 1
  * Duration: 3.344
  * Error Details: AssertionError: not error expected but got: {'agent': {'name': '5ee0cf2ad087', 'id': '7973a356-7e6e-49da-b2c0-2bd98a091cd0', 'type': 'filebeat', 'ephemeral_id': '6b07788e-118b-49ca-9a18-48ea069f92f2', 'version': '8.0.0'}, 'log': {'file': {'path': '/go/src/github.com/elastic/beats/x-pack/filebeat/module/misp/threat/test/misp-test.json.log'}, 'offset': 0}, 'destination': {'geo': {'continent_name': 'North America', 'region_iso_code': 'US-PA', 'city_name': 'State College', 'country_iso_code': 'US', 'country_name': 'United States', 'region_name': 'Pennsylvania', 'location': {'lon': -77.8618, 'lat': 40.7957}}, 'ip': '98.235.162.24'}, 'rule': {'description': 'Tor exit nodes feed', 'id': '1', 'category': 'Network activity', 'uuid': '58dcfe62-ed84-4e5e-b293-4991950d210f'}, 'misp': {'threat_indicator': {'attack_pattern': "[destination:ip = '98.235.162.24']", 'feed': 'misp', 'attack_pattern_kql': 'destination.ip: "98.235.162.24"', 'description': 'Tor exit nodes feed', 'id': '58dcfe62-ed84-4e5e-b293-4991950d210f', 'type': 'ip-dst'}}, 'fileset': {'name': 'threat'}, 'error': {'message': "TypeError: Cannot read property 'forEach' of undefined at /go/src/github.com/elastic/beats/x-pack/filebeat/module/misp/threat/config/pipeline.js:44:7(16)"}, 'message': '98.235.162.24', 'tags': ['_js_exception'], 'input': {'type': 'log'}, '@timestamp': '2017-03-30T12:54:26.000Z', 'ecs': {'version': '1.6.0'}, 'service': {'type': 'misp'}, 'host': {'name': '5ee0cf2ad087'}, 'event': {'ingested': '2020-10-07T22:56:39.151516911Z', 'kind': 'event', 'module': 'misp', 'id': '5d2cb906-eff4-40f0-9f1d-10eb7d6a0c26', 'type': 'indicator', 'category': 'threat-intel', 'dataset': 'misp.threat'}}.    The related error message is: TypeError: Cannot read property 'forEach' of undefined at /go/src/github.com/elastic/beats/x-pack/filebeat/module/misp/threat/config/pipeline.js:44:7(16) assert 'error' not in {'@timestamp': '2017-03-30T12:54:26.000Z', 'agent': {'ephemeral_id': '6b07788e-118b-49ca-9a18-48ea069f92f2', 'id': '79...untry_iso_code': 'US', 'country_name': 'United States', ...}, 'ip': '98.235.162.24'}, 'ecs': {'version': '1.6.0'}, ...}
    
  </p>
  </details>


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-21664/detail/PR-21664/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `mage build test`
    * Description: mage build test
    
    * Duration: 33 min 16 sec
    
    * Start Time: 2020-10-07T22:24:16.389+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21664/runs/1/steps/725/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-07T22:57:34.363Z] Status: Downloaded newer image for alpine:3.4
[2020-10-07T22:57:36.608Z] + python .ci/scripts/pre_archive_test.py
[2020-10-07T22:57:38.530Z] Copy ./x-pack/filebeat/build into build/x-pack/filebeat/build
[2020-10-07T22:57:38.555Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-21664/src/github.com/elastic/beats/build
[2020-10-07T22:57:38.909Z] + rm -rf ve
[2020-10-07T22:57:38.910Z] + find . -type d -name vendor -exec rm -r {} ;
[2020-10-07T22:57:38.933Z] WARNING: Unknown parameter(s) found for class type 'hudson.tasks.junit.pipeline.JUnitResultsStep': id,stashedTestReports
[2020-10-07T22:57:38.937Z] Recording test results
[2020-10-07T22:57:40.277Z] Stashed 4 file(s)
[2020-10-07T22:57:40.613Z] + tar --version
[2020-10-07T22:57:40.974Z] + tar --exclude=test-build-artifacts-x-pack/filebeat-build.tgz -czf test-build-artifacts-x-pack/filebeat-build.tgz .
[2020-10-07T22:58:19.807Z] Archiving artifacts
[2020-10-07T22:58:44.667Z] + python .ci/scripts/search_system_tests.py
[2020-10-07T22:58:44.729Z] [INFO] system-tests='build/x-pack/filebeat/build/system-tests'. If no empty then let's create a tarball
[2020-10-07T22:58:45.096Z] + tar --version
[2020-10-07T22:58:45.473Z] + tar --exclude=x-pack-filebeat--system-tests-linux.tgz -czf x-pack-filebeat--system-tests-linux.tgz build/x-pack/filebeat/build/system-tests
[2020-10-07T22:59:07.491Z] Archiving artifacts
[2020-10-07T22:59:20.565Z] Client: Docker Engine - Community
[2020-10-07T22:59:20.565Z]  Version:           19.03.13
[2020-10-07T22:59:20.565Z]  API version:       1.40
[2020-10-07T22:59:20.565Z]  Go version:        go1.13.15
[2020-10-07T22:59:20.565Z]  Git commit:        4484c46d9d
[2020-10-07T22:59:20.565Z]  Built:             Wed Sep 16 17:02:36 2020
[2020-10-07T22:59:20.565Z]  OS/Arch:           linux/amd64
[2020-10-07T22:59:20.565Z]  Experimental:      false
[2020-10-07T22:59:20.565Z] 
[2020-10-07T22:59:20.565Z] Server: Docker Engine - Community
[2020-10-07T22:59:20.565Z]  Engine:
[2020-10-07T22:59:20.565Z]   Version:          19.03.13
[2020-10-07T22:59:20.565Z]   API version:      1.40 (minimum version 1.12)
[2020-10-07T22:59:20.565Z]   Go version:       go1.13.15
[2020-10-07T22:59:20.565Z]   Git commit:       4484c46d9d
[2020-10-07T22:59:20.565Z]   Built:            Wed Sep 16 17:01:06 2020
[2020-10-07T22:59:20.565Z]   OS/Arch:          linux/amd64
[2020-10-07T22:59:20.565Z]   Experimental:     false
[2020-10-07T22:59:20.565Z]  containerd:
[2020-10-07T22:59:20.565Z]   Version:          1.3.7
[2020-10-07T22:59:20.565Z]   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
[2020-10-07T22:59:20.565Z]  runc:
[2020-10-07T22:59:20.565Z]   Version:          1.0.0-rc10
[2020-10-07T22:59:20.565Z]   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
[2020-10-07T22:59:20.565Z]  docker-init:
[2020-10-07T22:59:20.565Z]   Version:          0.18.0
[2020-10-07T22:59:20.565Z]   GitCommit:        fec3683
[2020-10-07T22:59:27.570Z] Failed in branch x-pack/filebeat-build
[2020-10-07T22:59:32.813Z] [INFO] unstashV2: JOB_GCS_BUCKET is set. bucket param got precedency instead.
[2020-10-07T22:59:32.839Z] [INFO] unstashV2: JOB_GCS_CREDENTIALS is set. credentialsId param got precedency instead.
[2020-10-07T22:59:32.910Z] [Google Cloud Storage Plugin] Found 1 files to downloa [...]

2020-10-08 21:14 UTC, andrewkroh requested changes
Thanks @hungnguyen-elastic 

- [x] Please add a JSON event to the test directory that contains this `Tag` field.
- [x] Add an entry to the CHANGELOG.next.asciidoc file under the Added/Filebeat section.
- [ ] Update the golden test files (`cd x-pack/filebeat; GENERATE=true PYTEST_ADDOPTS="-k misp" mage -v pythonIntegTest`). If you have trouble we can do this step.

2020-10-08 21:14 UTC, andrewkroh commented on x-pack/filebeat/module/misp/threat/config/pipeline.js
> +          elasticTags.push(item.name);
You can use `evt.AppendTo("tags", item.name)`.

2020-10-08 21:14 UTC, andrewkroh commented on x-pack/filebeat/module/misp/threat/config/pipeline.js
> +    var setTags = function (evt) {
```suggestion
    // Copy tags from MISP event to Elastic event tags.
    var setTags = function (evt) {
```

2020-10-30 22:06 UTC, elasticmachine commented
## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1947  |
| Skipped      | 259 |
| Total        | 2206   |




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_flaky.id-->

2020-10-30 22:07 UTC, andrewkroh approved these changes

2020-10-30 22:19 UTC, merged

2020-11-02 14:03 UTC, hungnguyen-elastic commented
Thanks @andrewkroh