[build][packaging] Add resilience when docker build
elastic/beats pull request #22050
Opened 2020-10-21 14:08 UTC by v1v

## What does this PR do?

Retry to build docker images when something bad happened.

We could potentially include a retry step in the CI but it might add some overhead, another approach could be creating a specific mage goal to run the `docker build` rather than just using the mage goal for everything.

## Why is it important?

Sometimes some third party resources are not accessible temporarily

## Related issues

Caused by https://github.com/elastic/beats/issues/21563

2020-10-21 14:08 UTC, elasticmachine commented
Pinging @elastic/ingest-management (Team:Ingest Management)

2020-10-21 14:15 UTC, mdelapenya commented on x-pack/elastic-agent/magefile.go
> +func dockerBuild(tag) string {
Type needs to be added
```suggestion
func dockerBuild(tag string) string {
```

2020-10-21 14:17 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22050/detail/PR-22050/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22050/detail/PR-22050/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22050/detail/PR-22050/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22050/detail/PR-22050/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_22050.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #22050 opened]`

* Start Time: 2020-10-21T14:09:33.313+0000

* Duration: 7 min 19 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22050/detail/PR-22050/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  
  * **Name**: `Dump mage variables`
    * Description: mage dumpVariables
    
    * Duration: 0 min 11 sec
    
    * Start Time: 2020-10-21T14:15:55.545+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22050/runs/1/steps/144/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-21T14:15:32.627Z] ++ awk '{print $3}'
[2020-10-21T14:15:32.627Z] ++ sed s/,//
[2020-10-21T14:15:32.627Z] + FOUND_DOCKER_COMPOSE_VERSION=1.23.2
[2020-10-21T14:15:32.627Z] + '[' 1.23.2 == 1.21.0 ']'
[2020-10-21T14:15:32.627Z] + echo 'UNMET DEP: Installing docker-compose'
[2020-10-21T14:15:32.627Z] UNMET DEP: Installing docker-compose
[2020-10-21T14:15:32.627Z] + DC_CMD=/var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/docker-compose
[2020-10-21T14:15:32.627Z] + mkdir -p /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin
[2020-10-21T14:15:32.627Z] ++ uname -s
[2020-10-21T14:15:32.627Z] ++ uname -m
[2020-10-21T14:15:32.627Z] + curl -sSLo /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/docker-compose https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64
[2020-10-21T14:15:33.199Z] + chmod +x /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/docker-compose
[2020-10-21T14:15:33.199Z] + .ci/scripts/install-terraform.sh
[2020-10-21T14:15:33.199Z] + MSG='environment variable missing.'
[2020-10-21T14:15:33.199Z] + TERRAFORM_VERSION=0.12.24
[2020-10-21T14:15:33.199Z] + HOME=/var/lib/jenkins/workspace/Beats_beats_PR-22050
[2020-10-21T14:15:33.199Z] + TERRAFORM_CMD=/var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform
[2020-10-21T14:15:33.199Z] ++ uname -s
[2020-10-21T14:15:33.199Z] ++ tr '[:upper:]' '[:lower:]'
[2020-10-21T14:15:33.199Z] + OS=linux
[2020-10-21T14:15:33.199Z] + command -v terraform
[2020-10-21T14:15:33.199Z] + echo 'UNMET DEP: Installing Terraform'
[2020-10-21T14:15:33.199Z] UNMET DEP: Installing Terraform
[2020-10-21T14:15:33.199Z] + mkdir -p /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin
[2020-10-21T14:15:33.199Z] + curl -sSLo - https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
[2020-10-21T14:15:33.770Z] ++ dirname /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform
[2020-10-21T14:15:33.770Z] + unzip -o /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform.zip -d /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin
[2020-10-21T14:15:33.770Z] Archive:  /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform.zip
[2020-10-21T14:15:34.381Z]   inflating: /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform  
[2020-10-21T14:15:34.381Z] + rm /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform.zip
[2020-10-21T14:15:34.381Z] + chmod +x /var/lib/jenkins/workspace/Beats_beats_PR-22050/bin/terraform
[2020-10-21T14:15:34.381Z] + make mage
[2020-10-21T14:15:34.381Z] Installing mage v1.10.0.
[2020-10-21T14:15:35.325Z] go: downloading github.com/magefile/mage v1.10.0
[2020-10-21T14:15:36.711Z] /var/lib/jenkins/workspace/Beats_beats_PR-22050/.magefile cleaned
[2020-10-21T14:15:37.057Z] + git config --get user.email
[2020-10-21T14:15:37.057Z] + [ -z  ]
[2020-10-21T14:15:37.057Z] + git config --global user.email beatsmachine@users.noreply.github.com
[2020-10-21T14:15:37.057Z] + git config --global user.name beatsmachine
[2020-10-21T14:15:37.374Z] + go mod download
[2020-10-21T14:15:55.522Z] ### MAGE DUMP ###
[2020-10-21T14:15:55.842Z] + mage dumpVariables
[2020-10-21T14:16:05.876Z] # github.com/elastic/beats/v7/dev-tools/mage
[2020-10-21T14:16:05.876Z] dev-tools/mage/dockerbuilder.go:78:3: tag declared but not used
[2020-10-21T14:16:06.138Z] Error: error compiling magefiles
[2020-10-21T14:16:06.496Z] Client: Docker Engine - Community
[2020-10-21T14:16:06.497Z]  Version:           19.03.13
[2020-10-21T14:16:06.497Z]  API version:       1.40
[2020-10-21T14:16:06.497Z]  Go version:        go1.13.15
[2020-10-21T14:16:06.497Z]  Git commit:        4484c46d9d
[2020-10-21T14:16:06.497Z]  Built:             Wed Sep 16 17:02:36 2020
[2020-10-21T14:16:06.497Z]  OS/Arch:           linux/amd64
[2020-10-21T14:16:06.497Z]  Experimental:      false
[2020-10-21T14:16:06.497Z] 
[2020-10-21T14:16:06.497Z] Server: Docker Engine - Community
[2020-10-21T14:16:06.497Z]  Engine:
[2020-10-21T14:16:06.497Z]   Version:          19.03.13
[2020-10-21T14:16:06.497Z]   API version:      1.40 (minimum version 1.12)
[2020-10-21T14:16:06.497Z]   Go version:       go1.13.15
[2020-10-21T14:16:06.497Z]   Git commit:       4484c46d9d
[2020-10-21T14:16:06.497Z]   Built:            Wed Sep 16 17:01:06 2020
[2020-10-21T14:16:06.497Z]   OS/Arch:          linux/amd64
[2020-10-21T14:16:06.497Z]   Experimental:     false
[2020-10-21T14:16:06.497Z]  containerd:
[2020-10-21T14:16:06.497Z]   Version:          1.3.7
[2020-10-21T14:16:06.497Z]   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
[2020-10-21T14:16:06.497Z]  runc:
[2020-10-21T14:16:06.497Z]   Version:          1.0.0-rc10
[2020-10-21T14:16:06.497Z]   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
[2020-10-21T14:16:06.497Z]  docker-init:
[2020-10-21T14:16:06.497Z]   Version:          0.18.0
[2020-10-21T14:16:06.497Z]   GitCommit:        fec3683
[2020-10-21T14:16:06.497Z] Unable to find image 'alpine:3.4' locally
[2020-10-21T14:16:07.068Z] 3.4: Pulling from library/alpine
[2020-10-21T14:16:07.330Z] c1e54eec4b57: Pulling fs layer
[2020-10-21T14:16:07.592Z] c1e54eec4b57: Verifying Checksum
[2020-10-21T14:16:07.593Z] c1e54eec4b57: Download complete
[2020-10-21T14:16:07.593Z] c1e54eec4b57: Pull complete
[2020-10-21T14:16:07.593Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
[2020-10-21T14:16:07.593Z] Status: Downloaded newer image for alpine:3.4
[2020-10-21T14:16:25.264Z] Stage "Build&Test" skipped due to earlier failure(s)
[2020-10-21T14:16:29.784Z] [INFO] unstashV2: JOB_GCS_BUCKET is set. bucket param got precedency instead.
[2020-10-21T14:16:29.805Z] [INFO] unstashV2: JOB_GCS_CREDENTIALS is set. credentialsId param got precedency instead.
[2020-10-21T14:16:29.867Z] [Google Cloud Storage Plugin] Found 1 files to download from pattern: gs://beats-ci-temp/Beats/beats/PR-22050-1/source/source.tgz
[2020-10-21T14:16:29.884Z] [Google Cloud Storage Plugin] Downloading: Beats/beats/PR-22050-1/source/source.tgz to local path: /var/ [...]

2020-10-21 14:25 UTC, kuisathaverat commented
probably it resolves also https://github.com/elastic/beats/issues/22020

2020-10-21 14:28 UTC, kuisathaverat approved these changes

2020-10-21 16:20 UTC, cachedout approved these changes

2020-10-21 17:19 UTC, jsoriano requested changes

2020-10-21 17:19 UTC, jsoriano commented on libbeat/tests/compose/wrapper.go
> +
There are already some retries in the higher-level [`EnsureUp` method](https://github.com/elastic/beats/blob/addadf2f692949a3b90c2825adb150acf952c7d0/libbeat/tests/compose/compose.go#L99), that is the one used out of this package.

Also, we shouldn't add a explicit build here, we should take into account `opts.Create.Build` and so on.

I think this code is not needed.

2020-10-22 09:25 UTC, jsoriano approved these changes
:+1:

2020-10-22 10:38 UTC, merged