Add IO operations in progress to be exported in diskio module
elastic/beats pull request #22066
Opened 2020-10-22 05:39 UTC by VertexC

## What does this PR do?
Add `io.ops` in fields exported by system.diskio in metricbeat.
  
## Why is it important?
As elastic/beats#20691 points out, we may need to calculate the queue time based on this new field `system.diskio.io.ops`.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works

## Related issues
- Closes  elastic/beats#20691

2020-10-22 05:39 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-10-22 05:39 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-10-22 05:44 UTC, VertexC commented
@andresrc Could you kindly review this PR?

2020-10-22 05:44 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22066/detail/PR-22066/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22066/detail/PR-22066/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22066/detail/PR-22066/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22066/detail/PR-22066/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #22066 opened]`

* Reason: `The PR is not allowed to run in the CI yet`

* Start Time: 2020-10-22T05:40:30.083+0000

* Duration: 4 min 59 sec


* Commit: 6ff88467999482708531620f6eaef2fda4ee597d




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22066/detail/PR-22066/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  
  * **Name**: `Error signal`
    * Description: githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permission
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-22T05:44:23.700+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22066/runs/1/steps/77/log)
    
  
  * **Name**: `General Build Step`
    * Description: 
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-22T05:44:27.503+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22066/runs/1/steps/100/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-22T05:43:07.682Z] Cleaning workspace
[2020-10-22T05:43:07.698Z] Using shallow fetch with depth 10
[2020-10-22T05:43:07.698Z] Pruning obsolete local branches
[2020-10-22T05:43:07.665Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2020-10-22T05:43:07.669Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-10-22T05:43:07.677Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2020-10-22T05:43:07.684Z]  > git rev-parse --verify HEAD # timeout=10
[2020-10-22T05:43:07.690Z] No valid HEAD. Skipping the resetting
[2020-10-22T05:43:07.690Z]  > git clean -fdx # timeout=10
[2020-10-22T05:43:07.700Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2020-10-22T05:43:07.700Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-10-22T05:43:07.705Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/22066/head:refs/remotes/origin/PR-22066 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2020-10-22T05:43:08.784Z] Merging remotes/origin/master commit ba2b2f935f1c6badc316f62417d87d630991ad2f into PR head commit 6ff88467999482708531620f6eaef2fda4ee597d
[2020-10-22T05:43:08.787Z]  > git config core.sparsecheckout # timeout=10
[2020-10-22T05:43:08.792Z]  > git checkout -f 6ff88467999482708531620f6eaef2fda4ee597d # timeout=15
[2020-10-22T05:43:10.282Z] Merge succeeded, producing 6ff88467999482708531620f6eaef2fda4ee597d
[2020-10-22T05:43:10.282Z] Checking out Revision 6ff88467999482708531620f6eaef2fda4ee597d (PR-22066)
[2020-10-22T05:43:10.927Z] Commit message: "add IO operations in progress to be exported in diskio module"
[2020-10-22T05:43:10.927Z] Cleaning workspace
[2020-10-22T05:43:11.406Z]  > git --version # timeout=10
[2020-10-22T05:43:11.424Z]  > git --version # 'git version 2.17.1'
[2020-10-22T05:43:11.440Z] fatal: bad object dc07f0745f9821353e0d44a4eaebd2a238f62b10
[2020-10-22T05:43:10.240Z]  > git remote # timeout=10
[2020-10-22T05:43:10.244Z]  > git config --get remote.origin.url # timeout=10
[2020-10-22T05:43:10.252Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-10-22T05:43:10.262Z]  > git merge ba2b2f935f1c6badc316f62417d87d630991ad2f # timeout=10
[2020-10-22T05:43:10.276Z]  > git rev-parse HEAD^{commit} # timeout=10
[2020-10-22T05:43:10.285Z]  > git config core.sparsecheckout # timeout=10
[2020-10-22T05:43:10.292Z]  > git checkout -f 6ff88467999482708531620f6eaef2fda4ee597d # timeout=15
[2020-10-22T05:43:10.929Z]  > git rev-parse --verify HEAD # timeout=10
[2020-10-22T05:43:10.936Z] Resetting working tree
[2020-10-22T05:43:10.936Z]  > git reset --hard # timeout=10
[2020-10-22T05:43:11.333Z]  > git clean -fdx # timeout=10
[2020-10-22T05:43:12.328Z] Masking supported pattern matches of $GIT_USERNAME or $GIT_PASSWORD
[2020-10-22T05:43:13.049Z] + git fetch https://****:****@github.com/elastic/beats.git +refs/pull/*/head:refs/remotes/origin/pr/*
[2020-10-22T05:44:20.851Z] Archiving artifacts
[2020-10-22T05:44:21.577Z] + git rev-parse HEAD
[2020-10-22T05:44:21.946Z] + git rev-parse HEAD
[2020-10-22T05:44:22.261Z] + git rev-parse origin/pr/22066
[2020-10-22T05:44:22.308Z] [INFO] githubEnv: Found Git Build Cause: pr
[2020-10-22T05:44:22.494Z] Masking supported pattern matches of $GITHUB_TOKEN
[2020-10-22T05:44:23.344Z] [WARN] githubApiCall: The REST API call https://api.github.com/repos/elastic/beats/pulls/22066/reviews return 0 elements
[2020-10-22T05:44:23.395Z] [INFO] githubPrCheckApproved: Title: Add IO operations in progress to be exported in diskio module - User: VertexC - Author Association: FIRST_TIME_CONTRIBUTOR
[2020-10-22T05:44:23.719Z] ERROR: githubPrCheckApproved: The PR is not allowed to run in the CI yet
[2020-10-22T05:44:23.719Z] ERROR: githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)
[2020-10-22T05:44:23.790Z] [INFO] Let's stop build #1. The PR is not allowed to run in the CI yet
[2020-10-22T05:44:23.808Z] Sleeping for 5 sec
[2020-10-22T05:44:25.647Z] Stage "Lint" skipped due to earlier failure(s)
[2020-10-22T05:44:25.717Z] Stage "Build&Test" skipped due to earlier failure(s)
[2020-10-22T05:44:27.475Z] [INFO] unstashV2: JOB_GCS_BUCKET is set. bucket param got precedency instead.
[2020-10-22T05:44:27.497Z] [INFO] unstashV2: JOB_GCS_CREDENTIALS is set. credentialsId param got precedency instead.
[2020-10-22T05:44:27.603Z] Error when executing always post condition:
[2020-10-22T05:44:27.609Z] com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
[2020-10-22T05:44:27.609Z] {
[2020-10-22T05:44:27.609Z]   "code" : 404,
[2020-10-22T05:44:27.609Z]   "errors" : [ {
[2020-10-22T05:44:27.609Z]     "domain" : "global",
[2020-10-22T05:44:27.609Z]     "message" : "No such object: beats-ci-temp/Beats/beats/PR-22066-1/source/source.tgz",
[2020-10-22T05:44:27.609Z]     "reason" : "notFound"
[2020-10-22T05:44:27.609Z]   } ],
[2020-10-22T05:44:27.609Z]   "message" : "No such object: beats-ci-temp/Beats/beats/PR-22066-1/source/source.tgz"
[2020-10-22T05:44:27.609Z] }
[2020-10-22T05:44:27.609Z] 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
[2020-10-22T05:44:27.609Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[2020-10-22T05:44:27.609Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnE [...]

2020-10-22 06:44 UTC, elasticmachine commented
Pinging @elastic/integrations-services (Team:Services)

2020-10-22 07:14 UTC, unixsurfer commented
@VertexC I am sorry but I'm not familiar with the development of metricbeats and therefore I can't perform a  proper review.
I would like to thank you for taking the time to add support for IO operations in progress metric.

2020-10-23 02:08 UTC, VertexC commented
> @VertexC I am sorry but I'm not familiar with the development of metricbeats and therefore I can't perform a proper review.
> I would like to thank you for taking the time to add support for IO operations in progress metric.

It is okay :) And thanks for posting this good-for-first issue.

2020-10-30 15:32 UTC, fearful-symmetry requested changes

2020-10-30 15:32 UTC, fearful-symmetry commented on metricbeat/module/system/diskio/diskio.go
> +				"ops":  counters.IopsInProgress,
It looks like this metric is exclusive to linux. We're trying to move away from globally reporting metrics that are exclusive to one or two OSes, as it means that unsupported OSes will report an unhelpful `0`. We'll want to insert this into the MapStr later with a `runtime.GOOS == "linux"` guard.

2020-10-30 15:32 UTC, fearful-symmetry commented on metricbeat/module/system/test_system.py
> +                        "write.bytes", "read.time", "write.time", "io.time", "io.ops"]
Once we guard the `io.ops`, we'll want to remove this.

2020-11-04 07:31 UTC, VertexC commented
The diskio_linux fails in CI due to timeout issue. I only have mac (unix) environment and relevant tests might just skip locally.  Do you have any idea on this timeout error? @fearful-symmetry 

```bash
=================================== FAILURES ===================================
____________________________ Test.test_diskio_linux ____________________________
self = <test_system.Test testMethod=test_diskio_linux>
    @unittest.skipUnless(re.match("(?i)linux", sys.platform), "os")
    def test_diskio_linux(self):
        """
        Test system/diskio output on linux.
        """
        self.render_config_template(modules=[{
            "name": "system",
            "metricsets": ["diskio"],
            "period": "5s"
        }])
        proc = self.start_beat()
>       self.wait_until(lambda: self.output_lines() > 0)
module/system/test_system.py:251: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <test_system.Test testMethod=test_diskio_linux>
cond = <function Test.test_diskio_linux.<locals>.<lambda> at 0x7f9365a1f510>
max_timeout = 10, poll_interval = 0.1, name = 'cond'
    def wait_until(self, cond, max_timeout=10, poll_interval=0.1, name="cond"):
        """
        Waits until the cond function returns true,
        or until the max_timeout is reached. Calls the cond
        function every poll_interval seconds.
    
        If the max_timeout is reached before cond() returns
        true, an exception is raised.
        """
        start = datetime.now()
        while not cond():
            if datetime.now() - start > timedelta(seconds=max_timeout):
                raise TimeoutError("Timeout waiting for '{}' to be true. ".format(name) +
>                                  "Waited {} seconds.".format(max_timeout))
E               beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
../libbeat/tests/system/beat/beat.py:363: TimeoutError
```

2020-11-04 15:35 UTC, fearful-symmetry requested changes

2020-11-04 15:35 UTC, fearful-symmetry commented on metricbeat/module/system/diskio/diskio.go
> +			event["io"].(common.MapStr)["ops"] = counters.IopsInProgress
We probably shouldn't be casting like that. Try using `.Put()` instead.

2020-11-04 15:35 UTC, fearful-symmetry commented
Not sure, I imagine it's a deeper failure that the CI is just reporting as a timeout.

2020-11-10 16:26 UTC, fearful-symmetry commented
Not sure why we're running into CI issues here....

2020-11-10 16:26 UTC, fearful-symmetry commented
jenkins, test this

2020-11-10 17:31 UTC, elasticmachine commented
## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2248  |
| Skipped      | 508 |
| Total        | 2756   |




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_flaky.id-->

2020-11-11 03:01 UTC, VertexC commented
Hmmm, it reports there is one change requested but I don't see any unresolved requested changes. @fearful-symmetry

2020-11-17 03:20 UTC, VertexC commented
@fearful-symmetry Hi, do you have any plan to merge this pr? I'm happy to merge and rebuil fields, but if it is not merged for certain time, new conflicts will occur.

2020-11-17 17:22 UTC, fearful-symmetry commented
Hey, sorry about dropping this last week. We're good to go, it looks like. Just rebase the PR and I can approve it. @VertexC

2020-11-18 17:23 UTC, fearful-symmetry commented
jenkins, test this

2020-11-19 05:25 UTC, VertexC commented
It looks like Lint is somehow blocked. Shall I commit --amend and force push again? @fearful-symmetry

2020-11-19 18:00 UTC, fearful-symmetry commented
Try to merge from master again, yah. Not sure why the CI is blocked now.

2020-11-20 16:34 UTC, fearful-symmetry commented
jenkins, test this

2020-11-20 16:57 UTC, fearful-symmetry commented
@VertexC while I fight with CI, one last thing: Can you add a changelog entry to `CHANGELOG.next.asciidoc` ?

2020-11-23 02:05 UTC, VertexC commented
> @VertexC while I fight with CI, one last thing: Can you add a changelog entry to `CHANGELOG.next.asciidoc` ?

Done :)

2020-11-23 16:35 UTC, fearful-symmetry commented
jenkins, test this

2020-11-23 22:54 UTC, fearful-symmetry approved these changes

2020-11-23 22:56 UTC, merged

2020-11-30 09:54 UTC, andresrc commented
@fearful-symmetry does this need a backport?