docs: Prepare Changelog for 7.10.0
elastic/beats pull request #22339
Opened 2020-11-02 11:24 UTC by andresrc

Prepare Changelog for 7.10.0.

Merge after first BC.

2020-11-02 11:55 UTC, elasticmachine commented
## :grey_exclamation: Flaky test report
No test was executed to be analysed.





</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_flaky.id-->

2020-11-02 11:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22339/detail/PR-22339/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22339/detail/PR-22339/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22339/detail/PR-22339/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22339/detail/PR-22339/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_22339.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #22339 opened]`

* Start Time: 2020-11-02T11:25:04.252+0000

* Duration: 30 min 51 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-11-02 13:46 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2020-11-02 14:10 UTC, v1v reviewed
Some typos

2020-11-02 14:10 UTC, v1v commented on CHANGELOG.asciidoc
> +- Allow embedding of CAs, Certificate of private keys for anything that support TLS in ouputs and inputs https://github.com/elastic/beats/pull/21179
```suggestion
- Allow embedding of CAs, Certificate of private keys for anything that support TLS in outputs and inputs {pull}21179[21179]
```

2020-11-02 14:10 UTC, v1v commented on CHANGELOG.asciidoc
> +- Fix `event.outcome` in the security module for non-English languages. {issue}20079[20079] {pull}20564[2056
```suggestion
- Fix `event.outcome` in the security module for non-English languages. {issue}20079[20079] {pull}20564[2056]
```

2020-11-02 14:10 UTC, v1v commented on CHANGELOG.asciidoc
> +- Fix catchall bucket config errors by adding more validation. {issue}17572[16282] {pull}20887[16287]
```suggestion
- Fix catchall bucket config errors by adding more validation. {issue}17572[17572] {pull}20887[20887]
```

2020-11-02 14:10 UTC, v1v commented on libbeat/docs/release.asciidoc
> +* <<release-notes-7.10.0>>
```suggestion
* <<release-notes-7.10.0>>
* <<release-notes-7.9.3>>
```

2020-11-02 14:51 UTC, andresrc commented
Thanks @v1v !!

2020-11-02 15:08 UTC, hendry-lim requested changes
Added missing code formatting

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add support for azure light metricset app_stats. {pull}20639[20639]
```suggestion
- Add support for azure light metricset `app_stats`. {pull}20639[20639]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Remove io.time from windows {pull}22237[22237]
```suggestion
- Remove `io.time` from windows {pull}22237[22237]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add "network" to event.category {issue}20364[20364] {pull}20392[20392]
```suggestion
- Add "network" to `event.category` {issue}20364[20364] {pull}20392[20392]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add replace_fields config option in add_host_metadata for replacing host fields. {pull}20490[20490] {issue}20464[20464]
```suggestion
- Add `replace_fields` config option in `add_host_metadata` for replacing host fields. {pull}20490[20490] {issue}20464[20464]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add option to select the type of index template to load: legacy, component, index. {pull}21212[21212]
```suggestion
- Add option to select the type of index template to load: `legacy`, `component`, `index`. {pull}21212[21212]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add event.ingested to all Filebeat modules. {pull}20386[20386]
```suggestion
- Add `event.ingested` to all Filebeat modules. {pull}20386[20386]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add event.ingested for Suricata module {pull}20220[20220]
```suggestion
- Add `event.ingested` for Suricata module {pull}20220[20220]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add support for custom header and headersecret for filebeat http_endpoint input {pull}20435[20435]
```suggestion
- Add support for custom header and headersecret for filebeat `http_endpoint` input {pull}20435[20435]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Convert httpjson to v2 input {pull}20226[20226]
```suggestion
- Convert `httpjson` to v2 input {pull}20226[20226]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add event.ingested to all Filebeat modules. {pull}20386[20386]
```suggestion
- Add `event.ingested` to all Filebeat modules. {pull}20386[20386]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Added new properties field support for event.outcome in azure module {pull}20998[20998]
```suggestion
- Added new properties field support for `event.outcome` in azure module {pull}20998[20998]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add type and sub_type to panw panos fileset {pull}20912[20912]
```suggestion
- Add `type` and `sub_type` to panw `panos` fileset {pull}20912[20912]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add related.hosts ecs field to all modules {pull}21160[21160]
```suggestion
- Add `related.hosts` ecs field to all modules {pull}21160[21160]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Keep cursor state between httpjson input restarts {pull}20751[20751]
```suggestion
- Keep cursor state between `httpjson` input restarts {pull}20751[20751]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- New juniper.srx dataset for Juniper SRX logs. {pull}20017[20017]
```suggestion
- New `juniper.srx` dataset for Juniper SRX logs. {pull}20017[20017]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add cloud.instance.name into aws ec2 metricset. {pull}20077[20077]
```suggestion
- Add `cloud.instance.name` into aws ec2 metricset. {pull}20077[20077]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add state_daemonset metricset for Kubernetes Metricbeat module {pull}20649[20649]
```suggestion
- Add `state_daemonset` metricset for Kubernetes Metricbeat module {pull}20649[20649]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add billing metricset into googlecloud module. {pull}20812[20812] {issue}20738[20738]
```suggestion
- Add `billing` metricset into googlecloud module. {pull}20812[20812] {issue}20738[20738]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Release lambda metricset in aws module as GA. {issue}21251[21251] {pull}21255[21255]
```suggestion
- Release `lambda` metricset in aws module as GA. {issue}21251[21251] {pull}21255[21255]
```

2020-11-02 15:08 UTC, hendry-lim commented on CHANGELOG.asciidoc
> +- Add dashboard for pubsub metricset in googlecloud module. {pull}21326[21326] {issue}17137[17137]
```suggestion
- Add dashboard for `pubsub` metricset in googlecloud module. {pull}21326[21326] {issue}17137[17137]
```

2020-11-02 16:41 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +- Allow embedding of CAs, Certificate of private keys for anything that support TLS in outputs and inputs {pull}21179[21179]
```suggestion
- Allow embedding of CAs, Certificate of private keys for anything that supports TLS in outputs and inputs {pull}21179[21179]
```

2020-11-02 16:41 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +- Remove "invalid zero" metrics on Windows and Darwin, don't report linux-only memory and diskio metrics when running under agent. {pull}21457[21457]
```suggestion
- Remove "invalid zero" metrics on Windows and Darwin, don't report linux-only memory and disk I/O metrics when running under agent. {pull}21457[21457]
```

2020-11-02 16:41 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +- Add capability of enriching process metadata with contianer id also for non-privileged containers in `add_process_metadata` processor. {pull}19767[19767]
```suggestion
- Add capability of enriching process metadata with container id also for non-privileged containers in `add_process_metadata` processor. {pull}19767[19767]
```

2020-11-02 16:41 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +- Add `scope` setting for elasticsearch module, allowing it to monitor an Elasticsearch cluster behind a load-balancing proxy. {issue}18539[18539] {pull}18547[18547]
```suggestion
- Add `scope` setting for Elasticsearch module, allowing it to monitor an Elasticsearch cluster behind a load-balancing proxy. {issue}18539[18539] {pull}18547[18547]
```

2020-11-05 17:22 UTC, bmorelli25 approved these changes

2020-11-05 17:22 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +
Duplicate
```suggestion
```

2020-11-05 17:22 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +
Duplicate
```suggestion
```

2020-11-05 17:22 UTC, bmorelli25 commented on CHANGELOG.asciidoc
> +
I would get rid of all of these and just add n/a
```suggestion

- N/A
```

2020-11-09 11:07 UTC, merged