Cherry-pick to 6.8: fixes fields documentation for php_fpm metricbeat module (#22332)
elastic/beats pull request #22430
Opened 2020-11-04 16:14 UTC by EamonnTP

Backports the following commits to 6.8:
 - fixes fields documentation for php_fpm metricbeat module (#22332)

2020-11-04 16:15 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2020-11-04 16:20 UTC, bmorelli25 requested changes
This backport isn't correct. You'll need to open this up locally and run `make update` I think

2020-11-04 16:27 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22430/detail/PR-22430/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22430/detail/PR-22430/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22430/detail/PR-22430/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22430/detail/PR-22430/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_22430.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #22430 opened]`

* Start Time: 2020-11-04T16:16:54.523+0000

* Duration: 10 min 55 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22430/detail/PR-22430/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  
  
  
  
  * **Name**: `make check` (took 2 min 1 sec) . View log details on [here](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22430/runs/1/steps/149/log/?start=0)
    * Description: `make check`
  
  
  
  
  * **Name**: `Error signal` (took 0 min 0 sec) . View log details on [here](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22430/runs/1/steps/150/log/?start=0)
    * Description: `Error 'hudson.AbortException: script returned exit code 2'`
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-11-04T16:25:13.771Z] go get github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
[2020-11-04T16:25:13.771Z] # testify is needed for unit and integration tests
[2020-11-04T16:25:13.771Z] go get github.com/elastic/beats/vendor/github.com/stretchr/testify/assert
[2020-11-04T16:25:17.958Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/auditbeat'
[2020-11-04T16:25:17.958Z] make[1]: Entering directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/filebeat'
[2020-11-04T16:25:18.527Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:19.462Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:21.366Z] mkdir -p /var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/filebeat/build/coverage
[2020-11-04T16:25:21.366Z] # gotestcover is needed to fetch coverage for multiple packages
[2020-11-04T16:25:21.366Z] go get github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
[2020-11-04T16:25:21.366Z] # testify is needed for unit and integration tests
[2020-11-04T16:25:21.366Z] go get github.com/elastic/beats/vendor/github.com/stretchr/testify/assert
[2020-11-04T16:25:33.593Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/filebeat'
[2020-11-04T16:25:33.593Z] make[1]: Entering directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/heartbeat'
[2020-11-04T16:25:33.593Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:33.593Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:35.495Z] mkdir -p /var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/heartbeat/build/coverage
[2020-11-04T16:25:35.496Z] # gotestcover is needed to fetch coverage for multiple packages
[2020-11-04T16:25:35.496Z] go get github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
[2020-11-04T16:25:35.496Z] # testify is needed for unit and integration tests
[2020-11-04T16:25:35.496Z] go get github.com/elastic/beats/vendor/github.com/stretchr/testify/assert
[2020-11-04T16:25:39.692Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/heartbeat'
[2020-11-04T16:25:39.692Z] make[1]: Entering directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/journalbeat'
[2020-11-04T16:25:39.692Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:40.260Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2020-11-04T16:25:42.162Z] mkdir -p /var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/journalbeat/build/coverage
[2020-11-04T16:25:42.162Z] # gotestcover is needed to fetch coverage for multiple packages
[2020-11-04T16:25:42.162Z] go get github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
[2020-11-04T16:25:42.421Z] # testify is needed for unit and integration tests
[2020-11-04T16:25:42.421Z] go get github.com/elastic/beats/vendor/github.com/stretchr/testify/assert
[2020-11-04T16:25:44.961Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/journalbeat'
[2020-11-04T16:25:44.961Z] make[1]: Entering directory '/var/lib/jenkins/workspace/Beats_beats_PR-22430/src/github.com/elastic/beats/metricbeat'
[2020-11-04T16:25:45.899Z] DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-proc [...]

2020-11-04 19:39 UTC, dedemorton commented
@EamonnTP I can't get `make update` to work on the 6.8 branch either. I'll reach out to the dev team and see if they can help. If not, I think we just skip backporting this change to 6.8.

2020-11-11 11:13 UTC, EamonnTP commented
Discussed with @andresrc and agreed to close this PR.

2020-11-11 11:13 UTC, closed without merging