fix: align default metrics_path with the sample appplication
elastic/beats pull request #22934
Opened 2020-12-04 17:30 UTC by mdelapenya

## What does this PR do?
It aligns the configuration for dropwizard, updating the metrics_path using test appplication's web context path.

## Why is it important?
Running integrations-ci/dropwizard and a default metricbeat configured following config.yml/cconfig.reference.yml, it fails with HTTP 404 because the /metrics endpoint is not found. With this change, the configuration and the application path is aligned.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Discovered while testing elastic/e2e-testing#507

## Use cases

## Screenshots

## Logs

2020-12-04 17:34 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2020-12-04 18:34 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22934/detail/PR-22934/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22934/detail/PR-22934/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22934/detail/PR-22934/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22934/detail/PR-22934/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_22934.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `Pull request #22934 opened`

* Start Time: 2020-12-04T17:31:08.081+0000

* Duration: 63 min 57 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2291  |
| Skipped      | 505 |
| Total        | 2796   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->





### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-22934/detail/PR-22934/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `metricbeat-Lint - make -C metricbeat check;
make -C metricbeat update;
make check-no-changes;
`
<ul>
<li>Took 3 min 33 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22934/runs/1/steps/1073/log/?start=0">here</a></li>
<li>Description: <code>make -C metricbeat check;make -C metricbeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `x-pack/metricbeat-Lint - make -C x-pack/metricbeat check;
make -C x-pack/metricbeat update;
make che`
<ul>
<li>Took 2 min 58 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22934/runs/1/steps/1103/log/?start=0">here</a></li>
<li>Description: <code>make -C x-pack/metricbeat check;make -C x-pack/metricbeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-22934/runs/1/steps/1377/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-12-04T18:29:28.119Z] + git config --get user.email
[2020-12-04T18:29:28.120Z] + [ -z  ]
[2020-12-04T18:29:28.120Z] + git config --global user.email beatsmachine@users.noreply.github.com
[2020-12-04T18:29:28.120Z] + git config --global user.name beatsmachine
[2020-12-04T18:29:28.433Z] + go mod download
[2020-12-04T18:29:43.694Z] + .ci/scripts/terraform-cleanup.sh x-pack/metricbeat
[2020-12-04T18:29:43.694Z] + DIRECTORY=x-pack/metricbeat
[2020-12-04T18:29:43.694Z] + FAILED=0
[2020-12-04T18:29:43.694Z] ++ find x-pack/metricbeat -name terraform.tfstate
[2020-12-04T18:29:43.694Z] + for tfstate in $(find $DIRECTORY -name terraform.tfstate)
[2020-12-04T18:29:43.694Z] ++ dirname x-pack/metricbeat/module/aws/terraform.tfstate
[2020-12-04T18:29:43.694Z] + cd x-pack/metricbeat/module/aws
[2020-12-04T18:29:43.694Z] + terraform destroy -auto-approve
[2020-12-04T18:29:45.600Z] random_password.db: Refreshing state... [id=none]
[2020-12-04T18:29:45.600Z] random_id.suffix: Refreshing state... [id=aal1Bg]
[2020-12-04T18:29:46.993Z] aws_sqs_queue.test: Refreshing state... [id=https://sqs.********.amazonaws.com/627286350134/metricbeat-test-69a97506]
[2020-12-04T18:29:46.993Z] aws_db_instance.test: Refreshing state... [id=metricbeat-test-69a97506]
[2020-12-04T18:29:46.993Z] aws_s3_bucket.test: Refreshing state... [id=metricbeat-test-69a97506]
[2020-12-04T18:29:53.559Z] aws_s3_bucket_metric.test: Refreshing state... [id=metricbeat-test-69a97506:EntireBucket]
[2020-12-04T18:29:53.559Z] aws_s3_bucket_object.test: Refreshing state... [id=someobject]
[2020-12-04T18:29:56.859Z] aws_s3_bucket_metric.test: Destroying... [id=metricbeat-test-69a97506:EntireBucket]
[2020-12-04T18:29:56.860Z] aws_s3_bucket_object.test: Destroying... [id=someobject]
[2020-12-04T18:29:56.860Z] aws_sqs_queue.test: Destroying... [id=https://sqs.********.amazonaws.com/627286350134/metricbeat-test-69a97506]
[2020-12-04T18:29:56.860Z] aws_db_instance.test: Destroying... [id=metricbeat-test-69a97506]
[2020-12-04T18:29:57.119Z] aws_s3_bucket_object.test: Destruction complete after 1s
[2020-12-04T18:29:57.119Z] aws_s3_bucket_metric.test: Destruction complete after 1s
[2020-12-04T18:29:57.119Z] aws_s3_bucket.test: Destroying... [id=metricbeat-test-69a97506]
[2020-12-04T18:29:57.119Z] aws_sqs_queue.test: Destruction complete after 1s
[2020-12-04T18:29:57.690Z] aws_s3_bucket.test: Destruction complete after 1s
[2020-12-04T18:30:07.674Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 10s elapsed]
[2020-12-04T18:30:17.665Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 20s elapsed]
[2020-12-04T18:30:27.648Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 30s elapsed]
[2020-12-04T18:30:37.629Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 40s elapsed]
[2020-12-04T18:30:47.616Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 50s elapsed]
[2020-12-04T18:30:57.599Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m0s elapsed]
[2020-12-04T18:31:07.579Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m10s elapsed]
[2020-12-04T18:31:17.556Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m20s elapsed]
[2020-12-04T18:31:27.536Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m30s elapsed]
[2020-12-04T18:31:37.515Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m40s elapsed]
[2020-12-04T18:31:47.495Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 1m50s elapsed]
[2020-12-04T18:31:57.499Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m0s elapsed]
[2020-12-04T18:32:07.484Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m10s elapsed]
[2020-12-04T18:32:17.469Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m20s elapsed]
[2020-12-04T18:32:27.553Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m30s elapsed]
[2020-12-04T18:32:37.536Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m40s elapsed]
[2020-12-04T18:32:47.516Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 2m50s elapsed]
[2020-12-04T18:32:57.524Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 3m0s elapsed]
[2020-12-04T18:33:07.501Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 3m10s elapsed]
[2020-12-04T18:33:17.480Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 3m20s elapsed]
[2020-12-04T18:33:27.470Z] aws_db_instance.test: Still destroying... [id=metricbeat-test-69a97506, 3m30s elapsed]
[2020-12-04T18:33:37.445Z] aws_db_instance.test: Still destroying... [...]

2020-12-04 18:37 UTC, cachedout approved these changes

2020-12-07 12:56 UTC, jsoriano requested changes

2020-12-07 12:56 UTC, jsoriano commented on metricbeat/module/dropwizard/_meta/config.reference.yml
> +  metrics_path: /test/metrics
This is the reference configuration used in documentation, I would prefer not to show a "`test`" path here.

I see two alternatives:
* Look for another way of overriding this `metrics_path` in the integrations CI.
* Modify the path in the Dockerfile from `test` to `metrics` so this config works. Not sure if this path depends on the [name of the war](https://github.com/elastic/beats/blob/1edb43e594c80a18c061b04bccf54c4f972ff32b/metricbeat/module/dropwizard/_meta/Dockerfile#L13), or on the [artifact id](https://github.com/elastic/beats/blob/1edb43e594c80a18c061b04bccf54c4f972ff32b/metricbeat/module/dropwizard/_meta/test/pom.xml#L6). If this is changed, the config used by go and python tests would need to be updated.

2022-03-31 17:18 UTC, closed without merging