Rename s3 input to aws-s3 input
elastic/beats pull request #23469
Opened 2021-01-12 23:43 UTC by kaiyan-sheng

## What does this PR do?

This PR is to rename Filebeat `s3` input to `aws-s3` input.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

2021-01-12 23:43 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Platforms)

2021-01-12 23:53 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23469/detail/PR-23469/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23469/detail/PR-23469/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23469/detail/PR-23469/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23469/detail/PR-23469/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `Pull request #23469 opened`

* Reason: `Aborted from #2`

* Start Time: 2021-01-12T23:43:52.365+0000

* Duration: 9 min 57 sec


* Commit: 2861eb2b22b8c39c094484b4c315ed1ae292b65c




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->





### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23469/detail/PR-23469/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Check for changes`
<ul>
<li>Took 0 min 3 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-23469/runs/1/steps/168/log/?start=0">here</a></li>
<li>Description: <code>make check-no-changes</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-23469/runs/1/steps/169/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-01-12T23:51:14.124Z]   HOME: /var/lib/jenkins/workspace/Beats_beats_PR-23469
[2021-01-12T23:51:14.124Z]   NOSETESTS_OPTIONS: null
[2021-01-12T23:51:14.124Z]   NOW: null
[2021-01-12T23:51:14.124Z]   PATH: /var/lib/jenkins/workspace/Beats_beats_PR-23469/bin:/var/lib/jenkins/workspace/Beats_beats_PR-23469/.gvm/versions/go1.14.12.linux.amd64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[2021-01-12T23:51:14.124Z]   PKG_BUILD_DIR: null
[2021-01-12T23:51:14.124Z]   PKG_UPLOAD_DIR: null
[2021-01-12T23:51:14.124Z]   PIP_INSTALL_PARAMS: null
[2021-01-12T23:51:14.124Z]   PROJECTS: null
[2021-01-12T23:51:14.124Z]   PROJECTS_ENV: null
[2021-01-12T23:51:14.124Z]   PYTHON_ENV: /var/lib/jenkins/workspace/Beats_beats_PR-23469/python-env
[2021-01-12T23:51:14.124Z]   PYTHON_ENV_EXE: null
[2021-01-12T23:51:14.124Z]   PYTHON_EXE: null
[2021-01-12T23:51:14.124Z]   PYTHON_TEST_FILES: null
[2021-01-12T23:51:14.124Z]   PROCESSES: null
[2021-01-12T23:51:14.124Z]   REVIEWDOG: null
[2021-01-12T23:51:14.124Z]   REVIEWDOG_OPTIONS: null
[2021-01-12T23:51:14.124Z]   REVIEWDOG_REPO: null
[2021-01-12T23:51:14.124Z]   STRESS_TESTS: null
[2021-01-12T23:51:14.124Z]   STRESS_TEST_OPTIONS: null
[2021-01-12T23:51:14.124Z]   SYSTEM_TESTS: null
[2021-01-12T23:51:14.124Z]   TESTIFY_TOOL_REPO: null
[2021-01-12T23:51:14.124Z]   TEST_ENVIRONMENT: null
[2021-01-12T23:51:14.124Z]   TEST_TAGS: null,oracle
[2021-01-12T23:51:14.124Z]   TESTING_ENVIRONMENT: null
[2021-01-12T23:51:14.124Z]   TIMEOUT: null
[2021-01-12T23:51:14.124Z]   USERPROFILE: null
[2021-01-12T23:51:14.124Z]   VENV_PARAMS: null
[2021-01-12T23:51:14.124Z]   XPACK_SUFFIX: null
[2021-01-12T23:51:14.124Z]   ### END ENV DUMP ###
[2021-01-12T23:51:14.124Z]   
[2021-01-12T23:51:14.415Z] + make get-version
[2021-01-12T23:51:15.688Z] + make check-python
[2021-01-12T23:52:37.500Z] + make check-go
[2021-01-12T23:52:38.372Z] + make check-no-changes
[2021-01-12T23:52:39.746Z] diff --git a/go.sum b/go.sum
[2021-01-12T23:52:39.746Z] index a4dbe5c331..6ff61bcfea 100644
[2021-01-12T23:52:39.746Z] --- a/go.sum
[2021-01-12T23:52:39.746Z] +++ b/go.sum
[2021-01-12T23:52:39.746Z] @@ -246,8 +246,6 @@ github.com/eapache/queue v1.1.0 h1:YOEu7KNc61ntiQlcEeUIoDTJ2o8mQznoNvUhiigpIqc=
[2021-01-12T23:52:39.746Z]  github.com/eapache/queue v1.1.0/go.mod h1:6eCeP0CKFpHLu8blIFXhExK/dRa7WDZfr6jVFPTqq+I=
[2021-01-12T23:52:39.746Z]  github.com/eclipse/paho.mqtt.golang v1.2.1-0.20200121105743-0d940dd29fd2 h1:DW6WrARxK5J+o8uAKCiACi5wy9EK1UzrsCpGBPsKHAA=
[2021-01-12T23:52:39.746Z]  github.com/eclipse/paho.mqtt.golang v1.2.1-0.20200121105743-0d940dd29fd2/go.mod h1:H9keYFcgq3Qr5OUJm/JZI/i6U7joQ8SYLhZwfeOo6Ts=
[2021-01-12T23:52:39.746Z] -github.com/elastic/beats v1.3.1 h1:hHzUBHCo3HJHxnRVwa0XlfZoxmP8Rxp7GQ0ZVELGY4A=
[2021-01-12T23:52:39.746Z] -github.com/elastic/beats v6.8.13+incompatible h1:0aANw37fP0uaNJ+TRGWyrVgTp2okWV+m/2xjTRxSXhI=
[2021-01-12T23:52:39.746Z]  github.com/elastic/dhcp v0.0.0-20200227161230-57ec251c7eb3 h1:lnDkqiRFKm0rxdljqrj3lotWinO9+jFmeDXIC4gvIQs=
[2021-01-12T23:52:39.746Z]  github.com/elastic/dhcp v0.0.0-20200227161230-57ec251c7eb3/go.mod h1:aPqzac6AYkipvp4hufTyMj5PDIphF3+At8zr7r51xjY=
[2021-01-12T23:52:39.746Z]  github.com/elastic/ecs v1.6.0 h1:8NmgfnsjmKXh9hVsK3H2tZtfUptepNc3msJOAynhtmc=
[2021-01-12T23:52:40.679Z] go.sum: needs update
[2021-01-12T23:52:40.679Z] Makefile:116: recipe for target 'check-no-changes' failed
[2021-01-12T23:52:40.679Z] make: *** [check-no-changes] Error 1
[2021-01-12T23:52:41.044Z] Client: Docker Engine - Community
[2021-01-12T23:52:41.044Z]  Version:           20.10.2
[2021-01-12T23:52:41.044Z]  API version:       1.41
[2021-01-12T23:52:41.044Z]  Go version:        go1.13.15
[2021-01-12T23:52:41.044Z]  Git commit:        2291f61
[2021-01-12T23:52:41.044Z]  Built:             Mon Dec 28 16:17:32 2020
[2021-01-12T23:52:41.045Z]  OS/Arch:           linux/amd64
[2021-01-12T23:52:41.045Z]  Context:           default
[2021-01-12T23:52:41.045Z]  Experimental:      true
[2021-01-12T23:52:41.045Z] 
[2021-01-12T23:52:41.045Z] Server: Docker Engine - Community
[2021-01-12T23:52:41.045Z]  Engine:
[2021-01-12T23:52:41.045Z]   Version:          20.10.2
[2021-01-12T23:52:41.045Z]   API version:      1.41 (minimum version 1.12)
[2021-01-12T23:52:41.045Z]   Go version:       go1.13.15
[2021-01-12T23:52:41.045Z]   Git commit:       8891c58
[2021-01-12T23:52:41.045Z]   Built:            Mon Dec 28 16:15:09 2020
[2021-01-12T23:52:41.045Z]   OS/Arch:          linux/amd64
[2021-01-12T23:52:41.045Z]   Experimental:     false
[2021-01-12T23:52:41.045Z]  containerd:
[2021-01-12T23:52:41.045Z]   Version:          1.4.3
[2021-01-12T23:52:41.045Z]   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
[2021-01-12T23:52:41.045Z]  runc:
[2021-01-12T23:52:41.045Z]   Version:          1.0.0-rc92
[2021-01-12T23:52:41.045Z]   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
[2021-01-12T23:52:41.045Z]  docker-init:
[2021-01-12T23:52:41.045Z]   Version:          0.19.0
[2021-01-12T23:52:41.045Z]   GitCommit:        de40ad0
[2021-01-12T23:52:41.045Z] Unable to find image 'alpine:3.4' locally
[2021-01-12T23:52:41.979Z] 3.4: Pulling from library/alpine
[2021-01-12T23:52:42.238Z] c1e54eec4b57: Pulling fs layer
[2021-01-12T23:52:42.496Z] c1e54eec4b57: Verifying Checksum
[2021-01-12T23:52:42.496Z] c1e54eec4b57: Download complete
[2021-01-12T23:52:42.496Z] c1e54eec4b57: Pull complete
[2021-01-12T23:52:42.754Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
[2021-01-12T23:52:42.754Z] Status: Downloaded newer image for alpine:3.4
[2021-01-12T23:52:47.754Z] Stage "Build&T [...]

2021-01-13 20:27 UTC, elasticmachine commented
Pinging @elastic/ingest-management (Team:Ingest Management)

2021-01-13 23:19 UTC, bmorelli25 commented
For the doc build, change this line:

https://github.com/elastic/beats/blame/18fb50493f6cd60eed1661caa3c4939de59db20e/filebeat/docs/filebeat-options.asciidoc#L79

It should be:

```
* <<{beatname_lc}-input-aws-s3>>
```

When I make this change the PR builds locally 🎉

2021-01-14 04:06 UTC, bmorelli25 commented on filebeat/docs/filebeat-options.asciidoc
> +* <<{beatname_lc}-input-aws-s3>>
Nice catch on the alphabetizing!

2021-01-14 14:18 UTC, kaiyan-sheng commented on filebeat/docs/filebeat-options.asciidoc
> +* <<{beatname_lc}-input-aws-s3>>
Ha thank you for your help!!

2021-01-15 03:18 UTC, leehinman requested changes
I think `filebeat/docs/aws-credentials-examples.asciidoc` and `x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl` need updating too.

otherwise looks great.

2021-01-15 20:08 UTC, kaiyan-sheng commented
@leehinman Good catch! It's fixed now, thank you!

2021-01-15 20:14 UTC, leehinman approved these changes

2021-01-19 17:05 UTC, merged