Add syntax for multiple selector logging
elastic/beats pull request #24207
Opened 2021-02-24 12:54 UTC by AndyHunt66

Add syntax for multiple selector logging

2021-02-24 12:55 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2021-02-24 13:15 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24207/detail/PR-24207/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24207/detail/PR-24207/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24207/detail/PR-24207/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24207/detail/PR-24207/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_24207.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #24207 opened`



* Start Time: 2021-02-24T12:54:41.989+0000


* Duration: 20 min 30 sec


* Commit: 1758d1aef616ae22859cf0fdeb79d558b40d5b17




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24207/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :grey_exclamation: Flaky test report
No test was executed to be analysed.



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-02-25 17:25 UTC, andresrc commented
@kvch @urso is the syntax correct?

2021-03-01 22:44 UTC, urso commented
Yes, but selectors is just an array. YAML arrays can be written using `[]` or `-` e.g.

```
logging.selectors: [a, b]
```

vs

```
logging.selectors:
- a
- b
```

2021-03-10 11:50 UTC, urso commented
> Should this update include both the YAML array formats you have listed above?

Not necessarily. But instead of we mention "following syntax", maybe we want to say "YAML list syntax" and link to our configuration file format docs.

2021-03-10 14:52 UTC, EamonnTP commented on libbeat/docs/loggingconfig.asciidoc
> +To configure multiple selectors, use the following syntax:
```suggestion
To configure multiple selectors, use the following {beats-ref}/config-file-format.html[YAML list syntax]:
```

2021-03-10 14:54 UTC, EamonnTP requested changes
@AndyHunt66 Thanks for the update! Just a minor suggestion.

2021-03-10 16:23 UTC, EamonnTP approved these changes

2021-03-10 17:00 UTC, bmorelli25 approved these changes

2021-03-11 09:23 UTC, merged