test
elastic/beats pull request #24230
Opened 2021-02-25 09:13 UTC by michalpristas

## What does this PR do?

This PR fixes issue with incorrect time format when logging. 
While this seems as simple change i would like to get opinions on unwanted consequences
our events change format of timestamp from
`2021-02-11T13:00:19.011-0700` to
`2021-02-11T13:00:19.011-07:00` 

While I haven't seen this format being required anywhere in the logs  I want to make sure I'm not breaking things here.

## Why is it important?

Fixes: #24229 24229

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2021-02-25 09:13 UTC, elasticmachine commented
Pinging @elastic/agent (Team:Agent)

2021-02-25 09:13 UTC, elasticmachine commented
Pinging @elastic/ingest-management (Team:Ingest Management)

2021-02-25 10:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24230/detail/PR-24230/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24230/detail/PR-24230/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24230/detail/PR-24230/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24230/detail/PR-24230/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_24230.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #24230 opened`



* Start Time: 2021-02-25T09:14:26.642+0000


* Duration: 67 min 18 sec


* Commit: 9c157e0459504eedad0487b90a678991603abde5



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 46724  |
| Skipped      | 4939 |
| Total        | 51663   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24230/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24230/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 46724  |
| Skipped      | 4939 |
| Total        | 51663   |



</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-02-25 11:19 UTC, michalpristas commented
/package

2021-03-08 10:00 UTC, ruflin commented
From a logs collector perspective, I assume this could be considered a breaking change as the log format changes? What are the alternatives to change the log format?

@urso Any thoughts here?

2021-03-09 19:14 UTC, ph commented
@michalpristas have you tried using the  _timestamp_ processor with the appropriate layout? This would not cause any breaking changes.

https://www.elastic.co/guide/en/beats/filebeat/current/processor-timestamp.html

2021-03-09 20:05 UTC, urso commented
We have a 'fixed' layout for timestamps we report to ES, and for logs the JSON input accepts. If the format does not match the contents in `@timestamp` might even get lost. If the logs produced by Beats can not be parsed correctly by the JSON support in the filebeat logs input I would consider this a bug.

2021-03-10 07:56 UTC, michalpristas commented
@urso this was also my second thought, make parser accept both formats. will rewrite in this way. 
thanks for input

2021-03-15 14:05 UTC, urso requested changes

2021-03-15 14:05 UTC, urso commented on libbeat/common/jsontransform/jsonhelper.go
> +			err = multierror.Append(err, parseErr)
1. It looks like the error is never returned.
2. Maybe we should create our own error message if parsing fails instead of returning a collection.

2021-03-15 14:05 UTC, urso commented on libbeat/common/jsontransform/jsonhelper.go
> +	return time.Now(), nil
returning `time.Now()` might be a semantic/breaking change for some users. The `@timestamp` was already set and would have been kept if the parse failed. Returning `time.Now()` here means that we will now overwrite existing timestamps no matter what.

2021-03-23 20:17 UTC, urso approved these changes

2021-03-25 15:01 UTC, merged