[Filebeat] Add Proxy config to httpjson v2
elastic/beats pull request #24662
Opened 2021-03-21 19:32 UTC by legoguy1000

## What does this PR do?

Adds a `proxy_url` config option to the httpjson v2 input.  Potentially resolves 24615.

## Why is it important?

No way to specify a proxy to use for the httpjson v2 input.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

## How to test this PR locally

## Related issues

Relates #24615

## Use cases

## Screenshots

## Logs

2021-03-21 19:37 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24662/detail/PR-24662/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24662/detail/PR-24662/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24662/detail/PR-24662/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24662/detail/PR-24662/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #24662 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-03-21T19:32:42.908+0000


* Duration: 5 min 46 sec


* Commit: 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24662/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24662/detail/PR-24662/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-24662/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/beats.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-24662/runs/1/steps/84/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-03-21T19:35:29.367Z]  > git checkout -f 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc # timeout=15
[2021-03-21T19:35:30.900Z]  > git remote # timeout=10
[2021-03-21T19:35:30.905Z]  > git config --get remote.origin.url # timeout=10
[2021-03-21T19:35:30.908Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-21T19:35:30.912Z]  > git merge b4dce824818eaff45d519dac024b1e200faf7515 # timeout=10
[2021-03-21T19:35:30.923Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-03-21T19:35:30.932Z]  > git config core.sparsecheckout # timeout=10
[2021-03-21T19:35:30.936Z]  > git checkout -f 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc # timeout=15
[2021-03-21T19:35:35.828Z] Commit message: "Add Proxy config to httpjson v2"
[2021-03-21T19:35:35.829Z] First time build. Skipping changelog.
[2021-03-21T19:35:35.829Z] Cleaning workspace
[2021-03-21T19:35:35.995Z]  > git --version # timeout=10
[2021-03-21T19:35:36.002Z]  > git --version # 'git version 2.17.1'
[2021-03-21T19:35:36.006Z] fatal: bad object 4f845c65634cd6e489a51cb99c12fd2674a3ab0e
[2021-03-21T19:35:35.829Z]  > git rev-parse --verify HEAD # timeout=10
[2021-03-21T19:35:35.839Z] Resetting working tree
[2021-03-21T19:35:35.839Z]  > git reset --hard # timeout=10
[2021-03-21T19:35:35.919Z]  > git clean -fdx # timeout=10
[2021-03-21T19:35:36.941Z] Timeout set to expire in 3 hr 0 min
[2021-03-21T19:35:36.976Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-03-21T19:35:37.308Z] [INFO] Number of builds to be searched 10
[2021-03-21T19:35:38.168Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-03-21T19:35:38.200Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-24662/src/github.com/elastic/beats
[2021-03-21T19:35:38.257Z] [INFO] gitCheckout: Checkout SCM PR-24662 with default customisation from the Item.
[2021-03-21T19:35:38.308Z] [INFO] Override default checkout
[2021-03-21T19:35:38.394Z] Sleeping for 10 sec
[2021-03-21T19:35:48.442Z] The recommended git tool is: git
[2021-03-21T19:35:48.505Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-03-21T19:35:48.578Z] Wiping out workspace first.
[2021-03-21T19:35:48.588Z] Cloning the remote Git repository
[2021-03-21T19:35:48.588Z] Using shallow clone with depth 10
[2021-03-21T19:35:48.588Z] Avoid fetching tags
[2021-03-21T19:35:48.601Z] Cloning repository git@github.com:elastic/beats.git
[2021-03-21T19:35:48.630Z]  > git init /var/lib/jenkins/workspace/Beats_beats_PR-24662/src/github.com/elastic/beats # timeout=10
[2021-03-21T19:35:48.635Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-03-21T19:35:48.636Z]  > git --version # timeout=10
[2021-03-21T19:35:48.639Z]  > git --version # 'git version 2.17.1'
[2021-03-21T19:35:48.640Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-21T19:35:48.643Z]  > git fetch --no-tags --progress -- git@github.com:elastic/beats.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-03-21T19:36:07.995Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-03-21T19:36:08.013Z] Cleaning workspace
[2021-03-21T19:36:08.027Z] Using shallow fetch with depth 10
[2021-03-21T19:36:08.028Z] Pruning obsolete local branches
[2021-03-21T19:36:09.060Z] Merging remotes/origin/master commit b4dce824818eaff45d519dac024b1e200faf7515 into PR head commit 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc
[2021-03-21T19:36:07.999Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-03-21T19:36:08.007Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-03-21T19:36:08.014Z]  > git rev-parse --verify HEAD # timeout=10
[2021-03-21T19:36:08.018Z] No valid HEAD. Skipping the resetting
[2021-03-21T19:36:08.018Z]  > git clean -fdx # timeout=10
[2021-03-21T19:36:08.029Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-03-21T19:36:08.029Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-21T19:36:08.033Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/24662/head:refs/remotes/origin/PR-24662 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-03-21T19:36:09.061Z]  > git config core.sparsecheckout # timeout=10
[2021-03-21T19:36:09.064Z]  > git checkout -f 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc # timeout=15
[2021-03-21T19:36:10.588Z] Merge succeeded, producing 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc
[2021-03-21T19:36:10.588Z] Checking out Revision 83c95b18a6dede7022f2ca8a8d1f9e7029ad9fdc (PR-24662)
[2021-03-21T19:36:11.475Z] Commit message: "Add Proxy config to httpjson v2"
[2021-03-21T19:36:11.475Z] Cleaning workspace
[2021-03-21T19:36:11.633Z]  > git --version # timeout=10
[2021-03-21T19:36:11.637Z]  > git --version # 'git version 2.17.1'
[2021-03-21T19:36:11.641Z] fatal: bad object 4f845c65634cd6e489a51cb99c12fd2674a3ab0e
[2021-03-21T19:36:10.561Z]  > git remote # timeout=10
[2021-03-21T19:36:10.565Z]  > git config --get remote.origin.url # timeout=10
[2021-03-21T19:36:10.568Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-03-21T19:36:10.571Z]  > git merge b4dce824818eaff45d519dac024b1e200faf7515 # timeout=10
[2021-03-21T19:36:10.582Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-03-21T19:36:10.590Z]  > git co [...]

2021-03-22 15:26 UTC, marc-gr requested changes
Thanks for the PR! On top of the suggested changes, an entry in the `CHANGELOG.next.asciidoc` is required, under the Bugfixes -> Filebeat section.

Let us know if you need any help to move forward.

2021-03-22 15:26 UTC, marc-gr commented on x-pack/filebeat/input/httpjson/internal/v2/config_request.go
> +	ProxyURL               string            `config:"proxy_url"`
```suggestion
	ProxyURL               *urlConfig            `config:"proxy_url"`
```

If you change to the `urlConfig` type, if will handle the validation and parsing of the url automatically.

2021-03-22 15:26 UTC, marc-gr commented on x-pack/filebeat/input/httpjson/internal/v2/config_request.go
> +func (c requestConfig) getProxyUrl() string {
I think we do not need this function, just checking the value of the field should be enough I think.

2021-03-22 15:26 UTC, marc-gr commented on x-pack/filebeat/module/okta/system/config/input.yml
> +{{ if .ssl }}
```suggestion
{{ if .proxy_url }}
```

2021-03-22 15:42 UTC, legoguy1000 commented on x-pack/filebeat/module/okta/system/config/input.yml
> +{{ if .ssl }}
done

2021-03-22 15:44 UTC, legoguy1000 commented
Should I add the `proxy_url` config option to all the other modules using the httpjsn v2 input?? I didn't want to right away until i got a thumbs up on the Golang code.

2021-03-23 02:38 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-03-23 03:16 UTC, andrewkroh approved these changes
Awesome, LGTM. Thanks!

~@marc-gr Can you check this too please.~

2021-03-23 03:16 UTC, andrewkroh commented
jenkins, test this

2021-03-24 15:38 UTC, marc-gr requested changes
Thanks for addressing the changes! It LGTM except for the changelog line, LMK if you need any help with that 👍

2021-03-24 15:38 UTC, marc-gr commented on CHANGELOG.next.asciidoc
> +- Add `proxy_url` config for httpjson vs input. {issue}24615[24615] {pull}24662[24662]
This is under the Bugfixes section, could you please move it under the `Added` one?

2021-03-24 15:49 UTC, andrewkroh commented
run tests

2021-03-24 16:26 UTC, marc-gr approved these changes

2021-03-24 17:02 UTC, andrewkroh commented
jenkins, run tests

2021-03-24 17:38 UTC, andrewkroh commented
run tests

2021-03-24 18:50 UTC, merged