Enable HMAC Signature Validation for http_endpoint input
elastic/beats pull request #24918
Opened 2021-04-02 21:24 UTC by SpencerLN

## What does this PR do?

Adds the option of HMAC signature validation for the `http_endpoint` input. This PR adds support for `sha1` and `sha256` based HMAC validation and allows flexible configuration of the header containing the signature, the key, and an optional prefix.
## Why is it important?
Many webhook senders offer this as the only method of authenticating that the method was actually sent from them, for example, GitHub and Dropbox. This enables future modules to receive events from these types of senders and allows users the flexibility to configure their own inputs in the meantime. 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

This PR can be tested locally by configuring a webhook sender to send events to your machine. I personally used ngrok to expose the appropriate port from Filebeat, but there are other options. One simple sender to use for testing is configuring a webhook on any GitHub repo. 

https://docs.github.com/en/developers/webhooks-and-events/creating-webhooks#exposing-localhost-to-the-internet

## Related issues

- Closes #24917

2021-04-02 22:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24918/detail/PR-24918/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24918/detail/PR-24918/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24918/detail/PR-24918/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-24918/detail/PR-24918/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_24918.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #24918 opened`



* Start Time: 2021-04-02T21:25:39.241+0000


* Duration: 54 min 35 sec


* Commit: f0c826fda3643af81e8d50e85958d424ab26f63d



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6883  |
| Skipped      | 1185 |
| Total        | 8068   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24918/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-24918/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 6883  |
| Skipped      | 1185 |
| Total        | 8068   |



</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-04-07 16:40 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-05-03 14:50 UTC, andrewkroh commented on x-pack/filebeat/input/http_endpoint/config.go
> +	HmacHeader    string                  `config:"hmac.header"`
For Go conventions this would be `HMACHeader`

2021-05-10 08:07 UTC, P1llus reviewed
It does LGTM, have you tested this for example with Github @SpencerLN ?

It looks better than my older implementation here: https://github.com/elastic/beats/pull/20744/files

2021-05-10 14:07 UTC, SpencerLN commented
> It does LGTM, have you tested this for example with Github @SpencerLN ?
> 
> It looks better than my older implementation here: https://github.com/elastic/beats/pull/20744/files

@P1llus I wrote this with GitHub in mind and that was what I did my primary testing with.

The conflict for the changelog should be resolved now; is there anything else I should take care of? I wasn't sure if I needed to add different labels for Mergify to work.

2021-05-10 14:51 UTC, P1llus commented
> > It does LGTM, have you tested this for example with Github @SpencerLN ?
> > It looks better than my older implementation here: https://github.com/elastic/beats/pull/20744/files
> 
> @P1llus I wrote this with GitHub in mind and that was what I did my primary testing with.
> 
> The conflict for the changelog should be resolved now; is there anything else I should take care of? I wasn't sure if I needed to add different labels for Mergify to work.

Just need to confirm a few things with @andrewkroh in terms of how the response body is read, and if we can still get this to work if we wanted to read the body further in the future (like body validation logic, middleware etc), (should be okay because of the NopCloser).

After that we can add the labels for you.

2021-05-12 23:01 UTC, andrewkroh requested changes
Thank you for including tests with this change.

2021-05-12 23:01 UTC, andrewkroh commented on x-pack/filebeat/input/http_endpoint/validate.go
> +			hmacHeaderValue = strings.Replace(hmacHeaderValue, v.hmacPrefix, "", 1)
There's a `strings.TrimPrefix`.

2021-05-12 23:01 UTC, andrewkroh commented on x-pack/filebeat/input/http_endpoint/validate.go
> +		signature, _ := hex.DecodeString(hmacHeaderValue)
This should return an error.

2021-05-12 23:01 UTC, andrewkroh commented on x-pack/filebeat/input/http_endpoint/validate.go
> +		buf, _ := ioutil.ReadAll(r.Body)
This should return an error.

2021-05-12 23:11 UTC, andrewkroh approved these changes
I pushed an update to address the comments I made. 

I also changed error messages that were [capitalized](https://github.com/golang/go/wiki/CodeReviewComments#error-strings) as an unrelated cleanup.

2021-05-13 11:25 UTC, merged