Update monitor-common-options.asciidoc
elastic/beats pull request #25052
Opened 2021-04-13 21:20 UTC by leahleahy

Copy edits and changes

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-04-13 21:25 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25052/detail/PR-25052/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25052/detail/PR-25052/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25052/detail/PR-25052/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25052/detail/PR-25052/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #25052 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-04-13T21:21:30.184+0000


* Duration: 4 min 46 sec


* Commit: 737d1d034d30f572e44cb007b7c73bb00be987c0




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25052/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25052/detail/PR-25052/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25052/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/beats.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25052/runs/1/steps/84/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-13T21:23:14.552Z]  > git checkout -f 737d1d034d30f572e44cb007b7c73bb00be987c0 # timeout=15
[2021-04-13T21:23:16.158Z]  > git remote # timeout=10
[2021-04-13T21:23:16.163Z]  > git config --get remote.origin.url # timeout=10
[2021-04-13T21:23:16.167Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:23:16.171Z]  > git merge e8afb8db469285608ee75d2f949fe5175cad2f68 # timeout=10
[2021-04-13T21:23:16.182Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-04-13T21:23:16.193Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:23:16.197Z]  > git checkout -f 737d1d034d30f572e44cb007b7c73bb00be987c0 # timeout=15
[2021-04-13T21:23:20.016Z] Commit message: "Update monitor-common-options.asciidoc"
[2021-04-13T21:23:20.017Z] First time build. Skipping changelog.
[2021-04-13T21:23:20.017Z] Cleaning workspace
[2021-04-13T21:23:20.341Z]  > git --version # timeout=10
[2021-04-13T21:23:20.345Z]  > git --version # 'git version 2.17.1'
[2021-04-13T21:23:20.349Z] fatal: bad object 5b62f622bb6e4e750b63eba4064d4de53db6f5e3
[2021-04-13T21:23:21.188Z] Timeout set to expire in 3 hr 0 min
[2021-04-13T21:23:21.221Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-04-13T21:23:21.473Z] [INFO] Number of builds to be searched 10
[2021-04-13T21:23:20.020Z]  > git rev-parse --verify HEAD # timeout=10
[2021-04-13T21:23:20.024Z] Resetting working tree
[2021-04-13T21:23:20.024Z]  > git reset --hard # timeout=10
[2021-04-13T21:23:20.258Z]  > git clean -fdx # timeout=10
[2021-04-13T21:23:22.130Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-04-13T21:23:22.163Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25052/src/github.com/elastic/beats
[2021-04-13T21:23:22.212Z] [INFO] gitCheckout: Checkout SCM PR-25052 with default customisation from the Item.
[2021-04-13T21:23:22.260Z] [INFO] Override default checkout
[2021-04-13T21:23:22.340Z] Sleeping for 10 sec
[2021-04-13T21:23:32.375Z] The recommended git tool is: git
[2021-04-13T21:23:32.455Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-04-13T21:23:32.510Z] Wiping out workspace first.
[2021-04-13T21:23:32.521Z] Cloning the remote Git repository
[2021-04-13T21:23:32.521Z] Using shallow clone with depth 10
[2021-04-13T21:23:32.521Z] Avoid fetching tags
[2021-04-13T21:23:32.541Z] Cloning repository git@github.com:elastic/beats.git
[2021-04-13T21:23:32.571Z]  > git init /var/lib/jenkins/workspace/Beats_beats_PR-25052/src/github.com/elastic/beats # timeout=10
[2021-04-13T21:23:32.577Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-04-13T21:23:32.577Z]  > git --version # timeout=10
[2021-04-13T21:23:32.581Z]  > git --version # 'git version 2.17.1'
[2021-04-13T21:23:32.582Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:23:32.586Z]  > git fetch --no-tags --progress -- git@github.com:elastic/beats.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-04-13T21:23:53.938Z] Cleaning workspace
[2021-04-13T21:23:53.952Z] Using shallow fetch with depth 10
[2021-04-13T21:23:53.952Z] Pruning obsolete local branches
[2021-04-13T21:23:55.250Z] Merging remotes/origin/master commit e8afb8db469285608ee75d2f949fe5175cad2f68 into PR head commit 737d1d034d30f572e44cb007b7c73bb00be987c0
[2021-04-13T21:23:53.922Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-04-13T21:23:53.925Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-04-13T21:23:53.934Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-04-13T21:23:53.941Z]  > git rev-parse --verify HEAD # timeout=10
[2021-04-13T21:23:53.944Z] No valid HEAD. Skipping the resetting
[2021-04-13T21:23:53.944Z]  > git clean -fdx # timeout=10
[2021-04-13T21:23:53.955Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-04-13T21:23:53.955Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:23:53.958Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/25052/head:refs/remotes/origin/PR-25052 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-04-13T21:23:55.252Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:23:55.255Z]  > git checkout -f 737d1d034d30f572e44cb007b7c73bb00be987c0 # timeout=15
[2021-04-13T21:23:56.831Z] Merge succeeded, producing 737d1d034d30f572e44cb007b7c73bb00be987c0
[2021-04-13T21:23:56.831Z] Checking out Revision 737d1d034d30f572e44cb007b7c73bb00be987c0 (PR-25052)
[2021-04-13T21:23:58.076Z] Commit message: "Update monitor-common-options.asciidoc"
[2021-04-13T21:23:58.076Z] Cleaning workspace
[2021-04-13T21:23:56.804Z]  > git remote # timeout=10
[2021-04-13T21:23:56.808Z]  > git config --get remote.origin.url # timeout=10
[2021-04-13T21:23:56.812Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:23:56.816Z]  > git merge e8afb8db469285608ee75d2f949fe5175cad2f68 # timeout=10
[2021-04-13T21:23:56.826Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-04-13T21:23:56.834Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:23:56.837Z]  > git checkout -f 737d1d034d30f572e44cb007b7c73bb00be987c0 # timeout=15
[2021-04-13T21:23:58.078Z]  > git rev-parse --verify HEAD  [...]

2021-04-13 21:25 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2021-04-13 21:27 UTC, bmorelli25 commented
jenkins, run the tests please

2021-04-13 21:28 UTC, bmorelli25 commented
@elasticmachine, run elasticsearch-ci/docs

2021-04-14 21:18 UTC, dedemorton requested changes
Thanks! Here are some more comments. I hope this is an active PR (can't remember which one was a duplicate).

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +regardless of changes to any config fields. Examples: `uploader-service`, `http://example.net`, `us-west-loadbalancer`. An ID is unique within a given beat instance. If you want to monitor the same e
Shorten this sentence and avoid the "it is recommended" structure: "If you want to monitor the same endpoint from multiple locations, it is recommended that those heartbeat instances..."

Also, capitalize Heartbeat.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +This field is used to aggregate with when querying against indexed monitor data. It appears in the
Not a fan of the passive voice here. Be more direct: Use this field to....

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +If you do not set this explicitly, the monitor's config will be hashed and a generated value will be used. This value will
This sentence isn't clear. I'd also avoid future tense when possible.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +Optional readable name for this monitor by an individual. This value appears in the <<exported-fields,exported fields>>
human readable is a common, industry standard term. Please revert this edit.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +For stats on the execution of scheduled tasks, enable the HTTP stats server with `http.enabled: true` in heartbeat.yml. Then, run `curl http://localhost:5066/stats | jq .heartbeat.scheduler` to view
We typically wrap filenames and paths in back ticks.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +For stats on the execution of scheduled tasks, enable the HTTP stats server with `http.enabled: true` in heartbeat.yml. Then, run `curl http://localhost:5066/stats | jq .heartbeat.scheduler` to view
"Each time a monitor is scheduled, it is considered to be a single job" is wordy. Needs an edit.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +For stats on the execution of scheduled tasks, enable the HTTP stats server with `http.enabled: true` in heartbeat.yml. Then, run `curl http://localhost:5066/stats | jq .heartbeat.scheduler` to view
Also, "DNS lookups and executing network requests are defined as tasks" is a bit jumbled. In the original, these were used as examples to help users map their understanding of monitors to the stats that are collected. Maybe rewrite with that in mind?

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +* **jobs.missed_deadline:** The number of jobs that are executed after their scheduled time. This can be caused either by overlong long timeouts from the previous job or high load preventing heartbea
I think you want "that have executed" here. Otherwise, you are changing the meaning slightly.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +Also, see the <<monitors-scheduler,task scheduler>> settings.
```suggestion
Also see the <<monitors-scheduler,task scheduler>> settings.
```

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +Also, see the <<monitors-scheduler,task scheduler>> settings.
comma is extraneous here.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +These are optional fields that can be used to add additional information to the
I don't like "that you can specify, " but changing to passive here is not the best fix. The sentence needs to be rewritten.

2021-04-14 21:18 UTC, dedemorton commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +combination of these. By default, the fields that are specified here will be
same comment

2021-04-20 19:30 UTC, bmorelli25 commented on heartbeat/docs/monitors/monitor-common-options.asciidoc
> +These options are the same for all monitors, while each monitor type will have additional configurations specific to each type.
```suggestion
These options are the same for all monitors, while each monitor type will have additional configurations specific to it.
```

2021-04-21 21:28 UTC, bmorelli25 commented
@elasticmachine, run elasticsearch-ci/docs

2021-04-21 21:28 UTC, bmorelli25 commented
Jenkins, run the tests please

2021-04-23 18:14 UTC, dedemorton commented
I'm closing this PR because there are too many edits that inadvertently change meaning and introduce mistakes.

2021-04-23 18:14 UTC, closed without merging