Update add_kubernetes_metadata.asciidoc
elastic/beats pull request #25054
Opened 2021-04-13 21:47 UTC by leahleahy

2021-04-13 21:52 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25054/detail/PR-25054/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25054/detail/PR-25054/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25054/detail/PR-25054/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25054/detail/PR-25054/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #25054 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-04-13T21:48:26.199+0000


* Duration: 4 min 12 sec


* Commit: f4cb0590685cc2373534e9a02e4902aa1a63528f




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25054/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25054/detail/PR-25054/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25054/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/beats.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25054/runs/1/steps/84/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-13T21:50:38.656Z]  > git remote # timeout=10
[2021-04-13T21:50:38.660Z]  > git config --get remote.origin.url # timeout=10
[2021-04-13T21:50:38.664Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:50:38.668Z]  > git merge e8afb8db469285608ee75d2f949fe5175cad2f68 # timeout=10
[2021-04-13T21:50:38.679Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-04-13T21:50:38.690Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:50:38.695Z]  > git checkout -f f4cb0590685cc2373534e9a02e4902aa1a63528f # timeout=15
[2021-04-13T21:50:43.287Z] Commit message: "Update add_kubernetes_metadata.asciidoc"
[2021-04-13T21:50:43.288Z] First time build. Skipping changelog.
[2021-04-13T21:50:43.288Z] Cleaning workspace
[2021-04-13T21:50:43.462Z]  > git --version # timeout=10
[2021-04-13T21:50:43.465Z]  > git --version # 'git version 2.17.1'
[2021-04-13T21:50:43.470Z] fatal: bad object 5b62f622bb6e4e750b63eba4064d4de53db6f5e3
[2021-04-13T21:50:44.330Z] Timeout set to expire in 3 hr 0 min
[2021-04-13T21:50:44.365Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-04-13T21:50:44.621Z] [INFO] Number of builds to be searched 10
[2021-04-13T21:50:45.298Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-04-13T21:50:45.328Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25054/src/github.com/elastic/beats
[2021-04-13T21:50:45.373Z] [INFO] gitCheckout: Checkout SCM PR-25054 with default customisation from the Item.
[2021-04-13T21:50:45.416Z] [INFO] Override default checkout
[2021-04-13T21:50:45.495Z] Sleeping for 10 sec
[2021-04-13T21:50:43.290Z]  > git rev-parse --verify HEAD # timeout=10
[2021-04-13T21:50:43.295Z] Resetting working tree
[2021-04-13T21:50:43.295Z]  > git reset --hard # timeout=10
[2021-04-13T21:50:43.379Z]  > git clean -fdx # timeout=10
[2021-04-13T21:50:55.529Z] The recommended git tool is: git
[2021-04-13T21:50:55.579Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-04-13T21:50:55.637Z] Wiping out workspace first.
[2021-04-13T21:50:55.646Z] Cloning the remote Git repository
[2021-04-13T21:50:55.646Z] Using shallow clone with depth 10
[2021-04-13T21:50:55.646Z] Avoid fetching tags
[2021-04-13T21:50:55.661Z] Cloning repository git@github.com:elastic/beats.git
[2021-04-13T21:50:55.688Z]  > git init /var/lib/jenkins/workspace/Beats_beats_PR-25054/src/github.com/elastic/beats # timeout=10
[2021-04-13T21:50:55.693Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-04-13T21:50:55.694Z]  > git --version # timeout=10
[2021-04-13T21:50:55.697Z]  > git --version # 'git version 2.17.1'
[2021-04-13T21:50:55.697Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:50:55.701Z]  > git fetch --no-tags --progress -- git@github.com:elastic/beats.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-04-13T21:51:16.965Z] Cleaning workspace
[2021-04-13T21:51:16.980Z] Using shallow fetch with depth 10
[2021-04-13T21:51:16.980Z] Pruning obsolete local branches
[2021-04-13T21:51:16.948Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-04-13T21:51:16.952Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-04-13T21:51:16.960Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-04-13T21:51:16.968Z]  > git rev-parse --verify HEAD # timeout=10
[2021-04-13T21:51:16.972Z] No valid HEAD. Skipping the resetting
[2021-04-13T21:51:16.972Z]  > git clean -fdx # timeout=10
[2021-04-13T21:51:16.982Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-04-13T21:51:16.983Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:51:16.987Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/25054/head:refs/remotes/origin/PR-25054 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-04-13T21:51:18.327Z] Merging remotes/origin/master commit e8afb8db469285608ee75d2f949fe5175cad2f68 into PR head commit f4cb0590685cc2373534e9a02e4902aa1a63528f
[2021-04-13T21:51:18.330Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:51:18.334Z]  > git checkout -f f4cb0590685cc2373534e9a02e4902aa1a63528f # timeout=15
[2021-04-13T21:51:20.490Z] Merge succeeded, producing f4cb0590685cc2373534e9a02e4902aa1a63528f
[2021-04-13T21:51:20.490Z] Checking out Revision f4cb0590685cc2373534e9a02e4902aa1a63528f (PR-25054)
[2021-04-13T21:51:20.351Z]  > git remote # timeout=10
[2021-04-13T21:51:20.354Z]  > git config --get remote.origin.url # timeout=10
[2021-04-13T21:51:20.358Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-04-13T21:51:20.361Z]  > git merge e8afb8db469285608ee75d2f949fe5175cad2f68 # timeout=10
[2021-04-13T21:51:20.376Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-04-13T21:51:20.653Z]  > git config core.sparsecheckout # timeout=10
[2021-04-13T21:51:20.656Z]  > git checkout -f f4cb0590685cc2373534e9a02e4902aa1a63528f # timeout=15
[2021-04-13T21:51:22.082Z] Commit message: "Update add_kubernetes_metadata.asciidoc"
[2021-04-13T21:51:22.082Z] Cleaning workspace
[2021-04-13T21:51:22.273Z]  > git --version # timeout=10
[2021-04-13T21:51:22.278Z]  > git --version # 'git version 2.17.1'
[2021-04-13T21:51:22.282Z] fatal [...]

2021-04-13 21:57 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2021-04-13 21:57 UTC, bmorelli25 commented
@elasticmachine, run elasticsearch-ci/docs

2021-04-13 21:57 UTC, bmorelli25 commented
jenkins, run the tests please

2021-04-13 22:27 UTC, dedemorton requested changes
Thanks for the contribution! I think you need to make another pass at this topic because you have missed some sentences that need attention. I've marked a few, but there are others. Thanks!

2021-04-13 22:27 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +At startup, it detects an `in_cluster` environment and caches the
A comma is OK, but the general rule is to add a comma after an introductory phrase of 4 or more words.

2021-04-13 22:27 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +In addition, Node's metadata and Namespace's metadata are being added in Pod's metadata.
```suggestion
In addition, the node and namespace metadata is added to the pod metadata.
```

2021-04-13 22:27 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
>  Indexers use pods metadata to create unique identifiers for each one of the
```suggestion
Indexers use pod metadata to create unique identifiers for each one of the
```
```suggestion
Indexers use pods metadata to create unique identifiers for each one of the
```

2021-04-13 22:27 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +`add_resource_metadata`:: (Optional) Specify labels and annotations filters for the extra metadata coming from Node and namespace.
Why is Node capitalized? It should be lowercase, no? See the [K8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

2021-04-13 22:27 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +while annotations are not added by default. These settings are useful when labels' and annotations'
Should labels and annotations be possessive here?

2021-04-21 20:09 UTC, bmorelli25 commented
Jenkins, run the tests please

2021-04-21 20:09 UTC, bmorelli25 commented
@elasticmachine, run elasticsearch-ci/docs

2021-04-23 18:18 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
>   `add_resource_metadata` can be done for `node` or `namespace`. By default all labels will be included
```suggestion
 `add_resource_metadata` can be done for `node` or `namespace`. By default all labels are included
```

2021-04-23 18:20 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +`default_indexers.enabled`:: (Optional) Enable or disable default pod indexers to specify your own.
```suggestion
`default_indexers.enabled`:: (Optional) Enable or disable default pod indexers when you want to specify your own.
```

2021-04-23 18:21 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +`default_indexers.enabled`:: (Optional) Enable or disable default pod indexers to specify your own.
my edit is wordier, but it makes it clear that you need to do more than enable or disable the default indexers.

2021-04-23 18:22 UTC, dedemorton commented on libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
> +`default_matchers.enabled`:: (Optional) Enable or disable default pod matchers to specify your own.
```suggestion
`default_matchers.enabled`:: (Optional) Enable or disable default pod matchers when you want to specify your own.
```

2021-04-23 18:23 UTC, dedemorton approved these changes

2021-04-23 23:13 UTC, merged