Report dataset metrics in monitoring log reporter
elastic/beats pull request #25727
Opened 2021-05-16 18:58 UTC by andrewkroh

## What does this PR do?

This adds periodic reporting of "dataset" metrics to the logs. This can be disabled by configuring `logging.metrics.namespaces`. These are the same metrics available from the HTTP monitoring endpoint under the /dataset path. This primarily improves visibility of Filebeat and Metricbeat because they make use of the "dataset" namespace for input and metricset instance metrics.

## Why is it important?

Prior to 7.10 the Filebeat input metrics were reported in the logged metrics, but this was lost when the metrics moved to the "dataset" namespace. It was a useful feature to have for remote debugging.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates https://github.com/elastic/beats/pull/19977
- Relates https://github.com/elastic/beats/pull/6836

## Logs

```
2021-05-16T14:20:17.885-0400    INFO    [monitoring]    log/log.go:183  Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":60,"time":{"ms":60}},"total":{"ticks":250,"time":{"ms":250},"value":250},"user":{"ticks":190,"time":{"ms":190}}},"info":{"ephemeral_id":"caa6d941-b4ad-44fa-a5b2-6b07e41427d2","uptime":{"ms":30055}},"memstats":{"gc_next":35415664,"memory_alloc":17979752,"memory_sys":77415424,"memory_total":75690904,"rss":86929408},"runtime":{"goroutines":62}},"filebeat":{"events":{"active":534,"added":543,"done":9},"harvester":{"open_files":8,"running":8,"started":8}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":0},"type":"elasticsearch"},"pipeline":{"clients":1,"events":{"active":528,"filtered":15,"published":528,"retry":150,"total":543},"queue":{"max_events":4096}}},"registrar":{"states":{"current":9,"update":9},"writes":{"success":9,"total":9}},"system":{"cpu":{"cores":12},"load":{"1":1.6616,"15":2.3765,"5":2.1978,"norm":{"1":0.1385,"15":0.198,"5":0.1831}}}}, "dataset": {"069dc32a-b71f-4344-a600-fa06d5071036":{"last_event_published_time":"2021-05-16T14:19:47.918Z","last_event_timestamp":"2021-05-16T14:19:47.918Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/pan_inc_traffic_ietf.log","read_offset":51624,"size":51624,"start_time":"2021-05-16T14:19:47.886Z"},"0a414085-71c7-4e62-86c8-d4ef09a2292b":{"last_event_published_time":"2021-05-16T14:19:47.888Z","last_event_timestamp":"2021-05-16T14:19:47.888Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/pan_inc_other.log","read_offset":6217,"size":6217,"start_time":"2021-05-16T14:19:47.884Z"},"12be14ea-a067-480f-9b3a-7f043a826068":{"last_event_published_time":"2021-05-16T14:19:47.886Z","last_event_timestamp":"2021-05-16T14:19:47.885Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/global_protect.log","read_offset":1641,"size":1641,"start_time":"2021-05-16T14:19:47.884Z"},"12cf5432-b0ff-4cb6-8db3-098e54b9cc4b":{"last_event_published_time":"2021-05-16T14:19:47.898Z","last_event_timestamp":"2021-05-16T14:19:47.898Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/userid.log","read_offset":2626,"size":2626,"start_time":"2021-05-16T14:19:47.890Z"},"8c19b7d1-a670-4e91-9950-6a96e0c49457":{"last_event_published_time":"2021-05-16T14:19:47.920Z","last_event_timestamp":"2021-05-16T14:19:47.920Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/traffic.log","read_offset":46385,"size":46385,"start_time":"2021-05-16T14:19:47.888Z"},"926dd152-78a7-45e8-abea-778e22794590":{"last_event_published_time":"2021-05-16T14:19:47.906Z","last_event_timestamp":"2021-05-16T14:19:47.905Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log","read_offset":36298,"size":36298,"start_time":"2021-05-16T14:19:47.885Z"},"c089fcd5-1822-4017-9739-4890d65ca098":{"last_event_published_time":"2021-05-16T14:19:47.915Z","last_event_timestamp":"2021-05-16T14:19:47.915Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/threat.log","read_offset":41586,"size":41586,"start_time":"2021-05-16T14:19:47.887Z"},"ddec21fc-29fb-4ed5-b23c-2cc6f6f09d12":{"last_event_published_time":"2021-05-16T14:19:47.914Z","last_event_timestamp":"2021-05-16T14:19:47.914Z","name":"/Users/akroh/go/src/github.com/elastic/beats/x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log","read_offset":39870,"size":39870,"start_time":"2021-05-16T14:19:47.884Z"}}}}
2021-05-16T14:20:47.883-0400    INFO    [monitoring]    log/log.go:183  Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":66,"time":{"ms":6}},"total":{"ticks":262,"time":{"ms":12},"value":262},"user":{"ticks":196,"time":{"ms":6}}},"info":{"ephemeral_id":"caa6d941-b4ad-44fa-a5b2-6b07e41427d2","uptime":{"ms":60054}},"memstats":{"gc_next":35415664,"memory_alloc":19664576,"memory_total":77375728,"rss":87179264},"runtime":{"goroutines":62}},"filebeat":{"harvester":{"open_files":8,"running":8}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":0}},"pipeline":{"clients":1,"events":{"active":528,"retry":50}}},"registrar":{"states":{"current":9}},"system":{"load":{"1":1.6016,"15":2.3442,"5":2.1299,"norm":{"1":0.1335,"15":0.1954,"5":0.1775}}}}}}
2021-05-16T14:23:35.401-0400    INFO    [monitoring]    log/log.go:191  Total metrics   {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":107,"time":{"ms":107}},"total":{"ticks":375,"time":{"ms":375},"value":375},"user":{"ticks":268,"time":{"ms":268}}},"info":{"ephemeral_id":"caa6d941-b4ad-44fa-a5b2-6b07e41427d2","uptime":{"ms":227570}},"memstats":{"gc_next":35912432,"memory_alloc":22875816,"memory_sys":77415424,"memory_total":86230296,"rss":92229632},"runtime":{"goroutines":10}},"filebeat":{"events":{"active":535,"added":544,"done":9},"harvester":{"closed":8,"open_files":0,"running":0,"skipped":0,"started":8},"input":{"log":{"files":{"renamed":0,"truncated":0}},"netflow":{"flows":0,"packets":{"dropped":0,"received":0}}}},"libbeat":{"config":{"module":{"running":0,"starts":0,"stops":0},"reloads":0,"scans":0},"output":{"events":{"acked":0,"active":0,"batches":0,"dropped":0,"duplicates":0,"failed":0,"toomany":0,"total":0},"read":{"bytes":0,"errors":0},"type":"elasticsearch","write":{"bytes":0,"errors":0}},"pipeline":{"clients":0,"events":{"active":529,"dropped":0,"failed":0,"filtered":15,"published":529,"retry":400,"total":544},"queue":{"acked":0,"max_events":4096}}},"registrar":{"states":{"cleanup":0,"current":9,"update":9},"writes":{"fail":0,"success":9,"total":9}},"system":{"cpu":{"cores":12},"load":{"1":3.0503,"15":2.4072,"5":2.4136,"norm":{"1":0.2542,"15":0.2006,"5":0.2011}}}}}}
```

2021-05-16 18:58 UTC, elasticmachine commented
Pinging @elastic/agent (Team:Agent)

2021-05-16 18:58 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-05-16 20:11 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_25727.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #25727 opened`



* Start Time: 2021-05-16T18:59:03.094+0000


* Duration: 72 min 1 sec


* Commit: 4d8e3c0a9cc3f29b1331e62b52ef5a2e8d81ac94



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 15924  |
| Skipped      | 1463 |
| Total        | 17388   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25727/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25727/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Build&Test / libbeat-build / test_logging_metrics – libbeat.tests.system.test_base.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 2 seconds. 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 self = <test_base.Test testMethod=test_logging_metrics>

    def test_logging_metrics(self):
        self.render_config_template(
            metrics_period="0.1s"
        )
        proc = self.start_beat(logging_args=["-e"])
        self.wait_until(
            lambda: self.log_contains("Non-zero metrics in the last 100ms"),
            max_timeout=2)
        proc.check_kill_and_wait()
        self.wait_until(
            lambda: self.log_contains("Total non-zero metrics"),
>           max_timeout=2)

tests/system/test_base.py:142: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_base.Test testMethod=test_logging_metrics>
cond = <function Test.test_logging_metrics.<locals>.<lambda> at 0x7f268051fbf8>
max_timeout = 2, poll_interval = 0.1, name = 'cond'

    def wait_until(self, cond, max_timeout=10, poll_interval=0.1, name="cond"):
        """
        Waits until the cond function returns true,
        or until the max_timeout is reached. Calls the cond
        function every poll_interval seconds.
    
        If the max_timeout is reached before cond() returns
        true, an exception is raised.
        """
        start = datetime.now()
        while not cond():
            if datetime.now() - start > timedelta(seconds=max_timeout):
                raise TimeoutError("Timeout waiting for '{}' to be true. ".format(name) +
>                                  "Waited {} seconds.".format(max_timeout))
E               beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 2 seconds.

tests/system/beat/beat.py:363: TimeoutError 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25727/detail/PR-25727/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `libbeat-build - mage build test`
<ul>
<li>Took 3 min 17 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25727/runs/1/steps/9169/log/?start=0">here</a></li>
<li>Description: <code>mage build test</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25727/runs/1/steps/10363/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 1'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-05-16T20:10:19.265Z] 10.67s call     x-pack/filebeat/tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_288_cisco
[2021-05-16T20:10:19.265Z] 10.62s call     x-pack/filebeat/tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_207_f5
[2021-05-16T20:10:19.265Z] 10.54s call     x-pack/filebeat/tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_086_juniper
[2021-05-16T20:10:19.265Z] ======================= 410 passed in 1955.15s (0:32:35) =======================
[2021-05-16T20:10:19.265Z] >> python test: Integration Testing Complete
[2021-05-16T20:10:23.022Z] Cleaning up /var/lib/jenkins/workspace/PR-25727-1-6dbc825d-0f2e-4870-9493-576710566451
[2021-05-16T20:10:23.022Z] Client: Docker Engine - Community
[2021-05-16T20:10:23.022Z]  Version:           20.10.3
[2021-05-16T20:10:23.022Z]  API version:       1.41
[2021-05-16T20:10:23.022Z]  Go version:        go1.13.15
[2021-05-16T20:10:23.022Z]  Git commit:        48d30b5
[2021-05-16T20:10:23.022Z]  Built:             Fri Jan 29 14:33:13 2021
[2021-05-16T20:10:23.022Z]  OS/Arch:           linux/amd64
[2021-05-16T20:10:23.022Z]  Context:           default
[2021-05-16T20:10:23.022Z]  Experimental:      true
[2021-05-16T20:10:23.022Z] 
[2021-05-16T20:10:23.022Z] Server: Docker Engine - Community
[2021-05-16T20:10:23.022Z]  Engine:
[2021-05-16T20:10:23.022Z]   Version:          20.10.3
[2021-05-16T20:10:23.022Z]   API version:      1.41 (minimum version 1.12)
[2021-05-16T20:10:23.022Z]   Go version:       go1.13.15
[2021-05-16T20:10:23.022Z]   Git commit:       46229ca
[2021-05-16T20:10:23.022Z]   Built:            Fri Jan 29 14:31:25 2021
[2021-05-16T20:10:23.022Z]   OS/Arch:          linux/amd64
[2021-05-16T20:10:23.022Z]   Experimental:     false
[2021-05-16T20:10:23.022Z]  containerd:
[2021-05-16T20:10:23.022Z]   Version:          1.4.4
[2021-05-16T20:10:23.022Z]   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
[2021-05-16T20:10:23.022Z]  runc:
[2021-05-16T20:10:23.023Z]   Version:          1.0.0-rc93
[2021-05-16T20:10:23.023Z]   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
[2021-05-16T20:10:23.023Z]  docker-init:
[2021-05-16T20:10:23.023Z]   Version:          0.19.0
[2021-05-16T20:10:23.023Z]   GitCommit:        de40ad0
[2021-05-16T20:10:23.023Z] Change ownership of all files inside the specific folder from root/root to current user/group
[2021-05-16T20:10:23.023Z] Unable to find image 'alpine:3.4' locally
[2021-05-16T20:10:23.593Z] 3.4: Pulling from library/alpine
[2021-05-16T20:10:23.853Z] c1e54eec4b57: Pulling fs layer
[2021-05-16T20:10:26.408Z] c1e54eec4b57: Verifying Checksum
[2021-05-16T20:10:26.408Z] c1e54eec4b57: Download complete
[2021-05-16T20:10:26.408Z] c1e54eec4b57: Pull complete
[2021-05-16T20:10:26.408Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7 [...]

2021-05-17 09:44 UTC, ruflin commented
@simitt This might affect apm?

2021-05-17 12:04 UTC, simitt commented
> This can be disabled by configuring `logging.metrics.namespaces`. 

@andrewkroh I haven't tested this, but does that mean that `logging.metrics.enabled: false` will no longer have the same effect to disable metrics in logs?

2021-05-17 13:12 UTC, andrewkroh commented
Hi @simitt, `logging.metrics.enabled: false` will continue to have the same behavior in that it entirely disables the log reporter component of the monitoring framework. 

The `logging.metrics.namespaces` setting allows you to select what metric namespaces are reported. The old implicit behavior was `logging.metrics.namespaces: [stats]` where stats is the same metrics as the [http endpoint /stats](https://www.elastic.co/guide/en/beats/filebeat/master/http-endpoint.html#_stats). This adds reporting of the `dataset` namespace to that list. I think only Filebeat and Metricbeat actually make use of this (e.g. `monitoring.GetNamespace("dataset").GetRegistry()`).

2021-05-17 14:19 UTC, andrewkroh commented
run tests

2021-07-20 12:34 UTC, kvch requested changes
The namespace "dataset" contains lots of metrics about every open file in Filebeat. Those metrics were moved to the dataset endpoint on purpose later because users did not want to see that much information about their files. I am all for this new option, but please do not add "dataset" to the default namespaces.

2021-08-12 08:12 UTC, kvch commented on libbeat/monitoring/report/log/log.go
> +func isGauge(key string) bool {
Where do you use this function?

2021-08-12 11:33 UTC, andrewkroh commented on libbeat/monitoring/report/log/log.go
> +func isGauge(key string) bool {
Fixed it and added a test to verify it.

2021-08-13 11:15 UTC, kvch approved these changes

2021-08-13 15:10 UTC, merged