Improve ES output error insights
elastic/beats pull request #25825
Opened 2021-05-24 09:47 UTC by ChrsMark

## What does this PR do?
This PR improves ES output insights by:
- do not record EOF as error  in `StatsDialer`
- wrap `StatsDialer`s  with a new dialer wrapper that logs errors

## Why is it important?
To provide [better insights](https://github.com/elastic/sdh-beats/issues/937) on Output errors.

2021-05-24 09:47 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-05-24 09:53 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25825/detail/PR-25825/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25825/detail/PR-25825/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25825/detail/PR-25825/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25825/detail/PR-25825/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #25825 opened`


* Reason: `Aborted from #2`


* Start Time: 2021-05-24T09:47:51.389+0000


* Duration: 5 min 10 sec


* Commit: 8d6b38c4854b8eca9961403aacb67aa7e7d91d54




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25825/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-05-24T09:49:40.322Z]  > git merge 4de534fe95f115da6afb2c2819335948ce7020c1 # timeout=10
[2021-05-24T09:49:40.335Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-05-24T09:49:40.344Z]  > git config core.sparsecheckout # timeout=10
[2021-05-24T09:49:40.348Z]  > git checkout -f 8d6b38c4854b8eca9961403aacb67aa7e7d91d54 # timeout=15
[2021-05-24T09:49:45.107Z] Commit message: "Improve ES output error insights"
[2021-05-24T09:49:45.107Z] First time build. Skipping changelog.
[2021-05-24T09:49:45.108Z] Cleaning workspace
[2021-05-24T09:49:45.109Z]  > git rev-parse --verify HEAD # timeout=10
[2021-05-24T09:49:45.112Z] Resetting working tree
[2021-05-24T09:49:45.113Z]  > git reset --hard # timeout=10
[2021-05-24T09:49:45.589Z]  > git --version # timeout=10
[2021-05-24T09:49:45.592Z]  > git --version # 'git version 2.17.1'
[2021-05-24T09:49:45.595Z] fatal: bad object 338418b47db64d2f76791e31a598d28cc38d49fc
[2021-05-24T09:49:46.413Z] Timeout set to expire in 3 hr 0 min
[2021-05-24T09:49:46.440Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-05-24T09:49:46.646Z] [INFO] Number of builds to be searched 10
[2021-05-24T09:49:47.255Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-05-24T09:49:47.276Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25825/src/github.com/elastic/beats
[2021-05-24T09:49:47.310Z] [INFO] gitCheckout: Checkout SCM PR-25825 with default customisation from the Item.
[2021-05-24T09:49:47.342Z] [INFO] Override default checkout
[2021-05-24T09:49:47.399Z] Sleeping for 10 sec
[2021-05-24T09:49:45.473Z]  > git clean -fdx # timeout=10
[2021-05-24T09:49:57.428Z] The recommended git tool is: git
[2021-05-24T09:49:57.521Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-05-24T09:49:57.527Z] Wiping out workspace first.
[2021-05-24T09:49:57.537Z] Cloning the remote Git repository
[2021-05-24T09:49:57.537Z] Using shallow clone with depth 10
[2021-05-24T09:49:57.537Z] Avoid fetching tags
[2021-05-24T09:49:57.593Z] Cloning repository git@github.com:elastic/beats.git
[2021-05-24T09:49:57.705Z]  > git init /var/lib/jenkins/workspace/Beats_beats_PR-25825/src/github.com/elastic/beats # timeout=10
[2021-05-24T09:49:57.710Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-05-24T09:49:57.710Z]  > git --version # timeout=10
[2021-05-24T09:49:57.714Z]  > git --version # 'git version 2.17.1'
[2021-05-24T09:49:57.714Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-24T09:49:57.718Z]  > git fetch --no-tags --progress -- git@github.com:elastic/beats.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-05-24T09:50:18.291Z] Cleaning workspace
[2021-05-24T09:50:18.303Z] Using shallow fetch with depth 10
[2021-05-24T09:50:18.303Z] Pruning obsolete local branches
[2021-05-24T09:50:18.276Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-05-24T09:50:18.280Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-05-24T09:50:18.287Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-05-24T09:50:18.293Z]  > git rev-parse --verify HEAD # timeout=10
[2021-05-24T09:50:18.296Z] No valid HEAD. Skipping the resetting
[2021-05-24T09:50:18.297Z]  > git clean -fdx # timeout=10
[2021-05-24T09:50:18.305Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-05-24T09:50:18.305Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-24T09:50:18.308Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/25825/head:refs/remotes/origin/PR-25825 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-05-24T09:50:19.245Z] Merging remotes/origin/master commit 4de534fe95f115da6afb2c2819335948ce7020c1 into PR head commit 8d6b38c4854b8eca9961403aacb67aa7e7d91d54
[2021-05-24T09:50:20.785Z] Merge succeeded, producing 8d6b38c4854b8eca9961403aacb67aa7e7d91d54
[2021-05-24T09:50:20.785Z] Checking out Revision 8d6b38c4854b8eca9961403aacb67aa7e7d91d54 (PR-25825)
[2021-05-24T09:50:19.247Z]  > git config core.sparsecheckout # timeout=10
[2021-05-24T09:50:19.250Z]  > git checkout -f 8d6b38c4854b8eca9961403aacb67aa7e7d91d54 # timeout=15
[2021-05-24T09:50:20.761Z]  > git remote # timeout=10
[2021-05-24T09:50:20.765Z]  > git config --get remote.origin.url # timeout=10
[2021-05-24T09:50:20.767Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-24T09:50:20.770Z]  > git merge 4de534fe95f115da6afb2c2819335948ce7020c1 # timeout=10
[2021-05-24T09:50:20.780Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-05-24T09:50:20.787Z]  > git config core.sparsecheckout # timeout=10
[2021-05-24T09:50:20.790Z]  > git checkout -f 8d6b38c4854b8eca9961403aacb67aa7e7d91d54 # timeout=15
[2021-05-24T09:50:21.941Z] Commit message: "Improve ES output error insights"
[2021-05-24T09:50:21.941Z] Cleaning workspace
[2021-05-24T09:50:22.097Z]  > git --version # timeout=10
[2021-05-24T09:50:22.099Z]  > git --version # 'git version 2.17.1'
[2021-05-24T09:50:22.103Z] fatal: bad object 338418b47db64d2f76791e31a598d28cc38d49fc
[2021-05-24T09:50:23.142Z] Masking supported pattern matches of $GIT_USERNAME or $GIT_PASSWORD
[2021-05-24T09:50:21.942Z]  > git rev-parse --verify HEAD # timeout=10
[2021-05-24T09:50:21.945Z] Resetting working tree
[2021-05-24T09:50:21.945Z]  > git reset --hard # timeout=10
[2021-05-24T09:50:22.027Z]  > git clean -fdx # timeout=10
[2021-05-24T09:50:23.820Z] + git fetch https://****:****@github.com/elastic/beats.git +refs/pull/*/head:refs/remotes/origin/pr/*
[2021-05-24T09:51:31.711Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25825/src/github.com/elastic/beats/.git
[2021-05-24T09:51:31.901Z] Archiving artifacts
[2021-05-24T09:51:33.027Z] + git rev-parse HEAD
[2021-05-24T09:51:33.466Z] + git rev-parse HEAD
[2021-05-24T09:51:33.771Z] + git rev-parse origin/pr/25825
[2021-05-24T09:51:33.820Z] [INFO] githubEnv: Found Git Build Cause: pr
[2021-05-24T09:51:34.029Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-24T09:51:35.144Z] [WARN] githubApiCall: The REST API call https://api.github.com/repos/elastic/beats/pulls/25825/reviews return 0 elements
[2021-05-24T09:51:35.202Z] [INFO] githubPrCheckApproved: Title: Improve ES output error insights - User: ChrsMark - [...]

2021-05-25 15:51 UTC, urso commented on libbeat/common/transport/logging.go
> +			err = nil
Do not eat EOF.

2021-05-25 15:52 UTC, urso commented on libbeat/common/transport/logging.go
> +			err = nil
do not eat EOF. We want to report only.

2021-05-25 15:54 UTC, urso commented on libbeat/common/transport/stats.go
> +		}
how about: `if err != nil && err != io.EOF && err != context.Canceled { s.stats.ReadError(err) }` ?

2021-05-25 15:55 UTC, urso commented on libbeat/esleg/eslegclient/connection.go
> +		tlsDialer = transport.LoggingDialer(tlsDialer, logger)
We always want the logging. Lets move the `LoggingDialer` out of the if statement.

2021-05-25 15:56 UTC, urso requested changes
Is there a reason for not instrumenting `statsConn.Write`?

2021-05-26 07:37 UTC, ChrsMark commented
> Is there a reason for not instrumenting `statsConn.Write`?

Tuned `Write` too. Let me know you think.

2021-05-27 11:17 UTC, urso commented on libbeat/common/transport/logging.go
> +	return ConnWrapper(d, func(c net.Conn) net.Conn {
One more ask: let's make use of structured logging, so we can tell which host the log output is to be associated with. e.g.

```
return DialFunc(func(network, address string) (net.Conn, error) {
  logger := logger.With("network", network, "address", address)
  conn, err := d.Dial(network, address)
  ...
})
```

The address includes `<hostname|ip>:<port>`.

2021-05-27 14:45 UTC, urso commented on libbeat/common/transport/logging.go
> +			logger.Errorf("error dialing", err)
Missing `%v` or do not use `Errorf`.

nit; Log messages should be a sentence and start with uppercase.

2021-05-27 14:50 UTC, urso commented on libbeat/common/transport/logging.go
> +		l.logger.Debugf("error reading from connection: %v", err)
Uppercase

2021-05-27 14:50 UTC, urso commented on libbeat/common/transport/logging.go
> +		l.logger.Debugf("error writing to connection: %v", err)
Uppercase

2021-05-27 15:03 UTC, urso approved these changes

2021-05-28 07:45 UTC, ChrsMark commented
Failing tests seem to be unrelated (hitting issue reported at https://github.com/elastic/beats/issues/25956). Merging this one.

2021-05-28 07:45 UTC, merged