Add support to combine update operations
elastic/beats pull request #25976
Opened 2021-05-27 21:22 UTC by urso

- Enhancement

## What does this PR do?

With this change the update operations emited by the filestream input
are not directly applied up on ACK, but will be scheduled for
application. A backgroun go-routine picks up all updates from all inputs
that are or have been active and applies the changes to the registry.

This removes the application to the cursor and write to persistent store
from the ACK handler path, which when blocked could produce back
pressure on the outputs, processors or inputs.

When another set of state updates are acked by the output, but the
writer is still busy with past updates, then we merge the new and other
pending updates into a single update operation. This reduces the amount
of in memory and on disk updates we need to execute if the system gets
under pressure.

TODO: performance tests logs input, master, and changes.

## Why is it important?

With this change backpressure from the registry writes is mostly
nullified, which removes the need for a `registry.flush` setting, as we
have globally for the logs input.

limitations: We combine as many updates as we can. If the registry can't
be updates for a long time, there is a chance of publishing duplicates
when filebeat is restarted after a crash. This same issue exists with
the `filebeat.registry.flush` setting.
On clean shutdown we still serialize all pending updates for already
ACKed events.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-05-27 21:25 UTC, urso commented on filebeat/input/filestream/internal/input-logfile/publish.go
> +	resource.pendingUpdate = updates
we do not apply the update directly anymore. Instead we store the most recent delta with the resource. The delta is applied lazily when the current `pendingCursor` state is required for real. This removes an 'expensive' operation from the hot path.

2021-05-27 21:28 UTC, urso commented on filebeat/input/filestream/internal/input-logfile/update_writer.go
> +	defer w.mutex.Unlock()
`Schedule` is a point of contention here. But it is still better then blocking and waiting for the serialization and IO to be finished.

2021-05-27 21:33 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25976/detail/PR-25976/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25976/detail/PR-25976/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25976/detail/PR-25976/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25976/detail/PR-25976/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #25976 opened`


* Reason: `Aborted from #2`


* Start Time: 2021-05-27T21:22:35.024+0000


* Duration: 11 min 49 sec


* Commit: a2cc279c64812a7d2415e6c52bb11ad255b08e4b




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25976/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-25976/detail/PR-25976/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25976/runs/1/steps/904/log/?start=0">here</a></li>
<li>Description: <code>Error 'org.jenkinsci.plugins.workflow.steps.FlowInterruptedException'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-05-27T21:30:17.802Z] + .ci/scripts/get-vendor-dependencies.sh x-pack/metricbeat
[2021-05-27T21:30:19.716Z] + git diff --name-only origin/master...a2cc279c64812a7d2415e6c52bb11ad255b08e4b
[2021-05-27T21:30:21.494Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-27T21:30:21.715Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/build-reasons
[2021-05-27T21:30:22.335Z] + .ci/scripts/get-vendor-dependencies.sh x-pack/osquerybeat
[2021-05-27T21:30:23.715Z] + git diff --name-only origin/master...a2cc279c64812a7d2415e6c52bb11ad255b08e4b
[2021-05-27T21:30:24.423Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-27T21:30:24.627Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/build-reasons
[2021-05-27T21:30:25.207Z] + .ci/scripts/get-vendor-dependencies.sh x-pack/packetbeat
[2021-05-27T21:30:26.587Z] + git diff --name-only origin/master...a2cc279c64812a7d2415e6c52bb11ad255b08e4b
[2021-05-27T21:30:27.392Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-27T21:30:27.603Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/build-reasons
[2021-05-27T21:30:28.202Z] + .ci/scripts/get-vendor-dependencies.sh x-pack/winlogbeat
[2021-05-27T21:30:29.575Z] + git diff --name-only origin/master...a2cc279c64812a7d2415e6c52bb11ad255b08e4b
[2021-05-27T21:30:30.336Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-27T21:30:30.530Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/build-reasons
[2021-05-27T21:30:31.110Z] + .ci/scripts/get-vendor-dependencies.sh dev-tools
[2021-05-27T21:30:31.110Z] package github.com/elastic/beats/v7/dev-tools: build constraints exclude all Go files in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/dev-tools
[2021-05-27T21:30:31.480Z] + git diff --name-only origin/master...a2cc279c64812a7d2415e6c52bb11ad255b08e4b
[2021-05-27T21:30:31.570Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-05-27T21:30:31.776Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-25976/src/github.com/elastic/beats/build-reasons
[2021-05-27T21:30:32.256Z] Sleeping for 1 min 23 sec
[2021-05-27T21:30:32.269Z] Sleeping for 47 sec
[2021-05-27T21:30:32.413Z] + make check-python
[2021-05-27T21:31:19.292Z] [INFO] Allocating a worker with the labels 'immutable && ubuntu-18'.
[2021-05-27T21:31:34.308Z] Still waiting to schedule task
[2021-05-27T21:31:34.308Z] All nodes of label ‘immutable&&ubuntu-18’ are offline
[2021-05-27T21:31:55.276Z] [INFO] Allocating a worker with the labels 'immutable && ubuntu-18'.
[2021-05-27T21:32:09.275Z] + make check-go
[2021-05-27T21:32:10.178Z] + make notice
[2021-05-27T21:32:10.178Z] Generating NOTICE
[2021-05-27T21:32:10.178Z] go mod tidy
[2021-05-27T21:32:10.300Z] Still waiting to schedule task
[2021-05-27T21:32:10.302Z] All nodes of label ‘immutable&&ubuntu-18’ are offline
[2021-05-27T21:32:10.755Z] go mod download
[2021-05-27T21:32:11.020Z] go list -m -json all | go run go.elastic.co/go-licence-detector \
[2021-05-27T21:32:11.020Z] 	-includeIndirect \
[2021-05-27T21:32:11.020Z] 	-rules dev-tools/notice/rules.json \
[2021-05-27T21:32:11.020Z] 	-overrides dev-tools/notice/overrides.json \
[2021-05-27T21:32:11.020Z] 	-noticeTemplate dev-tools/notice/NOTICE.txt.tmpl \
[2021-05-27T21:32:11.020Z] 	-noticeOut NOTICE.txt \
[2021-05-27T21:32:11.020Z] 	-depsOut ""
[2021-05-27T21:33:07.667Z] + make check-no-changes
[2021-05-27T21:33:13.006Z] Failed in branch filebeat-lint
[2021-05-27T21:33:13.018Z] Failed in branch x-pack/filebeat-lint
[2021-05-27T21:33:13.495Z] + go clean -modcache
[2021-05-27T21:33:17.182Z] Cleaning up /var/lib/jenkins/workspace/Beats_beats_PR-25976
[2021-05-27T21:33:17.182Z] Client: Docker Engine - Community
[2021-05-27T21:33:17.182Z]  Version:           20.10.3
[2021-05-27T21:33:17.182Z]  API version:       1.41
[2021-05-27T21:33:17.182Z]  Go version:        go1.13.15
[2021-05-27T21:33:17.182Z]  Git commit:        48d30b5
[2021-05-27T21:33:17.182Z]  Built:             Fri Jan 29 14:33:13 2021
[2021-05-27T21:33:17.182Z]  OS/Arch:           linux/amd64
[2021-05-27T21:33:17.182Z]  Context:           default
[2021-05-27T21:33:17.182Z]  Experimental:      true
[2021-05-27T21:33:17.182Z] 
[2021-05-27T21:33:17.182Z] Server: Docker Engine - Community
[2021-05-27T21:33:17.182Z]  Engine:
[2021-05-27T21:33:17.182Z]   Version:          20.10.3
[2021-05-27T21:33:17.182Z]   API version:      1.41 (minimum version 1.12)
[2021-05-27T21:33:17.182Z]   Go version:       go1.13.15
[2021-05-27T21:33:17.182Z]   Git commit:       46229ca
[2021-05-27T21:33:17.182Z]   Built:            Fri Jan 29 14:31:25 2021
[2021-05-27T21:33:17.182Z]   OS/Arch:          linux/amd64
[2021-05-27T21:33:17.182Z]   Experimental:     false
[2021-05-27T21:33:17.182Z]  containerd:
[2021-05-27T21:33:17.182Z]   Version:          1.4.4
[2021-05-27T21:33:17.182Z]   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
[2021-05-27T21:33:17.182Z]  runc:
[2021-05-27T21:33:17.182Z]   Version:          1.0.0-rc93
[2021-05-27T21:33:17.182Z]   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
[2021-05-27T21:33:17.182Z]  docker-init:
[2021-05-27T21:33:17.182Z]   Version:          0.19.0
[2021-05-27T21:33:17.182Z]   GitCommit:        de40ad0
[2021-05-27T21:33:17.182Z] Change ownership of all files inside the specific folder from root/root to current user/group
[2021-05-27T21:33:17.182Z] Unable to find image 'alpine:3.4' locally
[2021-05-27T21:33:17.789Z] 3.4: Pulling from library/alpine
[2021-05-27T21:33:18.054Z] c1e54eec4b57: Pulling fs layer
[2021-05-27T21:33:18.318Z] c1e54eec4b57: Download complete
[2021-05-27T21:33:18.584Z] c1e54eec4b57: Pull comp [...]

2021-05-28 15:32 UTC, urso commented
/test

2021-05-31 11:07 UTC, kvch approved these changes

2021-06-01 10:39 UTC, kvch requested changes
I like the general direction of the PR, hence I approved the PR. I am glad `loginp.Cursor` no longer requires a store instance. \o/

But please provide tests for your changes.

2021-07-19 19:39 UTC, elasticmachine commented
Pinging @elastic/agent (Team:Agent)

2021-07-19 19:46 UTC, urso commented
Added tests. PR is now ready for review.

2021-07-20 12:26 UTC, kvch approved these changes

2021-07-21 13:01 UTC, merged