Update http-endpoint.asciidoc
elastic/beats pull request #26463
Opened 2021-06-24 08:43 UTC by amrmotan

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-06-24 08:48 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26463/detail/PR-26463/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26463/detail/PR-26463/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26463/detail/PR-26463/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26463/detail/PR-26463/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #26463 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-06-24T08:43:36.668+0000


* Duration: 4 min 14 sec


* Commit: 1caf06d99cefdad51b8774da1ffa48037ed72342




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-26463/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26463/detail/PR-26463/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-26463/runs/1/steps/82/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/beats.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-26463/runs/1/steps/85/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-24T08:45:37.965Z] Checking out Revision 1caf06d99cefdad51b8774da1ffa48037ed72342 (PR-26463)
[2021-06-24T08:45:37.930Z]  > git remote # timeout=10
[2021-06-24T08:45:37.934Z]  > git config --get remote.origin.url # timeout=10
[2021-06-24T08:45:37.941Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-24T08:45:37.945Z]  > git merge 0869d91a08725eeeb7f10045b6fb7a3bdcee29a8 # timeout=10
[2021-06-24T08:45:37.959Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-06-24T08:45:37.967Z]  > git config core.sparsecheckout # timeout=10
[2021-06-24T08:45:37.971Z]  > git checkout -f 1caf06d99cefdad51b8774da1ffa48037ed72342 # timeout=15
[2021-06-24T08:45:42.865Z] Commit message: "Update http-endpoint.asciidoc"
[2021-06-24T08:45:42.866Z] First time build. Skipping changelog.
[2021-06-24T08:45:42.867Z] Cleaning workspace
[2021-06-24T08:45:43.039Z]  > git --version # timeout=10
[2021-06-24T08:45:43.042Z]  > git --version # 'git version 2.17.1'
[2021-06-24T08:45:43.045Z] fatal: bad object bbed8ab717206e63fa6cc1cef7d35f4a13f717ab
[2021-06-24T08:45:43.815Z] Timeout set to expire in 3 hr 0 min
[2021-06-24T08:45:43.841Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-06-24T08:45:44.116Z] [INFO] Number of builds to be searched 10
[2021-06-24T08:45:42.868Z]  > git rev-parse --verify HEAD # timeout=10
[2021-06-24T08:45:42.872Z] Resetting working tree
[2021-06-24T08:45:42.872Z]  > git reset --hard # timeout=10
[2021-06-24T08:45:42.955Z]  > git clean -fdx # timeout=10
[2021-06-24T08:45:44.875Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-06-24T08:45:44.900Z] Running in /var/lib/jenkins/workspace/Beats_beats_PR-26463@tmp
[2021-06-24T08:45:44.939Z] [INFO] gitCheckout: Checkout SCM PR-26463 with default customisation from the Item.
[2021-06-24T08:45:44.977Z] [INFO] Override default checkout
[2021-06-24T08:45:45.044Z] Sleeping for 10 sec
[2021-06-24T08:45:55.075Z] The recommended git tool is: git
[2021-06-24T08:45:55.134Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-06-24T08:45:55.139Z] Wiping out workspace first.
[2021-06-24T08:45:55.148Z] Cloning the remote Git repository
[2021-06-24T08:45:55.148Z] Using shallow clone with depth 10
[2021-06-24T08:45:55.148Z] Avoid fetching tags
[2021-06-24T08:45:55.162Z] Cloning repository git@github.com:elastic/beats.git
[2021-06-24T08:45:55.188Z]  > git init /var/lib/jenkins/workspace/Beats_beats_PR-26463@tmp # timeout=10
[2021-06-24T08:45:55.194Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-06-24T08:45:55.194Z]  > git --version # timeout=10
[2021-06-24T08:45:55.198Z]  > git --version # 'git version 2.17.1'
[2021-06-24T08:45:55.199Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-24T08:45:55.203Z]  > git fetch --no-tags --progress -- git@github.com:elastic/beats.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-06-24T08:46:17.129Z] Cleaning workspace
[2021-06-24T08:46:17.143Z] Using shallow fetch with depth 10
[2021-06-24T08:46:17.143Z] Pruning obsolete local branches
[2021-06-24T08:46:18.083Z] Merging remotes/origin/7.13 commit 0869d91a08725eeeb7f10045b6fb7a3bdcee29a8 into PR head commit 1caf06d99cefdad51b8774da1ffa48037ed72342
[2021-06-24T08:46:17.111Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-06-24T08:46:17.114Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-06-24T08:46:17.124Z]  > git config remote.origin.url git@github.com:elastic/beats.git # timeout=10
[2021-06-24T08:46:17.131Z]  > git rev-parse --verify HEAD # timeout=10
[2021-06-24T08:46:17.134Z] No valid HEAD. Skipping the resetting
[2021-06-24T08:46:17.135Z]  > git clean -fdx # timeout=10
[2021-06-24T08:46:17.146Z] Fetching upstream changes from git@github.com:elastic/beats.git
[2021-06-24T08:46:17.146Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-24T08:46:17.150Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/beats.git +refs/pull/26463/head:refs/remotes/origin/PR-26463 +refs/heads/7.13:refs/remotes/origin/7.13 # timeout=15
[2021-06-24T08:46:18.085Z]  > git config core.sparsecheckout # timeout=10
[2021-06-24T08:46:18.088Z]  > git checkout -f 1caf06d99cefdad51b8774da1ffa48037ed72342 # timeout=15
[2021-06-24T08:46:19.698Z] Merge succeeded, producing 1caf06d99cefdad51b8774da1ffa48037ed72342
[2021-06-24T08:46:19.699Z] Checking out Revision 1caf06d99cefdad51b8774da1ffa48037ed72342 (PR-26463)
[2021-06-24T08:46:20.741Z] Commit message: "Update http-endpoint.asciidoc"
[2021-06-24T08:46:20.742Z] Cleaning workspace
[2021-06-24T08:46:19.669Z]  > git remote # timeout=10
[2021-06-24T08:46:19.672Z]  > git config --get remote.origin.url # timeout=10
[2021-06-24T08:46:19.676Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-24T08:46:19.679Z]  > git merge 0869d91a08725eeeb7f10045b6fb7a3bdcee29a8 # timeout=10
[2021-06-24T08:46:19.690Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-06-24T08:46:19.701Z]  > git config core.sparsecheckout # timeout=10
[2021-06-24T08:46:19.706Z]  > git checkout -f 1caf06d99cefdad51b8774da1ffa48037ed72342 # timeout=15
[2021-06-24T08:46:20.744Z]  > git rev-parse --verify HEAD # timeout=10
[2021-06-24T08:46:20.747Z] Resetting working tree
[2021-06-2 [...]

2021-06-24 12:05 UTC, jsoriano requested changes
Good catch! But the change should be applied in master first, could you please rebase the PR on master? Thanks!

2021-06-24 12:05 UTC, jsoriano commented on libbeat/docs/http-endpoint.asciidoc
> +  "beat": "heartbeat",
Umm, I think this should be `{beatname_lc}`, so this is replaced by the lowercased name of the actual beat on each guide.
```suggestion
  "beat": "{beatname_lc}",
```

2021-06-24 12:05 UTC, jsoriano commented
You will also need to [sign the CLA](https://www.elastic.co/contributor-agreement), please.

2021-06-24 12:07 UTC, jsoriano commented
/test

2021-06-24 12:07 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2021-07-28 22:10 UTC, bmorelli25 commented
Replaced by https://github.com/elastic/beats/pull/27117.

2021-07-28 22:10 UTC, closed without merging