Update change-index-name.asciidoc
elastic/beats pull request #26703
Opened 2021-07-05 07:23 UTC by insukcho

The current doc can be misread like the user need to visit the ILM page to learn how to change the index name. But the TIP is saying they should visit the ILM page and change the index name in the existing ILM policy with the new index name. Need to be more clear sentance. Feel free to suggest better comments.

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-07-05 07:44 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26703/detail/PR-26703/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26703/detail/PR-26703/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26703/detail/PR-26703/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26703/detail/PR-26703/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_26703.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #26703 opened`



* Start Time: 2021-07-05T07:23:26.480+0000


* Duration: 21 min 56 sec


* Commit: d1ef850d7313978135e5ccee1b0c8ccbaa3b8fed




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-26703/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :grey_exclamation: Flaky test report
No test was executed to be analysed.



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-07-06 10:51 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2021-08-13 18:01 UTC, dedemorton requested changes
Minor correction to remove phrase that seems unnecessary. Thanks for fixing this!

2021-08-13 18:01 UTC, dedemorton commented on libbeat/docs/howto/change-index-name.asciidoc
> +management, you need to change the index name in the ILM policy to new one.
```suggestion
management, you need to change the index name in the ILM policy.
```

2021-08-19 03:38 UTC, insukcho commented
@dedemorton Thank you for the suggestion. Just applied ;)

2021-08-19 15:19 UTC, bmorelli25 approved these changes
Thanks, Insuk! I'll get this cherry-picked to master and backport

2021-08-19 15:21 UTC, merged