run processors, defined in the block overriding the input, before the module.
elastic/beats pull request #26862
Opened 2021-07-13 11:07 UTC by mjmbischoff

## What does this PR do?

Changing the order of processors when defining processors on the (overriding) input block, to be run before the module.

## Why is it important?

When overriding the input on a module https://www.elastic.co/guide/en/beats/filebeat/7.13/advanced-settings.html .
https://www.elastic.co/guide/en/beats/filebeat/7.13/defining-processors.html#where-valid describes how it's a valid location but is ambiguous about the order, other then that it runs after the input. This change makes the processors defined there, run right after the input, thus before the module. This is useful in the case where input is overiden as the structure might have changed due to using a different input/transport. 

For example, when adding a buffer to ingest pipeline, kafka is often introduced. Currently even if json is posted to kafka it is read back as json (escaped) string into the message field. Due to the modules having a log input with https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json setup this breaks / disallows kafka being used. As it iether expects json fields as root or json parsed and placed under the json field.  

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] I have made corresponding changes to the documentation
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] Discuss breaking change
- [ ] Discuss adding processor at module level to reintroduce old behaviour

## How to test this PR locally

## Related issues

- Relates #26833

## Use cases

As one of the reasons to introduce a buffer in the ingest pipeline is to allow quick draining of the logsources / reduce backpressure. parsing and processing is best done after the buffer. A beat / elastic agent -> kafka -> filebeat -> es is a preferred setup where logstash is not needed.

In other causes where a different intermediate is introduced this change will also help to smooth out any structural changes introduced by going through that intermediate. (for example syslog server or logging to s3 bucket.)

2021-07-13 11:14 UTC, mjmbischoff commented
Note that this PR reduces the need for https://github.com/elastic/beats/pull/26833 as we could, after this is merged, use https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html processor. https://github.com/elastic/beats/pull/26833 is more efficient, but pointing out how this PR introduces flexibility.

2021-07-13 12:44 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26862/detail/PR-26862/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26862/detail/PR-26862/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26862/detail/PR-26862/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-26862/detail/PR-26862/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_26862.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-07-13T10:57:37.960Z&rangeTo=2021-07-13T11:17:37.960Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=ab447de53e8f38cc1d1608ff254e1d04&transactionId=8c74f20a82c28f49)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-07-13T11:07:37.960+0000


* Duration: 96 min 9 sec


* Commit: a798efa367527303d326d4678114daab1cd9ff3a



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 14867  |
| Skipped      | 2312 |
| Total        | 17179   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-26862/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-26862/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 14867  |
| Skipped      | 2312 |
| Total        | 17179   |



</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-08-05 17:05 UTC, kvch requested changes
Same as https://github.com/elastic/beats/pull/27154#pullrequestreview-723599718

2021-08-23 00:04 UTC, elasticmachine commented
Pinging @elastic/agent (Team:Agent)

2021-09-22 06:49 UTC, mjmbischoff commented
Yes still relevant, as it allows us to be compatible with a lot more products / log sources / setups. Allowing us to correct for any small things introduced by these(99% compatible, additional transport step introducing some form of wrapping).

2021-11-21 13:46 UTC, closed without merging