[ecs] Update fields.ecs.yml to 1.12
elastic/beats pull request #27770
Opened 2021-09-07 11:01 UTC by marc-gr

## What does this PR do?

- [x] fields.ecs.yml to ECS 1.12.0-dev
- [ ] bump ecs.version in configs for modules that don't require changes.

## Why is it important?

- keep up to date with ECS changes
- allows modules to use new ECS fields

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

```
cd filebeat && mage pythonIntegTest
cd x-pack/filebeat && mage pythonIntegTest
```

2021-09-07 11:01 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-09-07 15:05 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.'}
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27770/detail/PR-27770/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27770/detail/PR-27770/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27770/detail/PR-27770/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27770/detail/PR-27770/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-07T10:51:38.153Z&rangeTo=2021-09-07T11:11:38.153Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=7579b3686814cb5cb780bd22668d81ed&transactionId=a0d21fd1b8d08a2a)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-09-07T11:01:38.153+0000


* Duration: 243 min 24 sec


* Commit: f05e2202aa5b671f65609adf2acb8db0124db6e6



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 549  |
| Passed       | 17727  |
| Skipped      | 1469 |
| Total        | 19745   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-27770/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-27770/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![549](https://img.shields.io/badge/549%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27770/detail/PR-27770/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `Build&Test / filebeat-module-compat-7.11 / test_fileset_file_000_elasticsearch – filebeat.tests.system.test_modules.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed: Timeout >90.0s 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 a = (<test_modules.Test testMethod=test_fileset_file_000_elasticsearch>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../build/ve/docker/lib/python3.7/site-packages/parameterized/parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/system/test_modules.py:99: in test_fileset_file
    cfgfile=cfgfile)
tests/system/test_modules.py:150: in run_on_file
    bufsize=0).wait()
/usr/lib/python3.7/subprocess.py:990: in wait
    return self._wait(timeout=timeout)
/usr/lib/python3.7/subprocess.py:1624: in _wait
    (pid, sts) = self._try_wait(0)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x7f25c6074550>, wait_flags = 0

    def _try_wait(self, wait_flags):
        """All callers to this function MUST hold self._waitpid_lock."""
        try:
>           (pid, sts) = os.waitpid(self.pid, wait_flags)
E           Failed: Timeout >90.0s

/usr/lib/python3.7/subprocess.py:1582: Failed 
 ```
</p></details>
</ul>
    
##### `Build&Test / filebeat-module-compat-7.11 / test_fileset_file_001_elasticsearch – filebeat.tests.system.test_modules.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds. 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 a = (<test_modules.Test testMethod=test_fileset_file_001_elasticsearch>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../build/ve/docker/lib/python3.7/site-packages/parameterized/parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/system/test_modules.py:99: in test_fileset_file
    cfgfile=cfgfile)
tests/system/test_modules.py:159: in run_on_file
    self.wait_until(lambda: self.es.indices.exists(self.index_name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_modules.Test testMethod=test_fileset_file_001_elasticsearch>
cond = <function Test.run_on_file.<locals>.<lambda> at 0x7f25c5fb6950>
max_timeout = 10, poll_interval = 0.1, name = 'cond'

    def wait_until(self, cond, max_timeout=10, poll_interval=0.1, name="cond"):
        """
        Waits until the cond function returns true,
        or until the max_timeout is reached. Calls the cond
        function every poll_interval seconds.
    
        If the max_timeout is reached before cond() returns
        true, an exception is raised.
        """
        start = datetime.now()
        while not cond():
            if datetime.now() - start > timedelta(seconds=max_timeout):
                raise TimeoutError("Timeout waiting for '{}' to be true. ".format(name) +
>                                  "Waited {} seconds.".format(max_timeout))
E               beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

../libbeat/tests/system/beat/beat.py:363: TimeoutError 
 ```
</p></details>
</ul>
    
##### `Build&Test / filebeat-module-compat-7.11 / test_fileset_file_002_elasticsearch – filebeat.tests.system.test_modules.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds. 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 a = (<test_modules.Test testMethod=test_fileset_file_002_elasticsearch>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../build/ve/docker/lib/python3.7/site-packages/parameterized/parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/system/test_modules.py:99: in test_fileset_file
    cfgfile=cfgfile)
tests/system/test_modules.py:159: in run_on_file
    self.wait_until(lambda: self.es.indices.exists(self.index_name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_modules.Test testMethod=test_fileset_file_002_elasticsearch>
cond = <function Test.run_on_file.<locals>.<lambda> at 0x7f25c60e0268>
max_timeout = 10, poll_interval = 0.1, name = 'cond'

    def wait_until(self, cond, max_timeout=10, poll_interval=0.1, name="cond"):
        """
        Waits until the cond function returns true,
        or until the max_timeout is reached. Calls the cond
        function every poll_interval seconds.
    
        If the max_timeout is reached before cond() returns
        true, an exception is raised.
        """
        start = datetime.now()
        while not cond():
            if datetime.now() - start > timedelta(seconds=max_timeout):
                raise TimeoutError("Timeout waiting for '{}' to be true. ".format(name) +
>                                  "Waited {} seconds.".format(max_timeout))
E               beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.

../libbeat/tests/system/beat/beat.py:363: TimeoutError 
 ```
</p></details>
</ul>
    
##### `Build&Test / filebeat-module-compat-7.11 / test_fileset_file_003_elasticsearch – filebeat.tests.system.test_modules.Test`


<ul>
<details><summary [...]

2021-09-20 17:16 UTC, andrewkroh requested changes
This changes `message` to use `match_only_text` which was introduced in 7.14. I think libbeat should fall-back to `text` if that type is not available. We added something similar for `wildcard` at https://github.com/elastic/beats/blob/7a49ca15950fed297aac20d3d96fe605db65164b/libbeat/template/processor.go#L90-L96.

2021-09-29 14:01 UTC, leehinman approved these changes
LGTM

2021-09-29 14:28 UTC, andrewkroh commented on CHANGELOG.next.asciidoc
> +- Add fallback for `match_only_text`. {pull}27770[27770]
Could you add a bit more description here. Like "Fields mapped as `match_only_text` will automatically fallback to a `text` mapping when using Elasticsearch versions that do not support `match_only_text`."

2021-09-29 14:28 UTC, andrewkroh approved these changes

2021-10-01 12:50 UTC, mdelapenya approved these changes
From E2E stand point, I'd say this PR is OK, as the errors we are seeing in the build history are considered flaky

2021-10-01 13:34 UTC, merged