[Filebeat] GA checkpoint module
elastic/beats pull request #27814
Opened 2021-09-08 19:59 UTC by leehinman

## What does this PR do?

GA checkpoint module

- release to ga
- remove beta from docs

## Why is it important?

sync with integration 

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates elastic/integrations#1562

2021-09-08 20:02 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-09-08 20:14 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27814/detail/PR-27814/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27814/detail/PR-27814/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27814/detail/PR-27814/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27814/detail/PR-27814/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_27814.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-08T19:49:34.804Z&rangeTo=2021-09-08T20:09:34.804Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=4e2efc4ab9602b877e886833301b0a15&transactionId=e5ef2666ab5cbf64)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-09-08T19:59:34.804+0000


* Duration: 14 min 23 sec


* Commit: 3dc07a124a0ef95b1d176eb2d27263f1678a9964




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-27814/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27814/detail/PR-27814/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `x-pack/filebeat-lint - make -C x-pack/filebeat check;make -C x-pack/filebeat update;make -C filebe`
<ul>
<li>Took 3 min 43 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27814/runs/1/steps/1055/log/?start=0">here</a></li>
<li>Description: <code>make -C x-pack/filebeat check;make -C x-pack/filebeat update;make -C filebeat check;make -C filebeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `List files to upload`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27814/runs/1/steps/1150/log/?start=0">here</a></li>
<li>Description: <code>ls -l src/github.com/elastic/beats/build/system-tests-*.tar.gz</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27814/runs/1/steps/1058/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-09-08T20:13:09.390Z] make: Leaving directory '/var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/src/github.com/elastic/beats/filebeat'
[2021-09-08T20:13:09.589Z] Timeout set to expire in 5 min 0 sec
[2021-09-08T20:13:09.925Z] Cleaning up /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050
[2021-09-08T20:13:09.925Z] Change ownership of all files inside the specific folder from root/root to current user/group
[2021-09-08T20:13:09.925Z] ++ id -u
[2021-09-08T20:13:09.925Z] ++ id -g
[2021-09-08T20:13:09.925Z] + docker run -v /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050:/beat alpine:3.4 sh -c 'find /beat -user 0 -exec chown -h 1171:1172 {} \;'
[2021-09-08T20:13:09.925Z] Unable to find image 'alpine:3.4' locally
[2021-09-08T20:13:10.500Z] 3.4: Pulling from library/alpine
[2021-09-08T20:13:10.761Z] c1e54eec4b57: Pulling fs layer
[2021-09-08T20:13:11.023Z] c1e54eec4b57: Verifying Checksum
[2021-09-08T20:13:11.023Z] c1e54eec4b57: Download complete
[2021-09-08T20:13:11.288Z] c1e54eec4b57: Pull complete
[2021-09-08T20:13:11.288Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
[2021-09-08T20:13:11.288Z] Status: Downloaded newer image for alpine:3.4
[2021-09-08T20:13:13.212Z] + set -e
[2021-09-08T20:13:13.212Z] + echo 'Change permissions with write access of all files inside the specific folder'
[2021-09-08T20:13:13.212Z] Change permissions with write access of all files inside the specific folder
[2021-09-08T20:13:13.212Z] + chmod -R +w /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050
[2021-09-08T20:13:13.880Z] Running in /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/src/github.com/elastic/beats/build
[2021-09-08T20:13:14.207Z] + rm -rf ve
[2021-09-08T20:13:14.207Z] + find . -type d -name vendor -exec rm -r {} ;
[2021-09-08T20:13:14.583Z] + python .ci/scripts/pre_archive_test.py
[2021-09-08T20:13:14.844Z] Copy ./x-pack/filebeat/build into build/x-pack/filebeat/build
[2021-09-08T20:13:14.844Z] Copy ./filebeat/build into build/filebeat/build
[2021-09-08T20:13:14.874Z] Running in /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/src/github.com/elastic/beats/build
[2021-09-08T20:13:14.919Z] Recording test results
[2021-09-08T20:13:15.705Z] None of the test reports contained any result
[2021-09-08T20:13:15.705Z] [Checks API] No suitable checks publisher found.
[2021-09-08T20:13:16.054Z] + tar --version
[2021-09-08T20:13:16.422Z] + tar --exclude=test-build-artifacts-x-pack-filebeat-lint-tgz -czf test-build-artifacts-x-pack-filebeat-lint-tgz .
[2021-09-08T20:13:17.228Z] + gsutil --version
[2021-09-08T20:13:20.594Z] Masking supported pattern matches of $FILE_CREDENTIAL
[2021-09-08T20:13:21.047Z] + gcloud auth activate-service-account --key-file ****
[2021-09-08T20:13:21.990Z] Activated service account credentials for: [beats-ci-gcs-plugin@elastic-ci-prod.iam.gserviceaccount.com]
[2021-09-08T20:13:22.626Z] + gsutil -m -q cp -a public-read test-build-artifacts-x-pack-filebeat-lint-tgz gs://beats-ci-temp/Beats/beats/PR-27814-1
[2021-09-08T20:13:25.181Z] + gvm 1.16.6
[2021-09-08T20:13:25.181Z] export GOROOT="/var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/.gvm/versions/go1.16.6.linux.amd64"
[2021-09-08T20:13:25.181Z] export PATH="/var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/.gvm/versions/go1.16.6.linux.amd64/bin:$PATH"
[2021-09-08T20:13:25.625Z] + go get -u github.com/magefile/mage
[2021-09-08T20:13:26.296Z] + go get -u github.com/elastic/go-licenser
[2021-09-08T20:13:26.699Z] + go get -u golang.org/x/tools/cmd/goimports
[2021-09-08T20:13:27.273Z] go get: upgraded golang.org/x/tools v0.1.1 => v0.1.5
[2021-09-08T20:13:27.678Z] + go get -u github.com/jstemmer/go-junit-report
[2021-09-08T20:13:27.837Z] Running in /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/src/github.com/elastic/beats/x-pack/filebeat
[2021-09-08T20:13:28.175Z] + mage packageSystemTests
[2021-09-08T20:13:36.331Z] >> there are no system test files under build/system-tests/run
[2021-09-08T20:13:36.455Z] Running in /var/lib/jenkins/workspace/PR-27814-1-ce67dc16-1875-4fcb-8b5d-d9a4cef45050/src/github.com/elastic/beats/src/github.com/elastic/beats
[2021-09-08T20:13:36.802Z] + ls -l src/github.com/elastic/beats/build/system-tests-*.tar.gz
[2021-09-08T20:13:36.802Z] ls: cannot access 'src/github.com/elastic/beats/build/system-tests-*.tar.gz': No such file or directory
[2021-09-08T20:13:36.881Z] ERROR: [...]

2021-09-14 14:49 UTC, adriansr requested changes

2021-09-14 14:49 UTC, adriansr commented on CHANGELOG.next.asciidoc
Extra space

2021-09-15 14:00 UTC, leehinman commented on CHANGELOG.next.asciidoc
Fixed.  Thanks.

2021-09-21 16:14 UTC, adriansr approved these changes

2021-09-21 17:37 UTC, merged