[Elastic Agent] Golden files for program tests
elastic/beats pull request #27862
Opened 2021-09-10 13:24 UTC by ruflin

Currently it seems the expected config files for each program were manually generated. This makes adding a new test cumbersome and in case of small changes it means adjusting many files.

This changes the test that it is possible to run with `go test . -generate` and new golden files are generated. Ideally it also means most of the additional tests become obsolete like how many program files should be generated. To make sure no left over files exist, on -generate all the generated files are first cleaned up.

NOTE: This PR is not complete yet, for example removal of old files is missing and cleanup of generated files. I wanted to discuss the approach first before going further.

2021-09-10 13:24 UTC, ruflin commented
@blakerouse @michalpristas Would be great to get your feedback on this idea.

2021-09-10 13:37 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27862/detail/PR-27862/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27862/detail/PR-27862/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27862/detail/PR-27862/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27862/detail/PR-27862/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_27862.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-10T13:14:15.693Z&rangeTo=2021-09-10T13:34:15.693Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=7654b8222ac0bcfb2879689fc5fca110&transactionId=41192b2b28af807e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-09-10T13:24:15.693+0000


* Duration: 13 min 32 sec


* Commit: 95693824fb0e359fa8e334ca290c807a41a05bf6




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-27862/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-27862/detail/PR-27862/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `x-pack/elastic-agent-lint - make -C x-pack/elastic-agent check;make -C x-pack/elastic-agent update;`
<ul>
<li>Took 1 min 21 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27862/runs/1/steps/1039/log/?start=0">here</a></li>
<li>Description: <code>make -C x-pack/elastic-agent check;make -C x-pack/elastic-agent update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `List files to upload`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27862/runs/1/steps/1135/log/?start=0">here</a></li>
<li>Description: <code>ls -l src/github.com/elastic/beats/build/system-tests-*.tar.gz</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-27862/runs/1/steps/1043/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-09-10T13:35:23.314Z] >> check: Checking source code for common problems
[2021-09-10T13:36:02.130Z] Error: some files are not up-to-date. Run 'make update' then review and commit the changes. Modified: [x-pack/elastic-agent/pkg/agent/program/program_test.go]
[2021-09-10T13:36:02.131Z] ../../dev-tools/make/mage.mk:21: recipe for target 'check' failed
[2021-09-10T13:36:02.131Z] make: *** [check] Error 1
[2021-09-10T13:36:02.131Z] make: Leaving directory '/var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/src/github.com/elastic/beats/x-pack/elastic-agent'
[2021-09-10T13:36:02.331Z] Timeout set to expire in 5 min 0 sec
[2021-09-10T13:36:02.663Z] Cleaning up /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960
[2021-09-10T13:36:02.663Z] Change ownership of all files inside the specific folder from root/root to current user/group
[2021-09-10T13:36:02.663Z] ++ id -u
[2021-09-10T13:36:02.663Z] ++ id -g
[2021-09-10T13:36:02.663Z] + docker run -v /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960:/beat alpine:3.4 sh -c 'find /beat -user 0 -exec chown -h 1171:1172 {} \;'
[2021-09-10T13:36:02.663Z] Unable to find image 'alpine:3.4' locally
[2021-09-10T13:36:03.235Z] 3.4: Pulling from library/alpine
[2021-09-10T13:36:03.497Z] c1e54eec4b57: Pulling fs layer
[2021-09-10T13:36:03.760Z] c1e54eec4b57: Download complete
[2021-09-10T13:36:03.760Z] c1e54eec4b57: Pull complete
[2021-09-10T13:36:04.021Z] Digest: sha256:b733d4a32c4da6a00a84df2ca32791bb03df95400243648d8c539e7b4cce329c
[2021-09-10T13:36:04.021Z] Status: Downloaded newer image for alpine:3.4
[2021-09-10T13:36:05.940Z] + set -e
[2021-09-10T13:36:05.940Z] + echo 'Change permissions with write access of all files inside the specific folder'
[2021-09-10T13:36:05.940Z] Change permissions with write access of all files inside the specific folder
[2021-09-10T13:36:05.940Z] + chmod -R +w /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960
[2021-09-10T13:36:07.418Z] Running in /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/src/github.com/elastic/beats/build
[2021-09-10T13:36:07.752Z] + rm -rf ve
[2021-09-10T13:36:07.752Z] + find . -type d -name vendor -exec rm -r {} ;
[2021-09-10T13:36:08.124Z] + python .ci/scripts/pre_archive_test.py
[2021-09-10T13:36:08.151Z] Running in /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/src/github.com/elastic/beats/build
[2021-09-10T13:36:08.195Z] Recording test results
[2021-09-10T13:36:08.933Z] None of the test reports contained any result
[2021-09-10T13:36:08.933Z] [Checks API] No suitable checks publisher found.
[2021-09-10T13:36:09.283Z] + tar --version
[2021-09-10T13:36:09.656Z] + tar --exclude=test-build-artifacts-x-pack-elastic-agent-lint-tgz -czf test-build-artifacts-x-pack-elastic-agent-lint-tgz .
[2021-09-10T13:36:10.159Z] + gsutil --version
[2021-09-10T13:36:13.506Z] Masking supported pattern matches of $FILE_CREDENTIAL
[2021-09-10T13:36:14.009Z] + gcloud auth activate-service-account --key-file ****
[2021-09-10T13:36:14.953Z] Activated service account credentials for: [beats-ci-gcs-plugin@elastic-ci-prod.iam.gserviceaccount.com]
[2021-09-10T13:36:15.337Z] + gsutil -m -q cp -a public-read test-build-artifacts-x-pack-elastic-agent-lint-tgz gs://beats-ci-temp/Beats/beats/PR-27862-1
[2021-09-10T13:36:17.894Z] + gvm 1.16.6
[2021-09-10T13:36:17.894Z] export GOROOT="/var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/.gvm/versions/go1.16.6.linux.amd64"
[2021-09-10T13:36:17.894Z] export PATH="/var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/.gvm/versions/go1.16.6.linux.amd64/bin:$PATH"
[2021-09-10T13:36:18.349Z] + go get -u github.com/magefile/mage
[2021-09-10T13:36:19.020Z] + go get -u github.com/elastic/go-licenser
[2021-09-10T13:36:19.686Z] + go get -u golang.org/x/tools/cmd/goimports
[2021-09-10T13:36:20.260Z] go get: upgraded golang.org/x/tools v0.1.1 => v0.1.5
[2021-09-10T13:36:20.666Z] + go get -u github.com/jstemmer/go-junit-report
[2021-09-10T13:36:20.825Z] Running in /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/src/github.com/elastic/beats/x-pack/elastic-agent
[2021-09-10T13:36:21.171Z] + mage packageSystemTests
[2021-09-10T13:36:27.775Z] >> there are no system test files under build/system-tests/run
[2021-09-10T13:36:27.902Z] Running in /var/lib/jenkins/workspace/PR-27862-1-2fc24ffc-4cbf-4c84-a5c2-77d3513d3960/src/github.com/elastic/beats/src/github.com/elastic/beats
[2021-09-10T13:36:28.248Z] + ls -l src/github.com/elastic/beats/build/syst [...]

2021-09-10 14:11 UTC, ruflin commented on x-pack/elastic-agent/pkg/agent/program/program_test.go
> +		generatedFiles, err := filepath.Glob(filepath.Join("testdata", "*.generated.yml"))
Better name? Maybe .golden.yml?

2021-09-10 17:50 UTC, blakerouse requested changes
Some what confused on what you are changing here? It seems like you are changing the code to generated the expected results of the tests. To me this will negate the point of the tests. The tests are ensuring that the inputs, match the outputs. The outputs are hand written to ensure that the output is what is expected with the given input.

2021-09-13 06:24 UTC, ruflin commented
The test files are only generated if the `-generate` flag is used. Otherwise I agree it would defy the purpose of the tests completely. This is known under [golden files test](https://medium.com/@jarifibrahim/golden-files-why-you-should-use-them-47087ec994bf) (I picked the first Google result ;-) ).

The problem with the current approach is that it is really cumbersome to add new examples. With the new approach, the first time the generate script can be run and the output can be reviewed. If in the future there is a "mass change" needed, this also make it easier. The important part is that any time the `-generate` flag is used, the diffs of the files must be carefully reviewed to make sure it is part of the expected change. But that is what a PR review is for.

2021-09-13 06:37 UTC, ruflin commented
To make this PR easier to review I did not change the old tests and kept them as is. I think we can remove some of these as the new ones replace part of the old ones that have at least one program but we can do this in a follow up PR.

Marking this as ready for review.

2021-09-13 06:37 UTC, elasticmachine commented
Pinging @elastic/agent (Team:Agent)

2021-09-16 13:47 UTC, blakerouse approved these changes
Thanks for keeping the old tests. I think its good so we don't cause any regressions, until we know for sure this will cover those old tests.

2021-09-20 06:16 UTC, merged