Allow worker or workers for output config
elastic/beats pull request #28726
Opened 2021-10-29 22:22 UTC by leehinman

## What does this PR do?

Allows `workers` or `worker` to be used to set the number of output
workers.  The greater of the two will be used if both are present.

## Why is it important?

We have had multiple performance issues where `workers` was used
instead of `worker`.  `workers` is not an error and is very hard to
see.  The plural is more natural.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

``` bash
cd libbeat\outputs
go test
```

2021-10-29 22:23 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-10-29 22:28 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28726/detail/PR-28726/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28726/detail/PR-28726/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28726/detail/PR-28726/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28726/detail/PR-28726/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-10-29T22:12:32.007Z&rangeTo=2021-10-29T22:32:32.007Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=9ba593f2dbeb681c2f6e8811a4c18a80&transactionId=44eb41500e2f62f9)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `Aborted from #2`


* Start Time: 2021-10-29T22:22:32.007+0000


* Duration: 6 min 10 sec


* Commit: 55e58c65d3c79ec5b2fbbb2102949732d2e2541a




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:


- `/test` : Re-trigger the build.

- `/package` : Generate the packages and run the E2E tests.

- `/beats-tester` : Run the installation tests with beats-tester.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-02 12:44 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane  (Team:Elastic-Agent-Data-Plane)

2021-11-03 15:51 UTC, ruflin requested changes
I don't think we should start to introduce aliases as it adds unnecessary complexity to the code. Even though I likely agree workers is the better term I not convinced it is enough to add complexity to the code. We change workers today, few others tomorrow. Also I think https://github.com/elastic/beats/pull/28726/files#diff-1b772717f8160cf8eedecb3287d304a0f8c11b1d48eae91c82990b9204deacb3R42 is very surprising for a user.

If we decide not to change it, how do we solve the customer issue then that `workers` is used? The bigger issue is config validation. So far we are only able to validate configs we know about. Any key that is used we do not support, we just skip it.

What if we would introduce a mechanism to catch config names that we know users are likely to use but don't work? The workers example is great. If a user types in `workers`, the Beat should stop and log out: `Did you mean "worker" instead of "workers"`? It is a mechanism that we could use in more places then just here.

2021-11-08 13:26 UTC, kvch commented
I agree with @ruflin on not merging these changes.

The root cause of the problem is we do not have proper configuration validation. This PR only fixes one of the many symptoms of the issue. Thus, it is not sustainable, it does not solve the problem in the long run. We should treat the cause, not the symptom. 

In the short term, we could extend the checks of the `processors` package to new features. In that package, developers can define allowed keywords, mutually exclusive keywords, etc. Then the configuration is checked against the fields: https://github.com/elastic/beats/blob/master/libbeat/processors/checks/checks.go#L29
Each plugin can register checks like this: https://github.com/elastic/beats/blob/master/libbeat/processors/actions/add_fields.go#L42-L44

In the long run, maybe we could make the existing checker more powerful or we could adopt a YAML schema validator. But it is something we should address in the future as it is also important for Fleet/Agent.

2021-11-09 20:28 UTC, leehinman commented
@ruflin @kvch Thanks for taking the time to review and the suggestions.  I'll close this PR and see if I can come up with a better change to `ucfg` that flags misspellings.

2021-11-09 20:28 UTC, closed without merging