WiP: multiple kafka outputs for different clientId
elastic/beats pull request #28859
Opened 2021-11-07 16:12 UTC by atercattus

This PR is WiP now. I'm interested to hear your opinion.

## What does this PR do?
This feature allows setting the clientID dynamically by using a format string to access any event field. It works the same as a topic selector.
A new Kafka client will be created for each calculated `client_id` value.

## Why is it important?
When we use filebeat in multi-tenant k8s nodes we need to separate different pods by specified clientID for each of them.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
Use configuration file with dynamic `client_id` value.

2021-11-07 16:18 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28859/detail/PR-28859/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28859/detail/PR-28859/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28859/detail/PR-28859/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-28859/detail/PR-28859/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-07T16:02:35.733Z&rangeTo=2021-11-07T16:22:35.733Z&transactionName=Beats/beats/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=0d2f74b5681bbad6625b20204eda0408&transactionId=9eeb09cc3a37b0df)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-11-07T16:12:35.733+0000


* Duration: 6 min 1 sec


* Commit: 2e3b8337099c2beb63aa6187d253fe9dad4de3e7




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:


- `/test` : Re-trigger the build.

- `/package` : Generate the packages and run the E2E tests.

- `/beats-tester` : Run the installation tests with beats-tester.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-10 10:27 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-11-25 06:02 UTC, atercattus commented
Up

2021-12-07 06:39 UTC, AectannArd commented
@faec 
@kvch 
could you please take a look at this so that we go on with adding this useful functionality to the upstream?
just for a notice - the feature is battle-tested in our production environments serving as log shipper for multi-tenant k8s clusters for the last 3 months and it works correctly.

2021-12-07 08:24 UTC, quasilyte commented
If this PR is ready for review, I would suggest removing the WIP prefix from the title.
Some people interpret WIP as "do not review yet".

2021-12-07 14:48 UTC, kvch commented
jenkins run tests

2021-12-07 14:49 UTC, kvch commented
@faec Could you please review this PR?

2021-12-21 14:27 UTC, AectannArd commented
UP!
@faec could you please take a look.

2022-01-17 07:12 UTC, AectannArd commented
@faec @kvch 
Any update on this issue?

2022-02-09 04:44 UTC, atercattus commented
@faec @kvch
Look at this pr, please.

2022-02-10 15:12 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane  (Team:Elastic-Agent-Data-Plane)

2022-02-11 16:17 UTC, cmacknz commented on libbeat/outputs/kafka/docs/kafka.asciidoc
> +You can set the clientID dynamically by using a format string to access any event field. For example, this configuration uses a custom field, `kubernetes.pod.annotations.tenant_name`, to set the topi
It's not clear why you would want multiple clients, in this case why would the topic selector not be enough?

2022-02-11 16:19 UTC, cmacknz commented
Hi @atercattus, sorry for the delay in reviewing this. 

I want to make sure I understand what the motivation is for having multiple clients in a single beat is before looking at merging this.

To merge and maintain this, we are going to need some tests for the multi-client you have added.

2022-02-11 16:22 UTC, cmacknz requested changes
Should have requested changes with my previous comment. We need to understand what the benefit is and then add test coverage.

2022-03-02 15:14 UTC, jlind23 commented
Closing for now until further updates from @atercattus

2022-03-02 15:14 UTC, closed without merging