Fix gcp metrics metricset apply aligner to all metric_types (#29513)
elastic/beats pull request #29514
Opened 2021-12-19 04:41 UTC by kwinstonix

Type of change
- Bug

## Why is it important?

* Each aligner is applied to all metric types, that will incur more Google monitoring API calls and more costs.

* There are many unnecessary metrics with wrong aligner in MetricBeat events.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

see issue #29513

## Related issues

- Closes #29513  

## Screenshots

It works as expected. There are only two metrics in events.

![image](https://user-images.githubusercontent.com/12824991/146663939-966e1eed-154d-4d18-8ac9-fdedc17604a0.png)

2021-12-19 04:48 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29514/detail/PR-29514/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29514/detail/PR-29514/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29514/detail/PR-29514/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29514/detail/PR-29514/2//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-19T04:33:38.217Z&rangeTo=2021-12-19T04:53:38.217Z&transactionName=Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=b2c8395cf29e3e56ee132100dc9fb4a1&transactionId=12a0acb3f477c26d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-12-19T04:43:38.217+0000


* Duration: 5 min 46 sec


* Commit: 33da63fffa6dec80c196ff92e79109af82e59724




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-19 04:49 UTC, kwinstonix commented
/test

2021-12-21 11:58 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-12-21 16:58 UTC, endorama requested changes

2021-12-21 17:07 UTC, endorama commented
Hi @kwinstonix, thank you for the contribution! 

I reviewed the code, and I would prefer another approach. The code is already complex to follow so I would prefer to perform the filtering not within the function itself; this would simplify the logic and reduce coupling.

My proposal would be to add this code:
```go
        // see https://github.com/elastic/beats/pull/29514
        metricsToCollect := map[string]metricMeta{}
        for _, v := range sdc.MetricTypes {
            metricsToCollect[sdc.AddPrefixTo(v)] = m.metricsMeta[sdc.AddPrefixTo(v)]
        }

        responses, err := m.requester.Metrics(ctx, sdc.ServiceName, metricsToCollect, sdc.Aligner)
```

in `x-pack/metricbeat/module/gcp/metrics/metricset.go:177`. This requires changes to `Metrics()` signature but help to streamline the method, as it allow a simpler execution flow. The new signature would be:
```go
func (r *metricsRequester) Metrics(ctx context.Context, serviceName string, 
			metricsToCollect map[string]metricMeta, aligner string) ([]timeSeriesWithAligner, error) {
	// ...
}
```

This way filtering happens in `Fetch()` function and `Metrics()` is unaware of the logic behind it. The new signature also removes dependency on `sdc` variable reducing coupling.

What do you think? (I tried a different approach first, deleting from `metricsMeta` within `Metrics()` all unneeded metrics, but Golang doesn't have built in ways to filter a map and I don't think adding multiple for loops helps with clarity)

2021-12-22 01:40 UTC, kwinstonix commented
@endorama , Yes, that is a better solution.  We should keep `Metrics` method simple.

2021-12-22 01:42 UTC, kwinstonix commented on CHANGELOG.next.asciidoc
> +- Fix s3 input when there is a blank line in the log file. {pull}25357[25357]
ok , I will rebase again.

2021-12-22 09:08 UTC, endorama commented
/test

2021-12-27 10:16 UTC, endorama approved these changes
Tests are green, I added a comment to explain why the filtering is happening (as from the code is quite obscure) but this looks good to me.

2021-12-27 10:16 UTC, endorama commented on x-pack/metricbeat/module/gcp/metrics/metricset.go
> +		metricsToCollect := map[string]metricMeta{}
```suggestion
		// m.metricsMeta contains all metrics to be collected, not just the one in the current MetricsConfig.
		// this loop filters the metrics in metricsMeta so requester.Metrics can collect only the appropriate
		// ones.
		// See https://github.com/elastic/beats/pull/29514
		metricsToCollect := map[string]metricMeta{}
```

2021-12-28 09:55 UTC, merged

2021-12-28 09:55 UTC, endorama commented
@kwinstonix thank you for your contribution!