Add the Elastic product origin header when talking to Elasticsearch or Kibana.
elastic/beats pull request #29966
Opened 2022-01-24 15:00 UTC by cmacknz

## What does this PR do?

Adds the x-elastic-product-origin header when communicating with Elasticsearch or Kibana.

## Why is it important?

If Elasticsearch deprecates an API we use in the future, this header will prevent Kibana from presenting the warning to the user. It will also tag the Elasticsearch deprecation log message with the header value to more easily attribute deprecated API usage to products

Note that there is no known usage of deprecated Elasticsearch APIs in beats currently.

## Checklist

- [ x ] My code follows the style guidelines of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [ x ] I have added tests that prove my fix is effective or that my feature works
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## How to test this PR locally

Run any beat and inspect the headers attached to requests. For example, `filebeat test output` will make a request that should have the new headers attached.

I ran filebeat (as an arbitrary choice) locally and inspected the HTTP requests to Elasticsearch with Wireshark to confirm the expected header was attached. I haven't exhaustively tested all beats, or all HTTP interactions.

2022-01-24 15:00 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane  (Team:Elastic-Agent-Data-Plane)

2022-01-24 15:23 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29966/detail/PR-29966/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29966/detail/PR-29966/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29966/detail/PR-29966/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29966/detail/PR-29966/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_29966.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-01-24T14:51:11.644Z&rangeTo=2022-01-24T15:11:11.644Z&transactionName=Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=096f885a4df0189ee0dfcae07e4b3d44&transactionId=efb91d797fe7544c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-01-24T15:01:11.644+0000


* Duration: 22 min 19 sec


* Commit: 8d58031e08c52347be60e0e40bf0fecc773d2b0e



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 0 |
| Total        | 3   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-29966/detail/PR-29966/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `libbeat-lint - make -C libbeat check;make -C libbeat update;make -C x-pack/libbeat check;make -C `
<ul>
<li>Took 2 min 45 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-29966/runs/1/steps/4267/log/?start=0">here</a></li>
<li>Description: <code>make -C libbeat check;make -C libbeat update;make -C x-pack/libbeat check;make -C x-pack/libbeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-29966/runs/1/steps/4563/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>


## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-25 12:14 UTC, ruflin reviewed
Overall change LGTM. Did not run it locally for testing. @ph Would be good to get an additional pair of eyes on this.

2022-01-25 13:29 UTC, cmacknz commented
I ran filebeat (as an arbitrary choice) locally and inspected the HTTP requests to Elasticsearch with Wireshark to confirm the expected header was attached. I haven't exhaustively tested all beats, or all HTTP interactions.

2022-01-25 15:28 UTC, ph requested changes
@cmacknz You can Remove `Fleet`, it's already implemented in fleet-server at https://github.com/elastic/fleet-server/blame/d435007d9ad40f9f7b5ed02b7a722612faffbda8/internal/pkg/config/output.go#L149. The implement is different since we don't want to increase coupling with libbeat.

2022-01-25 16:03 UTC, ph approved these changes

2022-01-25 17:53 UTC, merged