[libbeat][docs] Update perms docs for beats writers to match 8.0 datastream reqs
elastic/beats pull request #30567
Opened 2022-02-23 21:40 UTC by andrewvc

Our docs are currently incorrect for users transitioning from 7.x to 8.0 when following our permissions guidelines. 8.0 apparently requires additional permissions.

This was discovered in [this discuss thread](https://discuss.elastic.co/t/permissions-issues-after-upgrading-heartbeat-to-8-0/297383), where a user found that heartbeat couldn't write to indices after using the perms described in our docs on [privileges and roles needed for publishing](https://www.elastic.co/guide/en/beats/heartbeat/current/privileges-to-publish-events.html). This applies equally to all beats however as those docs are not beat specific.

This fixes the docs, but we should consider additional messaging as part of the upgrade process so other users are not bit by this.

2022-02-23 21:40 UTC, elasticmachine commented
Pinging @elastic/uptime (Team:Uptime)

2022-02-23 21:40 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane  (Team:Elastic-Agent-Data-Plane)

2022-02-23 21:40 UTC, elasticmachine commented
Pinging @elastic/obs-docs (Team:Docs)

2022-02-23 22:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30567/detail/PR-30567/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30567/detail/PR-30567/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30567/detail/PR-30567/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30567/detail/PR-30567/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_30567.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-23T21:30:32.512Z&rangeTo=2022-02-23T21:50:32.512Z&transactionName=Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=bac1d45d6e5264937bf2e2071c93d50b&transactionId=b8eee6bb893cf543)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-02-23T21:40:32.512+0000


* Duration: 24 min 52 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :grey_exclamation: Flaky test report
No test was executed to be analysed.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-25 01:56 UTC, dedemorton commented
@andrewvc But `ingest_admin` (which is recommended in the next step) already has the `manage_index_templates` privilege, so isn't this redundant?

I can see how users might overlook the second step, though. IMO it would be more user friend to provide a comprehensive list of required privileges for each role users need to create, but in the past, there's been pushback to document the roles so that we can change the underlying privileges later on. :-/  But of course, with Beats, there is no one role that works.

2022-03-01 16:58 UTC, andrewvc commented
@dedemorton I don't see where `ingest_admin` is mentioned on https://www.elastic.co/guide/en/beats/heartbeat/current/privileges-to-publish-events.html , I think there's maybe a bug in the conditionals that drive this page

2022-03-01 22:41 UTC, dedemorton commented
@andrewvc I ran through the setup a few times and noticed some strange things.

1 - Created the setup user described [here](https://www.elastic.co/guide/en/beats/heartbeat/current/privileges-to-setup-beats.html), and it worked as documented.

2 - Created the publishing (writer) user described [here](https://www.elastic.co/guide/en/beats/heartbeat/current/privileges-to-publish-events.html) and ran Heartbeat with the default http monitor enabled (didn't change the port). It worked and showed that the service was down because I didn't have an http server exposed on port 9200.

3 - Changed the monitor config to use an active port (8000), and ran Heartbeat again.

4 - Heartbeat returned this error (sorry about the awkward line wraps):

```
{"log.level":"warn","@timestamp":"2022-03-01T14:20:43.448-0800","log.logger":"elasticsearch","log.origin":
{"file.name":"elasticsearch/client.go","file.line":414},"message":"Cannot index event 
publisher.Event{Content:beat.Event{Timestamp:time.Date(2022, time.March, 1, 14, 20, 41, 
500259000, time.Local), Meta:null, Fields:{\"agent\":{\"ephemeral_id\":\"da9206d4-5545-
4335-b9cb-f73d4a8f8881\",\"id\":\"fca63c01-66ba-44ca-83b5-
7e48ed34f208\",\"name\":\"Rhodas-MacBook-
Pro.local\",\"type\":\"heartbeat\",\"version\":\"8.0.1\"},\"ecs\":{\"version\":\"8.0.0\"},\"event\":
{\"dataset\":\"http\"},\"http\":{\"response\":{\"body\":
{\"bytes\":185,\"hash\":\"568b4de0ad30e85670e724dc30ccb675924353b77807356c5ad7f29c
8c38f510\"},\"headers\":{\"Content-Length\":\"185\",\"Content-
Type\":\"text/html\",\"Date\":\"Tue, 01 Mar 2022 22:20:41 
GMT\",\"Location\":\"http://localhost:8000/guide/index.html\",\"Server\":\"nginx/1.14.2\"},\"mime_
type\":\"text/html; charset=utf-8\",\"status_code\":301},\"rtt\":{\"content\":
{\"us\":165},\"response_header\":{\"us\":2121},\"total\":{\"us\":2533},\"validate\":
{\"us\":2286},\"write_request\":{\"us\":52}}},\"monitor\":{\"check_group\":\"d47d10e0-99ad-
11ec-b60f-acde48001122\",\"duration\":{\"us\":3533},\"id\":\"my-
monitor\",\"ip\":\"127.0.0.1\",\"name\":\"My Monitor\",\"status\":\"up\",\"timespan\":
{\"gte\":\"2022-03-01T22:20:41.503Z\",\"lt\":\"2022-03-
01T22:20:51.503Z\"},\"type\":\"http\"},\"observer\":{\"hostname\":\"Rhodas-MacBook-Pro.local\",\"ip\":
[\"fe80::aede:48ff:fe00:1122\",\"fe80::cd:1a60:a015:13ec\",\"10.0.0.179\",\"2601:1c0:7000:bac0:4
d7:e39b:4ed2:628c\",\"2601:1c0:7000:bac0:dc8e:2c36:a455:f87a\",\"2601:1c0:7000:bac0::2d2
d\",\"fe80::fc09:fcff:fee7:f6f9\",\"fe80::fc09:fcff:fee7:f6f9\",\"fe80::aa1d:6113:96f4:68b9\",\"fe80
::dab1:2ad9:7331:dd02\",\"fe80::ce81:b1c:bd2c:69e\"],\"mac\":
[\"ac:de:48:00:11:22\",\"f2:18:98:b4:de:bb\",\"f0:18:98:b4:de:bb\",\"fe:09:fc:e7:f6:f9\",\"fe:09:fc:
e7:f6:f9\",\"82:73:06:86:ac:00\",\"82:73:06:86:ac:05\",\"82:73:06:86:ac:04\",\"82:73:06:86:ac:01
\",\"82:73:06:86:ac:01\",\"98:5a:eb:dc:f3:07\"]},\"resolve\":{\"ip\":\"127.0.0.1\",\"rtt\":
{\"us\":914}},\"summary\":{\"down\":0,\"up\":1},\"tcp\":{\"rtt\":{\"connect\":{\"us\":191}}},\"url\":
{\"domain\":\"localhost\",\"full\":\"http://localhost:8000\",\"port\":8000,\"scheme\":\"http\"}}, 
Private:interface {}(nil), TimeSeries:false}, Flags:0x0, 
Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=403): 
{\"type\":\"security_exception\",\"reason\":\"action [indices:admin/mapping/auto_put] is 
unauthorized for user [heartbeat_writer_user] with roles [heartbeat_writer] on indices [.ds-
heartbeat-8.0.1-2022.03.01-000001], this action is granted by the index privileges 
[auto_configure,manage,write,all]\"}, dropping 
event!","service.name":"heartbeat","ecs.version":"1.6.0"}
```

5 - Granted `manage_index_templates` cluster privilege to the writer role. Got the same error.

6 - Granted `manage` privilege on the `heartbeat-*` index to the writer role, and it worked.

However, I do not know if we really want to grant `manage` to the Beats user. @kvch Can you advise on what we need to recommend to users (the least restrictive privilege that will fix this problem).

I don't understand why the documented privileges work when the monitor is down, but doesn't work when it's up.

2022-03-04 16:25 UTC, kvch approved these changes

2022-03-07 21:43 UTC, andrewvc commented
@kvch are you OK with this from a security perspective. I'm a little aprehensive to merge thinking about this now, I'm just wondering why a write requires these extra privs?

2022-03-08 08:32 UTC, ruflin requested changes
Before we do any changes, lets dig into why this is happening. On guess I have that this is somehow related to the data-stream change. Looking at the error we get `[indices:admin/mapping/auto_put]` it seems a mapping update cannot be made. Is this a dynamic mapping? Why did this work with indices but not data streams? We have `create_doc` which should give the mapping update permissions.

2022-04-01 21:48 UTC, andrewvc commented
Closing, this is better handled by https://github.com/elastic/beats/pull/31048

2022-04-01 21:48 UTC, closed without merging

2022-04-05 20:07 UTC, cmacknz commented
The fix for this in https://github.com/elastic/beats/pull/31048 would be available in 8.2.

Should we adjust the documentation for earlier versions, or publish a work around somewhere? There's nothing to point people to right now when they run into this.

2022-04-05 22:04 UTC, justincr-elastic commented
To workaround this issue for metricbeat 8.1.2, I had to add `manage` permission for `metricbeat-*` indices to role `metricbeat_writer`.

In other words, the documentation does not mention the `manage` permission for the `metricbeat_writer` role, I had to duplicate that permission in both of the `metricbeat_setup` and `metricbeat_writer` roles.
```
POST /_security/role/metricbeat_writer
{
  "cluster": ["monitor", "read_ilm"],
  "indices": [
    {
      "names": [ "metricbeat-*" ],
      "privileges": ["create_doc", "manage"]
    }
  ]
}
```
```
POST /_security/user/metricbeat_writer
{
  "password" : "metricbeat_writer-password",
  "roles" : [ "metricbeat_writer" ],
  "full_name" : "Metricbeat Writer",
  "email" : "metricbeat_writer@example.com",
  "metadata" : {
    "intelligence" : 7
  }
}
```

For existing 8.0.x and 8.1.x releases, it would be nice to add this workaround to the Beats documentation; or another viable workaround if possible.

Also, if any patches are being released for 8.0.x and 8.1.x, a code fix would be nice, if that is possible.

2022-04-06 14:39 UTC, cmacknz commented
We're going to add a known issue to the beats changelog about this.