Adjust pdhcollectquerydataex sample interval
elastic/beats pull request #30861
Opened 2022-03-16 13:52 UTC by narph

## What does this PR do?

- adjusts pdhcollectquerydataex collecting interval, definition was confusing, between sample interval and wait interval
- reuse event to collect data

## Why is it important?

- fixes delay in ingestion

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2022-03-16 13:55 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane  (Team:Elastic-Agent-Data-Plane)

2022-03-16 14:10 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30861/detail/PR-30861/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30861/detail/PR-30861/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30861/detail/PR-30861/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30861/detail/PR-30861/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-16T13:44:50.754Z&rangeTo=2022-03-16T14:04:50.754Z&transactionName=BUILD+Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=6a9c62d76b056ce6674c099b71998b04&transactionId=35118845f88c6dea)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-16T13:54:50.754+0000


* Duration: 15 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 0 |
| Total        | 3   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30861/detail/PR-30861/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-30861/runs/1/steps/1337/log/?start=0">here</a></li>
<li>Description: <code>Error 'org.jenkinsci.plugins.workflow.steps.FlowInterruptedException'</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-16 14:14 UTC, adriansr commented on metricbeat/module/windows/perfmon/reader.go
> +	windows.CloseHandle(re.event)
The query should be closed before the event. Maybe call CloseHandle inside a defer statement?

2022-03-16 14:17 UTC, adriansr requested changes

2022-03-17 11:25 UTC, narph commented on CHANGELOG.next.asciidoc
> +- Fix delay in perfmon counters collection {pull}30861[#30861]
of course, done

2022-03-17 13:44 UTC, adriansr approved these changes

2022-03-21 09:25 UTC, adriansr commented
@narph can we also backport this to 7.17 / 8.0 / 8.1 ?

2022-03-21 09:46 UTC, merged