packetbeat/sniffer: update error check to match github.com/google/gopacket/afpacket API
elastic/beats pull request #30882
Opened 2022-03-17 03:26 UTC by efd6

## What does this PR do?

Previously we were using github.com/tsg/gopacket, an older fork of github.com/google/gopacket
with additions that were necessary to support functionality that we needed. In 274ccac we
changed over to a more recent fork of github.com/google/gopacket porting forward some of the
changes that we had made to a collection of forks. A significant difference between the tsg
fork and the google package, not found until now was in how poll calls are handled in the
afpacket package; in the tsg fork, a zero poll event count was returned as EINTR

	func (h *TPacket) pollForFirstPacket(hdr header) error {
		for hdr.getStatus()&C.TP_STATUS_USER == 0 {
			h.pollset.fd = h.fd
			h.pollset.events = C.POLLIN
			h.pollset.revents = 0
			timeout := C.int(h.opts.timeout / time.Millisecond)
			n, err := C.poll(&h.pollset, 1, timeout)
			if n == 0 {
				/* propagate timeout when no packets are available
				   otherwise it will loop forever until a packet
				  is received. */
				return syscall.EINTR
			}
			h.stats.Polls++
			if err != nil {
				return err
			}
		}

		h.shouldReleasePacket = true
		return nil
	}

while in the google package an afpacket error, ErrTimeout is returned in the
same context.

	func (h *TPacket) pollForFirstPacket(hdr header) error {
		tm := int(h.opts.pollTimeout / time.Millisecond)
		for hdr.getStatus()&unix.TP_STATUS_USER == 0 {
			pollset := [1]unix.PollFd{
				{
					Fd:     int32(h.fd),
					Events: unix.POLLIN,
				},
			}
			n, err := unix.Poll(pollset[:], tm)
			if n == 0 {
				return ErrTimeout
			}

			atomic.AddInt64(&h.stats.Polls, 1)
			if pollset[0].Revents&unix.POLLERR > 0 {
				return ErrPoll
			}
			if err == syscall.EINTR {
				continue
			}
			if err != nil {
				return err
			}
		}

		h.shouldReleasePacket = true
		return nil
	}

This change brings the calling code into agreement with the afpacket package and
updates the logging message.
 
## Why is it important?

Without this change the af_packet capture mode is not functional.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

This can be tested locally on a linux host using the following config by running `packetbeat -e -d flows,sniffer` as root.
```
output:
  console:
    enabled: true
    pretty: true
packetbeat:
  flows:
    period: 10s
    timeout: 30s
  interfaces:
    device: any
    internal_networks:
    - private
    type: af_packet
  protocols:
  - enabled: false
    type: icmp
  - ports:
    - 80
    - 8082
    - 8000
    - 5000
    - 8002
    type: http
path:
  config: ./packetbeat8
  data: ./packetbeat8/data
  home: ./packetbeat8
  logs: ./packetbeat8/logs
processors:
- else:
  - add_host_metadata: null
  if:
    contains:
      tags: forwarded
  then:
  - drop_fields:
      fields:
      - host
- add_cloud_metadata: null
- add_docker_metadata: null
- detect_mime_type:
    field: http.request.body.content
    target: http.request.mime_type
- detect_mime_type:
    field: http.response.body.content
    target: http.response.mime_type
```

## Related issues

- Closes #30731.
- Closes #30822.

Also see https://discuss.elastic.co/t/packetbeat8-0-af-packet-report-errors/298180.

## Use cases

## Screenshots

## Logs

2022-03-17 03:26 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-03-17 03:33 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30882/detail/PR-30882/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30882/detail/PR-30882/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30882/detail/PR-30882/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30882/detail/PR-30882/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-17T03:17:16.677Z&rangeTo=2022-03-17T03:37:16.677Z&transactionName=BUILD+Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=476f89844d4d5d8b4a8a8d1ef230d8b2&transactionId=73502b467a48902b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-17T03:27:16.677+0000


* Duration: 6 min 44 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-30882/detail/PR-30882/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 28 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-30882/runs/1/steps/92/log/?start=0">here</a></li>
<li>Description: <code>[2022-03-17T03:31:43.152Z] The recommended git tool is: git
[2022-03-17T03:31:43.164Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-17 10:25 UTC, adriansr requested changes
Thanks for fixing. Just a correction to the changelog, remember that its contents are user facing so it's better to describe what is fixed, not how.

2022-03-17 10:25 UTC, adriansr commented on CHANGELOG.next.asciidoc
> +- packetbeat/sniffer: update error check to match github.com/google/gopacket/afpacket. {issue}30731[30731] {issue}30822[30822] {pull}[30882]
```suggestion
- packetbeat: Fix timeout error in af_packet capture mode. {issue}30731[30731] {issue}30822[30822] {pull}30882[30882]
```

2022-03-17 21:18 UTC, merged

2022-03-23 14:33 UTC, chinaxushi commented
Which version will this fix eventually be reflected in? In 8.1.1? I just tested 8.1.1, but there is still an error

2022-03-23 15:03 UTC, andrewkroh commented
`v8.1.2` will be the first. (If you're looking for a binary to test with we have development builds with the change listed at https://artifacts-api.elastic.co/v1/versions/8.2.0-SNAPSHOT/builds/latest/projects/beats).

2022-03-24 05:20 UTC, chinaxushi commented
@andrewkroh  I see. Thank you for your reply.