[elastic/beats] Rabbitmq_1015: Add shovel metricset
elastic/beats pull request #31534
Opened 2022-05-05 16:44 UTC by ritalwar

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2022-05-05 17:00 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31534/detail/PR-31534/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31534/detail/PR-31534/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31534/detail/PR-31534/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31534/detail/PR-31534/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_31534.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-05-05T16:34:55.266Z&rangeTo=2022-05-05T16:54:55.266Z&transactionName=Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=05599c5431a98e5358db5b22eb05842f&transactionId=1f3d1149cf88ed62)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-05T16:44:55.266+0000


* Duration: 15 min 15 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 0 |
| Total        | 3   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31534/detail/PR-31534/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `metricbeat-checks - make -C metricbeat check;make -C metricbeat update;make -C x-pack/metricbeat c`
<ul>
<li>Took 3 min 41 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31534/runs/1/steps/1280/log/?start=0">here</a></li>
<li>Description: <code>make -C metricbeat check;make -C metricbeat update;make -C x-pack/metricbeat check;make -C x-pack/metricbeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `x-pack/metricbeat-checks - make -C x-pack/metricbeat check;make -C x-pack/metricbeat update;make -`
<ul>
<li>Took 2 min 19 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31534/runs/1/steps/1286/log/?start=0">here</a></li>
<li>Description: <code>make -C x-pack/metricbeat check;make -C x-pack/metricbeat update;make -C metricbeat check;make -C metricbeat update;make check-no-changes;</code></l1>
</ul>
  
  
  
  
##### `make check-default`
<ul>
<li>Took 2 min 39 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31534/runs/1/steps/873/log/?start=0">here</a></li>
<li>Description: <code>make check-default</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31534/runs/1/steps/1337/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-05-09 07:08 UTC, ritalwar commented
/test

2022-05-10 08:00 UTC, belimawr reviewed
I added some questions about the consistency of the docs/example with the implementation and a couple of small linting/formatting (I thought our linter should catch them o.O).

2022-05-12 07:07 UTC, ritalwar commented on metricbeat/module/rabbitmq/_meta/config.reference.yml
> +  metricsets: ["node", "queue", "connection","shovel"]
Added exchange.

2022-05-12 07:08 UTC, ritalwar commented on metricbeat/docs/modules/rabbitmq.asciidoc
> +  metricsets: ["node", "queue", "connection","shovel"]
Updated.

2022-05-12 07:09 UTC, ritalwar commented on metricbeat/module/rabbitmq/_meta/config.yml
> +  #  - shovel
Updated.

2022-05-12 07:11 UTC, ritalwar commented on metricbeat/module/rabbitmq/shovel/data.go
> +
> I added some questions about the consistency of the docs/example with the implementation and a couple of small linting/formatting (I thought our linter should catch them o.O).

I have addressed all the comments, Thanks.

2022-05-12 14:09 UTC, belimawr requested changes

2022-05-12 14:09 UTC, belimawr commented on metricbeat/module/rabbitmq/shovel/shovel_test.go
> +		t.Fatal("write", err)
This error message could be more descriptive. What has failed when `err != nil`?

2022-05-18 09:16 UTC, belimawr commented on metricbeat/module/rabbitmq/shovel/shovel_test.go
> +func TestData(t *testing.T) {
I see, thanks for clarifying!

2022-05-18 09:17 UTC, belimawr approved these changes

2022-05-26 08:39 UTC, muthu-mps commented on metricbeat/module/rabbitmq/shovel/_meta/fields.yml
> +    - name: state
If this field refers to status property in the shovel document then can you rename the field name to status ? and the description should start as Current state of shovel...

2022-05-26 08:39 UTC, muthu-mps commented on metricbeat/module/rabbitmq/shovel/_meta/fields.yml
> +    - name: state
If this field refers to status property in the shovel document then can you rename the field name to status ? and the description should start as Current state of shovel...

2022-05-26 09:02 UTC, muthu-mps commented on metricbeat/module/rabbitmq/shovel/shovel.go
> +		return nil, err
Add context to the return `err`

2022-05-30 01:11 UTC, muthu-mps approved these changes
LGTM!

2022-05-30 06:32 UTC, ManojS-shetty approved these changes
LGTM!

2022-05-30 06:41 UTC, ritalwar commented on metricbeat/docs/modules_list.asciidoc
> +|<<metricbeat-metricset-rabbitmq-shovel,shovel>> beta[]
Initially yes.

2022-05-30 08:59 UTC, merged