[Filebeat] keep track of bytes read when max_bytes exceeded
elastic/beats pull request #31824
Opened 2022-06-04 09:20 UTC by liuwenping

## What does this PR do?

Newlines also need to be recorded in the skipped characters

## Why is it important?

The skipped newline character is not recorded in the registry when the `max_bytes`(maximum limit of a single line) is exceeded. as the number of long lines increases, it will cause repeated reading problems

The relevant PR is #28352

2022-06-04 09:26 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31824/detail/PR-31824/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31824/detail/PR-31824/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31824/detail/PR-31824/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31824/detail/PR-31824/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-04T09:10:52.834Z&rangeTo=2022-06-04T09:30:52.834Z&transactionName=Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=7e1360eff693115bdec1beb8c62bdef5&transactionId=da1b335a693b8f6b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-04T09:20:52.834+0000


* Duration: 6 min 39 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31824/detail/PR-31824/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31824/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/liuwenping return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/liuwenping : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/liuwenping : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-06 17:54 UTC, cmacknz commented
@leehinman this looks like a follow up to a similar change you made elsewhere in this file, can you review it? https://github.com/elastic/beats/pull/28352

@liuwenping is there a test case we can add for this?

2022-06-07 09:26 UTC, liuwenping commented
> 

updated

2022-06-07 10:14 UTC, rdner commented
/test

2022-06-07 11:33 UTC, rdner requested changes

2022-06-07 11:33 UTC, rdner commented on libbeat/reader/readfile/line_test.go
> +	}
This new behaviour does not seem to be tested, could you add a test?

2022-06-07 11:33 UTC, rdner approved these changes

2022-06-07 11:33 UTC, rdner commented on libbeat/reader/readfile/line_test.go
> +	}
sorry, got confused :)

2022-06-07 11:35 UTC, merged

2022-06-08 14:05 UTC, andrewkroh commented
After this change one of the tests in the reader package has started failing. https://github.com/elastic/beats/issues/31863.