[Filebeat] AWS S3 input split JSON arrays into multiple events
elastic/beats pull request #31904
Opened 2022-06-09 23:48 UTC by legoguy1000

## What does this PR do?

Mirror the feature of the Azure Event Hub input that if the message is a JSON array of objects, split it into multiple events

## Why is it important?

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates #29951

## Use cases

## Screenshots

## Logs

2022-06-09 23:56 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31904/detail/PR-31904/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31904/detail/PR-31904/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31904/detail/PR-31904/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31904/detail/PR-31904/2//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-09T23:41:42.558Z&rangeTo=2022-06-10T00:01:42.558Z&transactionName=Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=78b9792bf315132f4da13a9ef5fe7007&transactionId=fd29ce916f21ea98)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-09T23:51:42.558+0000


* Duration: 4 min 27 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-31904/detail/PR-31904/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-31904/runs/2/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/legoguy1000 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-10 02:00 UTC, aspacca commented
@legoguy1000 , this would be a breaking change as it is :)

my personal opinion is that it should be a feature behind a config flag in order to enable it

@kaiyan-sheng  , @andrewkroh what do you think?

2022-06-10 02:08 UTC, legoguy1000 commented
As I was adding the change log I had an inclination that it could be a breaking change.

2022-06-10 02:41 UTC, andrewkroh commented
I do think an explicit configuration is needed to avoid a breaking change. How about requiring this to split an array of objects (inspired by `jq`): 

`expand_event_list_from_field: .[]`

2022-06-13 01:27 UTC, aspacca commented
> I do think an explicit configuration is needed to avoid a breaking change

yes, as long as the behaviour does not apply automatically, it's not needed.
your proposal with `expand_event_list_from_field: .[]` is fine for me

2022-06-15 07:56 UTC, rdner requested changes

2022-06-15 07:56 UTC, rdner commented on x-pack/filebeat/input/awss3/s3_objects.go
> +			p.log.Errorw(fmt.Sprintf("serializing message %s", ms), "error", err)
Same here, we should not expose customer's raw data in logs.

2022-06-16 14:05 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2023-06-27 16:01 UTC, andrewkroh commented
Closing because https://github.com/elastic/beats/pull/35475 implemented this.

2023-11-29 15:10 UTC, jlind23 commented
Closing according to @andrewkroh's comment.

2023-11-29 15:10 UTC, closed without merging