x-pack/filebeat/input/httpjson: use timer instead of ticker for singleshot
elastic/beats pull request #32061
Opened 2022-06-22 22:34 UTC by efd6

## What does this PR do?

This replaces the use of a `time.Ticker` with a `time.Timer` for a single-shot wait.

## Why is it important?

It uses a more appropriate type for the task.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2022-06-22 22:34 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-06-22 23:11 UTC, ineo48 requested changes
non support for this event.

2022-06-22 23:45 UTC, efd6 commented
@ineo48 Would you please explain?

2022-06-29 09:35 UTC, adriansr approved these changes

2022-06-29 09:49 UTC, merged