Enable MacOS M1 stages in the CI on a weekly basis
elastic/beats pull request #32173
Opened 2022-06-30 14:42 UTC by v1v

## What does this PR do?

Run build/test in the CI on `macos m1` workers. It will run on a weekly basis

## Why is it important?

More test coverage

2022-06-30 17:32 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-32173/detail/PR-32173/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-32173/detail/PR-32173/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-32173/detail/PR-32173/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-32173/detail/PR-32173/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_32173.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-30T14:33:14.934Z&rangeTo=2022-06-30T14:53:14.934Z&transactionName=Beats/beats/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4facea8f38bee379ee99cf0b24a6111f&transactionId=bd6e2d9fd0fbb916)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-30T14:43:14.934+0000


* Duration: 168 min 16 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 24795  |
| Skipped      | 2152 |
| Total        | 26947   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![14](https://img.shields.io/badge/14%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-32173/detail/PR-32173/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


> Show only the first 10 steps failures

  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/26380/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 7 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/27755/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/27855/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/27916/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/27878/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/28961/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/28960/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 5 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/28946/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Extract Zip file`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/29017/log/?start=0">here</a></li>
<li>Description: <code>zip END header not found</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-32173/runs/1/steps/26340/log/?start=0">here</a></li>
<li>Description: <code>Error 'java.util.zip.ZipException: zip END header not found'</code></l1>
</ul>
  
  </p>
  </details>



## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-08 14:47 UTC, v1v commented
/test

2022-09-08 16:08 UTC, v1v commented
Terraform for MacOS is not available in the existing version (`0.13.7`) but from https://github.com/hashicorp/terraform/releases/tag/v1.0.2 
see https://releases.hashicorp.com/terraform/1.0.2/

Blocked by the bump

2022-09-08 16:59 UTC, kuisathaverat approved these changes

2022-09-09 08:58 UTC, v1v commented
/test

2022-09-09 15:23 UTC, belimawr requested changes
I'm far from being an expert on our automation, but it seems the "comments" rule should match the Beat name.

2022-09-09 15:23 UTC, belimawr commented on filebeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
I believe this should be Filebeat:
```suggestion
                - "/test filebeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on heartbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test heartbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on metricbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test metricbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on packetbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test packetbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/filebeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test filebeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/functionbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test functonbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/heartbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test heartbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/metricbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test metricbeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/osquerybeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test osquerybeat for macos-m1"
```

2022-09-09 15:23 UTC, belimawr commented on x-pack/packetbeat/Jenkinsfile.yml
> +                - "/test auditbeat for macos-m1"
```suggestion
                - "/test packetbeat for macos-m1"
```

2022-09-12 15:58 UTC, v1v commented on auditbeat/Jenkinsfile.yml
> +        stage: extended
```suggestion
      # Ignore as long as there are test failures, see https://github.com/elastic/beats/issues/33033
#     macosM1:
#         mage: "mage build unitTest"
#         platforms:             ## override default label in this specific stage.
#           - "orka && darwin && aarch64"
#         when:                  ## Override the top-level when.
#             comments:
#                 - "/test auditbeat for macos-m1"
#             labels:
#                 - "macos-m1"
#             parameters:
#                 - "macosM1Test"
#             tags: false         ## for all the tags
#         stage: extended
```

2022-09-12 15:58 UTC, v1v commented on metricbeat/Jenkinsfile.yml
> +        stage: extended
```suggestion
      # Ignore as long as there are test failures, see https://github.com/elastic/beats/issues/33035
#     macosM1:
#         mage: "mage build unitTest"
#         platforms:             ## override default label in this specific stage.
#           - "orka && darwin && aarch64"
#         when:                  ## Override the top-level when.
#             comments:
#                 - "/test metricbeat for macos-m1"
#             labels:
#                 - "macos-m1"
#             parameters:
#                 - "macosM1Test"
#             tags: false         ## for all the tags
#         stage: extended
```

2022-09-12 15:58 UTC, v1v commented on x-pack/metricbeat/Jenkinsfile.yml
> +        stage: extended
```suggestion
      # Ignore as long as there are test failures, see https://github.com/elastic/beats/issues/33036
#     macosM1:
#         mage: "mage build unitTest"
#         platforms:             ## override default label in this specific stage.
#           - "orka && darwin && aarch64"
#         when:                  ## Override the top-level when.
#             comments:
#                 - "/test metricbeat for macos-m1"
#             labels:
#                 - "macos-m1"
#             parameters:
#                 - "macosM1Test"
#             tags: false         ## for all the tags
#         stage: extended
```

2022-09-13 09:09 UTC, merged