[IIS] Remove beta warning from application_pool metricset
elastic/beats pull request #35480
Opened 2023-05-16 11:18 UTC by muthu-mps

- Bug

## What does this PR do?

Relates to this issue #35061 

## How to test this PR locally

- Install IIS metricbeat module
- Enable application_pool metrics collection
- Verify there is no beta warnings.

## Related issues

- Closes #35061

2023-05-16 12:15 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35480/detail/PR-35480/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35480/detail/PR-35480/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35480/detail/PR-35480/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35480/detail/PR-35480/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_35480.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-05-16T11:08:47.588Z&rangeTo=2023-05-16T11:28:47.588Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=3927ed8c38e312e69135c8ddf2ddb2e0&transactionId=a6e2a053753743a7)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-16T11:18:47.588+0000


* Duration: 57 min 48 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1398  |
| Skipped      | 90 |
| Total        | 1488   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-18 06:06 UTC, shmsr requested changes
The changes look good to me but the PR title seems a little off. Suggestion:

> [IIS] Remove beta warning from application_pool metricset

^^ is similar to the title of the issue linked.

2023-05-18 08:19 UTC, shmsr approved these changes

2023-05-18 08:19 UTC, shmsr approved these changes

2023-05-22 04:53 UTC, ritalwar reviewed
Entry missing in the changelog. Could you please add it?

2023-05-23 05:24 UTC, lalit-satapathy approved these changes

2023-05-23 13:01 UTC, merged