filebeat/input/tcp: fix call to get unspecified IPv6 addresses
elastic/beats pull request #35637
Opened 2023-05-31 21:37 UTC by efd6

## What does this PR do?

The call incorrectly uses the IPv4 address list to populate the IPv6 unspecified address list. This will result in a panic when the more IPv6 addresses than IPv4 addresses appear in the the hosts IP list as returned by net.LookupIP().

## Why is it important?

The current code crashes Filebeat under the conditions described.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Fixes #35064 

## Use cases

## Screenshots

## Logs

2023-05-31 22:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35637/detail/PR-35637/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35637/detail/PR-35637/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35637/detail/PR-35637/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-35637/detail/PR-35637/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_35637.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-05-31T21:29:09.149Z&rangeTo=2023-05-31T21:49:09.149Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=68262f592aa4ac822cf7c24c248dac88&transactionId=e111ce7e75453779)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-31T21:39:09.149+0000


* Duration: 71 min 51 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 7830  |
| Skipped      | 749 |
| Total        | 8579   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-31 23:37 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-06-01 09:55 UTC, belimawr requested changes
@efd6 could you add at least one test that reproduces the problem this PR addresses and ensures the fix work?

It could be in the form of a unit test for `containsUnspecifiedAddr` proving it does not panic regardless of the input.

2023-06-01 10:50 UTC, efd6 commented
That's not the failure. The failure is a panic in `contains` when `addrIsUnspecified` is shorter than `addr`. This can happen when the the wrong `addr` is passed in to `containsUnspecifiedAddr` for the address list that is used when passed into `contains`. Summary:
```
hasUnspecified6, addrIsUnspecified6, badAddr := containsUnspecifiedAddr(addr) // should be addr6
procNetTCP("/proc/net/tcp6", addr6, hasUnspecified6, addrIsUnspecified6) // functionally a set of calls of contains(b, addr, addrIsUnspecified6)
```
This is not testable without significant changes to the code, impacting on performance.

2023-06-02 17:42 UTC, andrewkroh commented
I do think we need some kind of execution of this code path. I experimented with the existing system tests for this input in [test_tcp.py](https://github.com/elastic/beats/blob/8c79b67906ab4399dd9e575e5f2c4005498c32f3/filebeat/tests/system/test_tcp.py#L6-L9). The reason this test does not catch issues with the metrics is that the test never runs long enough to execute this code path.

I was able to reproduce the failure with the existing tests after making two modifications -- (1) making that test wait for at least 60s before stop and (2) changing it to bind to 0.0.0.0.

Could we make the input not wait 60s before executing its first set of `procNetTCP` calls? I think this would have allowed the system tests to catch the previous panic from #35064 too. You could add a system test for the 0.0.0.0 case like

```diff
diff --git a/filebeat/tests/system/test_tcp.py b/filebeat/tests/system/test_tcp.py
index 2f98e95c8b..c6a7e2178e 100644
--- a/filebeat/tests/system/test_tcp.py
+++ b/filebeat/tests/system/test_tcp.py
@@ -37,7 +37,13 @@ class Test(BaseTest):
         """
         self.send_events_with_rfc6587_framing("octet")
 
-    def send_events_with_delimiter(self, delimiter):
+    def test_tcp_with_wildcard_address(self):
+        """
+        Test TCP input with it binding to the wildcard address 0.0.0.0.
+        """
+        self.send_events_with_delimiter("\n", bind="0.0.0.0")
+
+    def send_events_with_delimiter(self, delimiter, bind="127.0.0.1"):
         host = "127.0.0.1"
         port = 8080
         input_raw = """
@@ -50,7 +56,7 @@ class Test(BaseTest):
         if delimiter != "":
             input_raw += "\n  line_delimiter: {}".format(delimiter)
 
-        input_raw = input_raw.format(host, port)
+        input_raw = input_raw.format(bind, port)
 
         self.render_config_template(
             input_raw=input_raw,
diff --git a/libbeat/tests/system/config/libbeat.yml.j2 b/libbeat/tests/system/config/libbeat.yml.j2
index 5cd434690d..bc0401555b 100644
--- a/libbeat/tests/system/config/libbeat.yml.j2
+++ b/libbeat/tests/system/config/libbeat.yml.j2
@@ -118,3 +118,8 @@ path:
 #================================ keystore =====================================
 keystore.path: {{keystore_path}}
 {% endif %}
+
+# Enable periodic input metric logging.
+logging.metrics.namespaces:
+  - stats
+  - dataset

```

2023-06-05 14:32 UTC, belimawr approved these changes

2023-06-05 19:23 UTC, andrewkroh approved these changes

2023-06-05 23:09 UTC, merged