{file,packet,winlog}beat - Register input metrics diagnostic hook
elastic/beats pull request #35798
Opened 2023-06-16 15:13 UTC by andrewkroh

## What does this PR do?

Register an elastic-agent diagnostics hook to return the input metrics (encoded to JSON) in agent diagnostic dumps.

## Why is it important?

Have this data included in Agent diagnostics will help in understanding what's happening with the inputs.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Notes

I haven't tested this under Agent. I will likely want to backport this to 8.8.x after testing everything in the 8.9.0-SNAPSHOT when it's available.

2023-06-18 21:34 UTC, efd6 approved these changes

2023-06-19 00:22 UTC, andrewkroh commented
/test

2023-06-20 13:05 UTC, belimawr requested changes

2023-06-20 13:05 UTC, belimawr commented on filebeat/beater/filebeat.go
> +					logp.L().Warnw("Failed to collect input metric snapshot for Agent diagnostics.", "error", err)
We always put the error in the main log message:
```suggestion
					logp.L().Warnf("Failed to collect input metric snapshot for Agent diagnostics: %s", err)
```

2023-06-20 13:05 UTC, belimawr commented on packetbeat/beater/packetbeat.go
> +					logp.L().Warnw("Failed to collect input metric snapshot for Agent diagnostics.", "error", err)
Same thing as the others
We always put the error in the main log message:
```suggestion
					logp.L().Warnf("Failed to collect input metric snapshot for Agent diagnostics: %s", err)
```

2023-06-20 14:35 UTC, andrewkroh commented
> We always put the error in the main log message:

Let's use the thread in https://github.com/elastic/beats/pull/35658#discussion_r1218185058 to discuss this. The same topic is blocking that PR.

2023-06-29 12:10 UTC, belimawr approved these changes

2023-06-30 14:05 UTC, merged