Log error when statsd server fails to start and fix airflow docs
elastic/beats pull request #36477
Opened 2023-08-31 15:19 UTC by belimawr

## Proposed commit message
This commit adds a log error when the statsd server fails to start, it
also improves the Airflow module documentation to make extra clear
that the module will start a statsd server.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

~~## Author's Checklist~~
## How to test this PR locally
1. Create the following `metricbeat.yml`:
    ```yaml
    metricbeat.modules:
    - module: airflow
      host: "1.2.3.4" # Any IP that does not belong to the host running Metricbeat
      port: "9102"
      ttl: "10s"
      period: 5s
      metricsets: [ 'statsd' ]
    
    output.console:
      enabled: true
    ```
2. Start Metricbeat
3. After a few seconds you should see a log error like this:
    ```json
    {"log.level":"error","@timestamp":"2023-08-31T17:09:34.565+0200","log.logger":"airflow.statsd","log.origin":{"file.name":"server/server.go","file.line":201},"message":"could not start statsd server for module: airflow","service.name":"metricbeat","error":{"message":"failed to start UDP server: listen udp 1.2.3.4:9102: bind: cannot assign requested address"},"ecs.version":"1.6.0"}
    ```
~~## Related issues~~
~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

2023-08-31 15:36 UTC, AndersonQ approved these changes

2023-08-31 16:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-36477/detail/PR-36477/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-36477/detail/PR-36477/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-36477/detail/PR-36477/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-36477/detail/PR-36477/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_36477.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-08-31T15:11:01.272Z&rangeTo=2023-08-31T15:31:01.272Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=3be6e614555329f52efc70c8220db56f&transactionId=0ba627ce82b7f41a)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-31T15:21:01.272+0000


* Duration: 53 min 25 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1501  |
| Skipped      | 96 |
| Total        | 1597   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-04 17:32 UTC, shmsr commented
Looks good to me but I could see more adjustments that could be made to Airflow docs. Sample patch:

```diff
 This module collects metrics from
-https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html[Airflow metrics]. It runs a
-statsd server where airflow will send metrics to. The default metricset is `statsd`.
+https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html[Airflow metrics]. It runs a statsd server where airflow will send metrics to. The default metricset is `statsd`.
 
 [float]
 === Compatibility
 
-The Airflow module is tested with Airflow 2.1.0. It should work with version
-2.0.0 and later.
+The Airflow module is tested with Airflow 2.1.0. It should work with version 2.0.0 and later.
 
 [float]
 === Usage
-The Airflow module requires <<metricbeat-module-statsd,Statsd>> to receive Statsd metrics. Refer to the link for instructions about how to use Statsd.
+The Airflow module requires <<metricbeat-module-statsd,Statsd>> to receive statsd metrics. Refer to the link for instructions about how to use statsd.
 
-Add the following lines to your Airflow configuration file e.g. `airflow.cfg` ensuring `statsd_prefix` is left empty and replace `%METRICBEAT_HOST%` with the address metricbeat is running:
+Add the following lines to your Airflow configuration file e.g. `airflow.cfg` ensuring `statsd_prefix` is left empty and replace `%METRICBEAT_HOST%` with the address where metricbeat is running:
```

2023-09-04 17:33 UTC, shmsr requested changes
Left one comment.

2023-09-11 16:14 UTC, belimawr commented
@shmsr I added all your suggestions on e8dc1d693c02d3eb72bef7456c7b9f340472b420

2023-09-12 06:31 UTC, shmsr approved these changes

2023-09-12 09:20 UTC, shmsr commented on x-pack/metricbeat/module/statsd/server/server.go
nitpick: rename the method receiver from `b` to `m`: s/b/m

2023-09-12 09:20 UTC, shmsr commented on x-pack/metricbeat/module/statsd/server/server.go
not important though

2023-09-13 16:28 UTC, belimawr commented on x-pack/metricbeat/module/statsd/server/server.go
That's a bigger change on the this file, I rather make it into a separated PR.

2023-09-13 16:28 UTC, merged

2023-09-14 10:05 UTC, belimawr commented on x-pack/metricbeat/module/statsd/server/server.go
The followup PR: https://github.com/elastic/beats/pull/36591

I think when I first looked I was thinking about the opposite change :man_facepalming:. It's a super small PR :D