Add linux disk IO metrics to system/process
elastic/beats pull request #37213
Opened 2023-11-28 04:07 UTC by fearful-symmetry

## Proposed commit message
Part of https://github.com/elastic/beats/issues/7461

This actually pulls in the changes from elastic-agent-system-metrics, and adds linux-only disk IO metrics to system/process.

No actual code changes here, see https://github.com/elastic/elastic-agent-system-metrics/pull/114

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
- [x] I have made corresponding changes to the documentation
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2023-11-28 04:15 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-11-28T03:57:42.889Z&rangeTo=2023-11-28T04:17:42.889Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=8ade577b4423cd5e21fbd1e8040a0300&transactionId=0c85c51d013c0d38)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats





* Duration: 8 min 39 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->
















## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-28 06:18 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37213.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-11-28T04:00:12.754Z&rangeTo=2023-11-28T04:20:12.754Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=4f28c7c0430068c6689914810cb1a742&transactionId=f6d86271b6828ac9)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-28T04:10:12.754+0000


* Duration: 128 min 12 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 6  |
| Passed       | 28158  |
| Skipped      | 1882 |
| Total        | 30046   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![6](https://img.shields.io/badge/6%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/2//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Build&Test / metricbeat-pythonIntegTest / test_process – metricbeat.module.system.test_system.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 AssertionError: Element counts were not equal:
First has 0, Second has 1:  'io' 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 self = <test_system.Test testMethod=test_process>

    @unittest.skipUnless(re.match("(?i)win|linux|darwin|freebsd", sys.platform), "os")
    def test_process(self):
        """
        Test system/process output.
        """
        self.render_config_template(modules=[{
            "name": "system",
            "metricsets": ["process"],
            "period": "5s",
            "extras": {
                "process.env.whitelist": ["PATH"],
                "process.include_cpu_ticks": True,
    
                # Remove 'percpu' prior to checking documented fields because its keys are dynamic.
                "process.include_per_cpu": False,
            }
        }])
        self.run_beat_and_stop()
    
        output = self.read_output_json()
        self.assertGreater(len(output), 0)
    
        found_cmdline = False
        for evt in output:
            process = evt["system"]["process"]
            # Not all process will have 'cmdline' due to permission issues,
            # especially on Windows. Therefore we ensure at least some of
            # them will have it.
            found_cmdline |= "cmdline" in process
    
            # Remove 'env' prior to checking documented fields because its keys are dynamic.
            process.pop("env", None)
            self.assert_fields_are_documented(evt)
    
            # Remove optional keys.
            process.pop("cgroup", None)
            process.pop("fd", None)
            process.pop("cmdline", None)
            process.pop("num_threads", None)
    
>           self.assertCountEqual(SYSTEM_PROCESS_FIELDS, process.keys())
E           AssertionError: Element counts were not equal:
E           First has 0, Second has 1:  'io'

module/system/test_system.py:439: AssertionError 
 ```
</p></details>
</ul>
    
##### `Build&Test / metricbeat-pythonIntegTest / test_process_unix – metricbeat.module.system.test_system.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 AssertionError: Element counts were not equal:
First has 0, Second has 1:  'io' 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 self = <test_system.Test testMethod=test_process_unix>

    @unittest.skipUnless(re.match("(?i)linux|darwin|freebsd", sys.platform), "os")
    def test_process_unix(self):
        """
        Test system/process output checking it has got all expected fields specific of unix systems and no extra ones.
        """
    
        self.render_config_template(
            modules=[{
                "name": "system",
                "metricsets": ["process"],
                "period": "5s",
                "extras": {
                    "process.env.whitelist": ["PATH"],
                    "process.include_cpu_ticks": True,
    
                    # Remove 'percpu' prior to checking documented fields because its keys are dynamic.
                    "process.include_per_cpu": False,
                },
            }],
            # Some info is only guaranteed in processes with permissions, check
            # only on own processes.
            processors=[{
                "drop_event": {
                    "when": "not.equals.user.name: " + getpass.getuser(),
                },
            }],
        )
        self.run_beat_and_stop()
    
        output = self.read_output_json()
        self.assertGreater(len(output), 0)
    
        found_fd = False
        found_env = False
        found_cwd = not sys.platform.startswith("linux")
        for evt in output:
            found_cwd |= "working_directory" in evt["process"]
    
            process = evt["system"]["process"]
            found_fd |= "fd" in process
            found_env |= "env" in process
    
            # Remove 'env' prior to checking documented fields because its keys are dynamic.
            process.pop("env", None)
            self.assert_fields_are_documented(evt)
    
            # Remove optional keys.
            process.pop("cgroup", None)
            process.pop("cmdline", None)
            process.pop("fd", None)
            process.pop("num_threads", None)
    
>           self.assertCountEqual(SYSTEM_PROCESS_FIELDS, process.keys())
E           AssertionError: Element counts were not equal:
E           First has 0, Second has 1:  'io'

module/system/test_system.py:497: AssertionError 
 ```
</p></details>
</ul>
    
##### `Build&Test / metricbeat-unitTest / test_process – metricbeat.module.system.test_system.Test`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 AssertionError: Element counts were not equal:
First has 0, Second has 1:  'io' 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 self = <test_system.Test testMethod=test_process>

    @unittest.skipUnless(re.match("(?i)win|linux|darwin|freebsd", sys.platform), "os")
    def test_process(self):
        """
        Test system/process output.
        """
        self.render_config_template(modules=[{
            "name": "system",
            "metricsets": ["process"],
            "period": "5s",
            "extras": {
                "process.env.whitelist": ["PATH"],
                "process.include_cpu_ticks": True,
    
                # Remove 'percpu' prior to checking documented fields because its keys are dynamic.
                "process.include_per_cpu": False,
            }
        }])
        self.run_beat_and_stop()
    
        output = self.read_output_json()
        self.assertGreater(len(output), 0)
    
        found_cmdline = False
        for evt in output:
    [...]

2023-11-28 09:50 UTC, belimawr requested changes

2023-11-28 09:50 UTC, belimawr commented on metricbeat/docs/fields.asciidoc
> +The number of bytes read fromo read(2) and similar syscalls.
Typo
```suggestion
The number of bytes read from read(2) and similar syscalls.
```

2023-11-28 09:50 UTC, belimawr commented on metricbeat/docs/fields.asciidoc
> +Disk I/O Metrics, as forwarded from /proc/[PID]/IO. Available on Linux only.
I was looking on my fs and the whole path is lowercase (e.g: `/proc/2847/io`), I believe the docs should reflect it as well.
```suggestion
Disk I/O Metrics, as forwarded from /proc/[PID]/io. Available on Linux only.
```

2023-11-28 09:50 UTC, belimawr commented on metricbeat/module/system/process/_meta/fields.yml
> +      description: Disk I/O Metrics, as forwarded from /proc/[PID]/IO. Available on Linux only.
Same here
```suggestion
      description: Disk I/O Metrics, as forwarded from /proc/[PID]/io. Available on Linux only.
```

2023-11-28 09:50 UTC, belimawr commented on metricbeat/module/system/process/_meta/fields.yml
> +          description: The number of bytes read fromo read(2) and similar syscalls.
Typo
```suggestion
          description: The number of bytes read from read(2) and similar syscalls.
```

2023-11-28 21:21 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/3//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/3//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/3//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/3//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-11-28T18:15:15.199Z&rangeTo=2023-11-28T18:35:15.199Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c34d5296a0e4186ff269deccde53e09c&transactionId=f42ad5eb1af520ec)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-28T18:25:15.199+0000


* Duration: 176 min 59 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 28164  |
| Skipped      | 1882 |
| Total        | 30046   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->
















## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-29 00:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/4//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/4//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/4//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/4//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37213.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-11-28T21:06:32.149Z&rangeTo=2023-11-28T21:26:32.149Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=a0e4778c6e9d0310ff7e7cfb1ff00804&transactionId=e1bfef34470e739d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-28T21:16:32.149+0000


* Duration: 186 min 6 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 28164  |
| Skipped      | 1882 |
| Total        | 30046   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-30 01:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/5//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/5//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/5//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/5//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37213.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-11-29T22:37:15.441Z&rangeTo=2023-11-29T22:57:15.441Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=6e4842eb935fa7313763412b3d8bbce0&transactionId=83230079f4c5acba)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-29T22:47:15.441+0000


* Duration: 178 min 38 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 28164  |
| Skipped      | 1882 |
| Total        | 30046   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-01 14:18 UTC, belimawr approved these changes

2023-12-01 20:08 UTC, cmacknz approved these changes

2023-12-01 20:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/6//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/6//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/6//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37213/detail/PR-37213/6//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37213.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-12-01T17:28:18.324Z&rangeTo=2023-12-01T17:48:18.324Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=136797f92fd64cf1dd520a42d4e5501c&transactionId=a9ce89faf6d913d1)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-12-01T17:38:18.324+0000


* Duration: 180 min 50 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 28164  |
| Skipped      | 1882 |
| Total        | 30046   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-01 20:57 UTC, merged