x-pack/filebeat/input/http-endpoint: Add fallback content-type to incoming requests
elastic/beats pull request #37724
Opened 2024-01-24 14:25 UTC by bhapas

## Proposed commit message

Few Webhooks like BitDefender do not send in `Content-Type` in their requests towards httpserver created in `http_endpoint` input. Hence the requests fail as the server expects a contentType.

Adding `application/json` as a fallback content-type for incoming requests if it is empty.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/integrations/issues/8696

2024-01-24 14:30 UTC, P1llus commented
I think we might want to reuse the content type override functionality we already have, and find out why its not executing

2024-01-24 14:34 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/2//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-01-24T14:16:18.865Z&rangeTo=2024-01-24T14:36:18.865Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7cf6d3d1966fedac5a504a8e88e9d277&transactionId=1dc0b9d1e9518bf4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2024-01-24T14:26:18.865+0000


* Duration: 8 min 47 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/2/steps/289/log/?start=0">here</a></li>
<li>Description: <code>Error 'org.jenkinsci.plugins.workflow.steps.FlowInterruptedException'</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-01-24 16:19 UTC, bhapas commented
> I think we might want to reuse the content type override functionality we already have, and find out why its not executing

The `http.Handler` that is created to handle a specific endpoint pattern accepts `application/json` as a default. But the [`http.Request`](https://pkg.go.dev/net/http#Request) coming from external server does not have this set. If we have use the same config value as a fallback , then we can use it through the [apiValidator](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/http_endpoint/validate.go#L32) struct in the handler and use it like

```diff
--- a/x-pack/filebeat/input/http_endpoint/handler.go
+++ b/x-pack/filebeat/input/http_endpoint/handler.go
@@ -54,7 +54,7 @@ type handler struct {
 func (h *handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
+      // Few webhook servers don't send in the Content-Type , hence defaulting to application/json if not present
+        if r.Header.Get("Content-Type") == "" {
+               r.Header.Set("Content-Type", h.validator.contentType)
        }

```

WDYT?

2024-01-24 16:43 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/3//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/3//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/3//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/3//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37724.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-01-24T14:18:56.486Z&rangeTo=2024-01-24T14:38:56.486Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=af24b9d1f65332b7910fe03d64dbc95e&transactionId=09b70f7b80cb8c51)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2024-01-24T14:28:56.486+0000


* Duration: 135 min 32 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3249  |
| Skipped      | 176 |
| Total        | 3425   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/3//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `x-pack/filebeat-packaging-linux - mage package`
<ul>
<li>Took 11 min 7 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/3/steps/4206/log/?start=0">here</a></li>
<li>Description: <code>mage package</code></l1>
</ul>
  
  
  
  
##### `x-pack/filebeat-packaging-arm-ubuntu-2204-aarch64 - mage package`
<ul>
<li>Took 4 min 2 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/3/steps/4385/log/?start=0">here</a></li>
<li>Description: <code>mage package</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/3/steps/4549/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 1'</code></l1>
</ul>
  
  </p>
  </details>



## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-01-24 16:50 UTC, bhapas commented
/test

2024-01-24 17:16 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/4//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/4//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/4//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/4//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_37724.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-01-24T16:40:34.365Z&rangeTo=2024-01-24T17:00:34.365Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=f792289a632a67306d8dd9bfdaf1ba04&transactionId=4b9457f4a56e2461)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2024-01-24T16:50:34.365+0000


* Duration: 26 min 42 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-37724/detail/PR-37724/4//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `x-pack/filebeat-packaging-linux - mage package`
<ul>
<li>Took 11 min 13 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/4/steps/2117/log/?start=0">here</a></li>
<li>Description: <code>mage package</code></l1>
</ul>
  
  
  
  
##### `x-pack/filebeat-packaging-arm-ubuntu-2204-aarch64 - mage package`
<ul>
<li>Took 4 min 9 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/4/steps/2284/log/?start=0">here</a></li>
<li>Description: <code>mage package</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-37724/runs/4/steps/2448/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 1'</code></l1>
</ul>
  
  </p>
  </details>



## :grey_exclamation: Flaky test report
No test was executed to be analysed.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-01-24 18:29 UTC, P1llus commented
I just think that its weird its not already being set, its like part of the code is no longer being used after certain changes 🤔

2024-01-24 18:35 UTC, andrewkroh commented on x-pack/filebeat/input/http_endpoint/handler.go
> +	if r.Header.Get("Content-Type") == "" {
The only reason to modify the request is to make the validator pass. So why not disable content-type validation using configuration?

From the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-http_endpoint.html):

<img width="289" alt="Screenshot 2024-01-24 at 13 34 14" src="https://github.com/elastic/beats/assets/4565752/77a2dd4a-a720-44db-adbe-22e7dcebed26">

2024-01-24 18:36 UTC, andrewkroh requested changes
I seems like this can be accomplished via configuration already.

2024-01-25 11:26 UTC, bhapas commented
@andrewkroh Probably https://github.com/elastic/integrations/pull/8974 in favour of config changes

2024-02-05 14:38 UTC, closed without merging