[Filebeat] Fix uri_parts ingest pipeline processor output wrong extension
elastic/beats pull request #38216
Opened 2024-03-07 15:06 UTC by muthu-mps

## Proposed commit message

This PR fixes the errors in the pipeline tests which generates incorrect values for the `extension` field of `uri_parts` processor. [Bug fix](https://github.com/elastic/elasticsearch/issues/105612) done in Elasticsearch to remove the incorrect url.extension values from the uri_parts ingest pipeline processor. The affected beats module should remove this field from the generated sample documents. IIS error module and the o365 audit log modules are effected by this change.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
cd beats/filebeat
GENERATE=true TESTING_FILEBEAT_MODULES=iis,o365 mage -v pythonIntegTest

## Related issues
This fixes the python integration tests failure reported in the below [PR](https://github.com/elastic/beats/pull/38122)

2024-03-07 15:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-winlogbeat/builds/1040)
* Commit: 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-winlogbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1040","number":1040,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1040}
buildkite-pr-comment-->

2024-03-07 15:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3091)
* Commit: 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3091}
buildkite-pr-comment-->

2024-03-07 15:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/1877)
* Commit: 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1877","number":1877,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1877}
buildkite-pr-comment-->

2024-03-07 15:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-packetbeat/builds/1884)
* Commit: 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-packetbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1884","number":1884,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1884}
buildkite-pr-comment-->

2024-03-07 15:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-packetbeat/builds/1889)
* Commit: ac306a99c3652d001f306f86b4e49e094cb1ddd6

### History
* :green_heart: [Build #1884](https://buildkite.com/elastic/beats-packetbeat/builds/1884) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-packetbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1889","number":1889,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1884","number":1884,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1889}
buildkite-pr-comment-->

2024-03-07 15:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3096)
* Commit: ac306a99c3652d001f306f86b4e49e094cb1ddd6

### History
* :green_heart: [Build #3091](https://buildkite.com/elastic/beats-metricbeat/builds/3091) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3096","number":3096,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3096}
buildkite-pr-comment-->

2024-03-07 15:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/1882)
* Commit: ac306a99c3652d001f306f86b4e49e094cb1ddd6

### History
* :green_heart: [Build #1877](https://buildkite.com/elastic/beats-libbeat/builds/1877) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1882","number":1882,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1877","number":1877,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1882}
buildkite-pr-comment-->

2024-03-07 15:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-winlogbeat/builds/1045)
* Commit: ac306a99c3652d001f306f86b4e49e094cb1ddd6

### History
* :green_heart: [Build #1040](https://buildkite.com/elastic/beats-winlogbeat/builds/1040) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-winlogbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1045","number":1045,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1040","number":1040,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1045}
buildkite-pr-comment-->

2024-03-07 15:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-winlogbeat/builds/1046)
* Commit: f3a4708f2414dfe2a960e0f532c7e3790a8d5891

### History
* :green_heart: [Build #1045](https://buildkite.com/elastic/beats-winlogbeat/builds/1045) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1040](https://buildkite.com/elastic/beats-winlogbeat/builds/1040) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-winlogbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1046","number":1046,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1045","number":1045,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1040","number":1040,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1046}
buildkite-pr-comment-->

2024-03-07 15:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3097)
* Commit: f3a4708f2414dfe2a960e0f532c7e3790a8d5891

### History
* :green_heart: [Build #3096](https://buildkite.com/elastic/beats-metricbeat/builds/3096) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #3091](https://buildkite.com/elastic/beats-metricbeat/builds/3091) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3097","number":3097,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3096","number":3096,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3097}
buildkite-pr-comment-->

2024-03-07 15:22 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38216/detail/PR-38216/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38216/detail/PR-38216/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38216/detail/PR-38216/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38216/detail/PR-38216/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-03-07T14:56:53.749Z&rangeTo=2024-03-07T15:16:53.749Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=11f78c62affadce68998f050d11cc55d&transactionId=3cd5db929215fdb6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats





* Duration: 16 min 49 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->
















## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-03-07 15:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2179)
* Commit: f3a4708f2414dfe2a960e0f532c7e3790a8d5891

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2179#018e197e-5c49-481c-9194-405ca7e0b683)

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2179}
buildkite-pr-comment-->

2024-03-07 15:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/filebeat/builds/3520)
* Commit: f3a4708f2414dfe2a960e0f532c7e3790a8d5891

### Failed CI Steps
* [:windows:-family/core-windows-2022 Unit Tests](https://buildkite.com/elastic/filebeat/builds/3520#018e197e-552c-4f84-8a75-21e40f39035c)

cc @muthu-mps

<!--buildkite-pr-comment-filebeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3520","number":3520,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":3520}
buildkite-pr-comment-->

2024-03-11 14:06 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2248)
* Commit: 42c867d7af4d20c669e1e3e801bb9a7b6c069529

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2248#018e2dd0-0b65-43ad-b985-1243b8172dc6)

### History
* :broken_heart: [Build #2179](https://buildkite.com/elastic/heartbeat/builds/2179) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2248","number":2248,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2248}
buildkite-pr-comment-->

2024-03-11 14:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2250)
* Commit: 07480b2ab575fb556b8eb6966677717c83cfe94f

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2250#018e2de1-6558-49c9-80f1-fc3bc596723c)

### History
* :broken_heart: [Build #2248](https://buildkite.com/elastic/heartbeat/builds/2248) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #2179](https://buildkite.com/elastic/heartbeat/builds/2179) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2250","number":2250,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2248","number":2248,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2250}
buildkite-pr-comment-->

2024-03-11 14:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/filebeat/builds/3591)
* Commit: 07480b2ab575fb556b8eb6966677717c83cfe94f

### Failed CI Steps
* [:windows:-family/core-windows-2022 Unit Tests](https://buildkite.com/elastic/filebeat/builds/3591#018e2de1-65ba-4cd0-b91a-2af91d079693)

### History
* :broken_heart: [Build #3589](https://buildkite.com/elastic/filebeat/builds/3589) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #3520](https://buildkite.com/elastic/filebeat/builds/3520) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-filebeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3591","number":3591,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3589","number":3589,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3520","number":3520,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":3591}
buildkite-pr-comment-->

2024-03-11 14:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/1953)
* Commit: 07480b2ab575fb556b8eb6966677717c83cfe94f

### History
* :green_heart: [Build #1883](https://buildkite.com/elastic/beats-libbeat/builds/1883) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1882](https://buildkite.com/elastic/beats-libbeat/builds/1882) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1877](https://buildkite.com/elastic/beats-libbeat/builds/1877) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1953","number":1953,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1883","number":1883,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1882","number":1882,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1877","number":1877,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1953}
buildkite-pr-comment-->

2024-03-11 14:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-packetbeat/builds/1960)
* Commit: 07480b2ab575fb556b8eb6966677717c83cfe94f

### History
* :green_heart: [Build #1890](https://buildkite.com/elastic/beats-packetbeat/builds/1890) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1889](https://buildkite.com/elastic/beats-packetbeat/builds/1889) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1884](https://buildkite.com/elastic/beats-packetbeat/builds/1884) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-packetbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1960","number":1960,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1890","number":1890,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1889","number":1889,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1884","number":1884,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1960}
buildkite-pr-comment-->

2024-03-11 15:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3167)
* Commit: 07480b2ab575fb556b8eb6966677717c83cfe94f

### History
* :green_heart: [Build #3097](https://buildkite.com/elastic/beats-metricbeat/builds/3097) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #3096](https://buildkite.com/elastic/beats-metricbeat/builds/3096) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #3091](https://buildkite.com/elastic/beats-metricbeat/builds/3091) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3167","number":3167,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3097","number":3097,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3096","number":3096,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3167}
buildkite-pr-comment-->

2024-03-12 03:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/filebeat/builds/3611)
* Commit: defd660e2156165787674e33071154ae55c58721

### Failed CI Steps
* [:windows:-family/core-windows-2022 Unit Tests](https://buildkite.com/elastic/filebeat/builds/3611#018e30ae-1079-48c2-a0ed-92a5bad8e4f6)

### History
* :broken_heart: [Build #3591](https://buildkite.com/elastic/filebeat/builds/3591) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #3589](https://buildkite.com/elastic/filebeat/builds/3589) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #3520](https://buildkite.com/elastic/filebeat/builds/3520) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-filebeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3611","number":3611,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3591","number":3591,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3589","number":3589,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3520","number":3520,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":3611}
buildkite-pr-comment-->

2024-03-12 03:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2270)
* Commit: defd660e2156165787674e33071154ae55c58721

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2270#018e30ae-14c9-45e7-a7d1-ec11d949147d)

### History
* :broken_heart: [Build #2250](https://buildkite.com/elastic/heartbeat/builds/2250) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #2248](https://buildkite.com/elastic/heartbeat/builds/2248) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #2179](https://buildkite.com/elastic/heartbeat/builds/2179) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2270","number":2270,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2250","number":2250,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2248","number":2248,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2270}
buildkite-pr-comment-->

2024-03-12 03:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/1973)
* Commit: defd660e2156165787674e33071154ae55c58721

### History
* :green_heart: [Build #1953](https://buildkite.com/elastic/beats-libbeat/builds/1953) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1883](https://buildkite.com/elastic/beats-libbeat/builds/1883) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1882](https://buildkite.com/elastic/beats-libbeat/builds/1882) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1877](https://buildkite.com/elastic/beats-libbeat/builds/1877) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1973","number":1973,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1953","number":1953,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1883","number":1883,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1882","number":1882,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1877","number":1877,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1973}
buildkite-pr-comment-->

2024-03-12 03:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-packetbeat/builds/1980)
* Commit: defd660e2156165787674e33071154ae55c58721

### History
* :green_heart: [Build #1960](https://buildkite.com/elastic/beats-packetbeat/builds/1960) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1890](https://buildkite.com/elastic/beats-packetbeat/builds/1890) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1889](https://buildkite.com/elastic/beats-packetbeat/builds/1889) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1884](https://buildkite.com/elastic/beats-packetbeat/builds/1884) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-packetbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1980","number":1980,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1960","number":1960,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1890","number":1890,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1889","number":1889,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1884","number":1884,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1980}
buildkite-pr-comment-->

2024-03-12 03:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-winlogbeat/builds/1136)
* Commit: defd660e2156165787674e33071154ae55c58721

### History
* :green_heart: [Build #1116](https://buildkite.com/elastic/beats-winlogbeat/builds/1116) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1046](https://buildkite.com/elastic/beats-winlogbeat/builds/1046) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1045](https://buildkite.com/elastic/beats-winlogbeat/builds/1045) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1040](https://buildkite.com/elastic/beats-winlogbeat/builds/1040) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-winlogbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1136","number":1136,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1116","number":1116,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1046","number":1046,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1045","number":1045,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1040","number":1040,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1136}
buildkite-pr-comment-->

2024-03-12 04:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3187)
* Commit: defd660e2156165787674e33071154ae55c58721

### History
* :green_heart: [Build #3167](https://buildkite.com/elastic/beats-metricbeat/builds/3167) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #3097](https://buildkite.com/elastic/beats-metricbeat/builds/3097) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #3096](https://buildkite.com/elastic/beats-metricbeat/builds/3096) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #3091](https://buildkite.com/elastic/beats-metricbeat/builds/3091) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3187","number":3187,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3167","number":3167,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3097","number":3097,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3096","number":3096,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3187}
buildkite-pr-comment-->

2024-03-12 15:14 UTC, leehinman approved these changes
LGTM

2024-03-13 04:15 UTC, ShourieG approved these changes
Lgtm

2024-03-13 04:22 UTC, shmsr approved these changes

2024-03-13 04:23 UTC, shmsr commented on CHANGELOG.next.asciidoc
> +- Fix the incorrect values generated by url_parts processor. {pull}38216[38216]
```suggestion
- Fix the incorrect values generated by the uri_parts processor. {pull}38216[38216]
```

2024-03-13 04:23 UTC, shmsr requested changes
Left one comment.

2024-03-13 04:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/filebeat/builds/3679)
* Commit: 5404033d230e3b696110aa47b1071f897636b6d4

### Failed CI Steps
* [:windows:-family/core-windows-2022 Unit Tests](https://buildkite.com/elastic/filebeat/builds/3679#018e3608-6a3d-4283-b972-f156e080753d)

### History
* :broken_heart: [Build #3611](https://buildkite.com/elastic/filebeat/builds/3611) failed defd660e2156165787674e33071154ae55c58721
* :broken_heart: [Build #3591](https://buildkite.com/elastic/filebeat/builds/3591) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #3589](https://buildkite.com/elastic/filebeat/builds/3589) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #3520](https://buildkite.com/elastic/filebeat/builds/3520) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-filebeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3679","number":3679,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3611","number":3611,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3591","number":3591,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3589","number":3589,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3520","number":3520,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":3679}
buildkite-pr-comment-->

2024-03-13 04:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2338)
* Commit: 5404033d230e3b696110aa47b1071f897636b6d4

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2338#018e3608-b1c1-4a75-bce3-4e49fdd04d83)

### History
* :broken_heart: [Build #2270](https://buildkite.com/elastic/heartbeat/builds/2270) failed defd660e2156165787674e33071154ae55c58721
* :broken_heart: [Build #2250](https://buildkite.com/elastic/heartbeat/builds/2250) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #2248](https://buildkite.com/elastic/heartbeat/builds/2248) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #2179](https://buildkite.com/elastic/heartbeat/builds/2179) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2338","number":2338,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2270","number":2270,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2250","number":2250,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2248","number":2248,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2338}
buildkite-pr-comment-->

2024-03-13 04:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/2041)
* Commit: 5404033d230e3b696110aa47b1071f897636b6d4

### History
* :green_heart: [Build #1973](https://buildkite.com/elastic/beats-libbeat/builds/1973) succeeded defd660e2156165787674e33071154ae55c58721
* :green_heart: [Build #1953](https://buildkite.com/elastic/beats-libbeat/builds/1953) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1883](https://buildkite.com/elastic/beats-libbeat/builds/1883) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1882](https://buildkite.com/elastic/beats-libbeat/builds/1882) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1877](https://buildkite.com/elastic/beats-libbeat/builds/1877) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/2041","number":2041,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1973","number":1973,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1953","number":1953,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1883","number":1883,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1882","number":1882,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1877","number":1877,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":2041}
buildkite-pr-comment-->

2024-03-13 04:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/heartbeat/builds/2339)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### Failed CI Steps
* [:windows: Unit Tests / family/core-windows-2022](https://buildkite.com/elastic/heartbeat/builds/2339#018e361e-710d-4d09-9d56-965415e6b53f)

### History
* :broken_heart: [Build #2338](https://buildkite.com/elastic/heartbeat/builds/2338) failed 5404033d230e3b696110aa47b1071f897636b6d4
* :broken_heart: [Build #2270](https://buildkite.com/elastic/heartbeat/builds/2270) failed defd660e2156165787674e33071154ae55c58721
* :broken_heart: [Build #2250](https://buildkite.com/elastic/heartbeat/builds/2250) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #2248](https://buildkite.com/elastic/heartbeat/builds/2248) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #2179](https://buildkite.com/elastic/heartbeat/builds/2179) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-heartbeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2339","number":2339,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2338","number":2338,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2270","number":2270,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2250","number":2250,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2248","number":2248,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/heartbeat/builds/2179","number":2179,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":2339}
buildkite-pr-comment-->

2024-03-13 04:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/filebeat/builds/3680)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### Failed CI Steps
* [:windows:-family/core-windows-2022 Unit Tests](https://buildkite.com/elastic/filebeat/builds/3680#018e361e-4679-41fd-b955-98d8045f59f5)

### History
* :broken_heart: [Build #3679](https://buildkite.com/elastic/filebeat/builds/3679) failed 5404033d230e3b696110aa47b1071f897636b6d4
* :broken_heart: [Build #3611](https://buildkite.com/elastic/filebeat/builds/3611) failed defd660e2156165787674e33071154ae55c58721
* :broken_heart: [Build #3591](https://buildkite.com/elastic/filebeat/builds/3591) failed 07480b2ab575fb556b8eb6966677717c83cfe94f
* :broken_heart: [Build #3589](https://buildkite.com/elastic/filebeat/builds/3589) failed 42c867d7af4d20c669e1e3e801bb9a7b6c069529
* :broken_heart: [Build #3520](https://buildkite.com/elastic/filebeat/builds/3520) failed f3a4708f2414dfe2a960e0f532c7e3790a8d5891

cc @muthu-mps

<!--buildkite-pr-comment-filebeat
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3680","number":3680,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3679","number":3679,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3611","number":3611,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3591","number":3591,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3589","number":3589,"commit":"42c867d7af4d20c669e1e3e801bb9a7b6c069529"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/filebeat/builds/3520","number":3520,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"}],"number":3680}
buildkite-pr-comment-->

2024-03-13 04:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-libbeat/builds/2042)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### History
* :green_heart: [Build #2041](https://buildkite.com/elastic/beats-libbeat/builds/2041) succeeded 5404033d230e3b696110aa47b1071f897636b6d4
* :green_heart: [Build #1973](https://buildkite.com/elastic/beats-libbeat/builds/1973) succeeded defd660e2156165787674e33071154ae55c58721
* :green_heart: [Build #1953](https://buildkite.com/elastic/beats-libbeat/builds/1953) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1883](https://buildkite.com/elastic/beats-libbeat/builds/1883) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1882](https://buildkite.com/elastic/beats-libbeat/builds/1882) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1877](https://buildkite.com/elastic/beats-libbeat/builds/1877) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-libbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/2042","number":2042,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/2041","number":2041,"commit":"5404033d230e3b696110aa47b1071f897636b6d4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1973","number":1973,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1953","number":1953,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1883","number":1883,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-libbeat/builds/1882","number":1882,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"}],"number":2042}
buildkite-pr-comment-->

2024-03-13 05:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-winlogbeat/builds/1205)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### History
* :green_heart: [Build #1136](https://buildkite.com/elastic/beats-winlogbeat/builds/1136) succeeded defd660e2156165787674e33071154ae55c58721
* :green_heart: [Build #1116](https://buildkite.com/elastic/beats-winlogbeat/builds/1116) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1046](https://buildkite.com/elastic/beats-winlogbeat/builds/1046) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1045](https://buildkite.com/elastic/beats-winlogbeat/builds/1045) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1040](https://buildkite.com/elastic/beats-winlogbeat/builds/1040) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-winlogbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1205","number":1205,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1136","number":1136,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1116","number":1116,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1046","number":1046,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1045","number":1045,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-winlogbeat/builds/1040","number":1040,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":1205}
buildkite-pr-comment-->

2024-03-13 05:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-packetbeat/builds/2049)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### History
* :green_heart: [Build #1980](https://buildkite.com/elastic/beats-packetbeat/builds/1980) succeeded defd660e2156165787674e33071154ae55c58721
* :green_heart: [Build #1960](https://buildkite.com/elastic/beats-packetbeat/builds/1960) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #1890](https://buildkite.com/elastic/beats-packetbeat/builds/1890) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #1889](https://buildkite.com/elastic/beats-packetbeat/builds/1889) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #1884](https://buildkite.com/elastic/beats-packetbeat/builds/1884) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-packetbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/2049","number":2049,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1980","number":1980,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1960","number":1960,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1890","number":1890,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1889","number":1889,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-packetbeat/builds/1884","number":1884,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":2049}
buildkite-pr-comment-->

2024-03-13 05:17 UTC, shmsr approved these changes

2024-03-13 05:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/beats-metricbeat/builds/3256)
* Commit: 8c88e40c3f5631a078ad3a6427e9ee31b0d75a24

### History
* :green_heart: [Build #3187](https://buildkite.com/elastic/beats-metricbeat/builds/3187) succeeded defd660e2156165787674e33071154ae55c58721
* :green_heart: [Build #3167](https://buildkite.com/elastic/beats-metricbeat/builds/3167) succeeded 07480b2ab575fb556b8eb6966677717c83cfe94f
* :green_heart: [Build #3097](https://buildkite.com/elastic/beats-metricbeat/builds/3097) succeeded f3a4708f2414dfe2a960e0f532c7e3790a8d5891
* :green_heart: [Build #3096](https://buildkite.com/elastic/beats-metricbeat/builds/3096) succeeded ac306a99c3652d001f306f86b4e49e094cb1ddd6
* :green_heart: [Build #3091](https://buildkite.com/elastic/beats-metricbeat/builds/3091) succeeded 829d6776fe8d2824a6f9e9f68962e628556358ec

cc @muthu-mps

<!--buildkite-pr-comment-beats-metricbeat
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3256","number":3256,"commit":"8c88e40c3f5631a078ad3a6427e9ee31b0d75a24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3187","number":3187,"commit":"defd660e2156165787674e33071154ae55c58721"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3167","number":3167,"commit":"07480b2ab575fb556b8eb6966677717c83cfe94f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3097","number":3097,"commit":"f3a4708f2414dfe2a960e0f532c7e3790a8d5891"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3096","number":3096,"commit":"ac306a99c3652d001f306f86b4e49e094cb1ddd6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/beats-metricbeat/builds/3091","number":3091,"commit":"829d6776fe8d2824a6f9e9f68962e628556358ec"}],"number":3256}
buildkite-pr-comment-->

2024-03-13 07:13 UTC, merged