[CI] x-pack/heartbeat monorepo
elastic/beats pull request #38845
Opened 2024-04-10 22:24 UTC by pazone

## Proposed commit message
Use mono repo plugin for xpack/heartbeat

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2024-04-10 22:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38845/detail/PR-38845/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38845/detail/PR-38845/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38845/detail/PR-38845/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38845/detail/PR-38845/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://beats_bk_38845.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-04-10T22:14:36.008Z&rangeTo=2024-04-10T22:34:36.008Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=8fcd181579b2b90f54f25c35819cce25&transactionId=e969a8f7475bd3b7)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats





* Duration: 14 min 42 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :grey_exclamation: Flaky test report
No test was executed to be analysed.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-04-12 11:25 UTC, dliappis requested changes
Thanks for raising this!

Left a few asks for fixes, mostly related to findings/bugs discovered in the last 24hrs.

2024-04-12 11:25 UTC, dliappis commented on .buildkite/pipeline.yml
> +                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
let's add `BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}` as well (which has already been added to the ones already migrated via https://github.com/elastic/beats/pull/38870).
See #38870 description for the reasoning.

2024-04-12 11:25 UTC, dliappis commented on .buildkite/x-pack/pipeline.xpack.heartbeat.yml
> +    depends_on:
we want to be able to run packaging regardless of mandatory/extended unit tests.
It's already ensured in line 184 below, however, in the context of a merge commit (e.g. in `main`) this wait, as it is now, will wait until all mandatory-tests have finished.

So let's just add if: build.env("BUILDKITE_PULL_REQUEST") != "false" above this line?

see https://github.com/elastic/beats/pull/38827/files#diff-87cc9e7aecd3c1a6382e951a1b17429443aa3f12387328521fa06b2c8f83a814R234-R237

for an example with comments

2024-04-12 11:25 UTC, dliappis commented on .buildkite/x-pack/pipeline.xpack.heartbeat.yml
> +      context: "$BEATS_PROJECT_NAME"
shall we remove this, since we've decided to have notifications per step (which already exist in this PR)?

2024-04-12 11:25 UTC, dliappis commented on .buildkite/x-pack/pipeline.xpack.heartbeat.yml
> +        command: ".buildkite/scripts/unit_tests.sh"
could you check if you can switch to the pattern:

```
       command: |
          set -euo pipefail
          source .buildkite/scripts/install_macos_tools.sh
          cd metricbeat && mage build unitTest
```

?

see https://github.com/elastic/beats/pull/38827/files#diff-87cc9e7aecd3c1a6382e951a1b17429443aa3f12387328521fa06b2c8f83a814R220-R222

doing that will not require setting `$BEATS_PROJECT_NAME` in this PR (and let us simplify things in common scripts)

2024-04-12 11:25 UTC, dliappis commented on .buildkite/x-pack/pipeline.xpack.heartbeat.yml
> +        command: "cd $BEATS_PROJECT_NAME && mage build unitTest"
we are making things explicit in the other PRs (see also https://github.com/elastic/beats/pull/38871), could you see if you can search/replace `$BEATS_PROJECT_NAME` with `x-pack/heartbeat" in the entire PR?

If we remove all occurrences of `BEATS_PROJECT_NAME` from our PRs, we'll be able to sunset a lot of common scripts.

Before attempting to replace this, please take a look my comment below about the execute command on macOS; if it works, then you can proceed with replacing this env var too.

2024-04-12 11:25 UTC, dliappis commented on .buildkite/pipeline.yml
> +          diff: "git diff --name-only HEAD~1"
```suggestion
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
```

2024-04-12 11:25 UTC, dliappis commented on .buildkite/pipeline.yml
> +          diff: "git diff --name-only HEAD~1"
see https://github.com/elastic/beats/pull/38870/files ; for merge commits (e.g. against main) we want to run all the tests, so we'll like use a different, very simple, pipeline, details in https://github.com/elastic/ingest-dev/issues/3159#issuecomment-2049780190

2024-04-15 14:26 UTC, sharbuz commented
Hi @pazone , please pay attention to [this PR,](https://github.com/elastic/beats/pull/38490/files) it looks like there are missed some changes related to **NodeJS** in the `.buildkite/scripts/install_tools.sh` and `.buildkite/scripts/common.sh` files

2024-04-17 15:31 UTC, dliappis commented on .buildkite/x-pack/pipeline.xpack.heartbeat.yml
> +        command: ".buildkite/scripts/unit_tests.sh"
turns out we don't need this for nodejs; only for linux unittests and go int tests: https://github.com/elastic/beats/blob/ci_xpack_heartbeat_monorepo/x-pack/heartbeat/Jenkinsfile.yml#L18

2024-04-18 06:28 UTC, dliappis commented
/test

2024-04-18 09:48 UTC, dliappis approved these changes
LGTM based on build status (see issue description links)

2024-04-18 09:53 UTC, merged