Added support for shards total count in Elasticsearch Module
elastic/beats pull request #38891
Opened 2024-04-12 14:02 UTC by philippkahr

## Proposed commit message

Hi,

I just added the support for the `shards_stats.total_count` which can be nice for alerting, since a lot of shards on a single node can impact performance.

Question: if I fix it here, that means it is fixed for the Elastic Agent integration package as well?

```
GET /_nodes/_all/stats?filter_path=*.*.*.shard_stats.*
```

Retrieves:

```
{
  "nodes": {
    "NXSI_2XFQaC2HH7ZvdTJuQ": {
      "indices": {
        "shard_stats": {
          "total_count": 0
        }
      }
    },
    "36aFMv40QX6MBZ4u1DsCCQ": {
      "indices": {
        "shard_stats": {
          "total_count": 0
        }
      }
    },
    "g2N_KasgRkuBEvD529XfhQ": {
      "indices": {
        "shard_stats": {
          "total_count": 1753
        }
      }
    },
    "ObCmi3u1Rhiyp4JTosFXdw": {
      "indices": {
        "shard_stats": {
          "total_count": 866
        }
      }
    },
    "AW982puiTbq-RNJpg23QEw": {
      "indices": {
        "shard_stats": {
          "total_count": 866
        }
      }
    }
  }
}
```

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2024-04-12 14:26 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38891/detail/PR-38891/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38891/detail/PR-38891/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38891/detail/PR-38891/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-38891/detail/PR-38891/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-04-12T13:52:57.826Z&rangeTo=2024-04-12T14:12:57.826Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7f37fc3f995393ac7795f4ebd87ee473&transactionId=34de0d8945b33cb0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats





* Duration: 24 min 33 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->
















## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-04-15 12:49 UTC, miltonhultgren approved these changes
These changes look fine but we'll need to update the mappings for the xpack more which live [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/monitoring-es-mb.json) in the Elasticsearch repo as well as the mappings for the Integration which live [here](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/data_stream/node_stats/fields/fields.yml).

2024-04-16 09:20 UTC, miltonhultgren requested changes
I should have reviewed this more carefully yesterday! 

We first need to wrap the access in a `c.Dict` to go into `indices.shard_stats` in the response, where we'll then find the field `total_count`. We also make that `Dict` optional so in case it's not there (as in older versions) we just skip grabbing that stat.

This should make the tests pass.

2024-04-16 09:20 UTC, miltonhultgren commented on metricbeat/module/elasticsearch/node_stats/data.go
> +			},
```suggestion
			"shard_stats": c.Dict("shard_stats", s.Schema{
				"total_count": c.Int("total_count"),
			}, c.DictOptional),
```

2024-04-16 09:22 UTC, philippkahr commented on metricbeat/module/elasticsearch/node_stats/data.go
> +			},
Ah that makes sense!

2024-04-16 09:41 UTC, miltonhultgren approved these changes

2024-04-16 12:00 UTC, merged