x-pack/filebeat/module/salesforce: Remove dashbaords from a Salesforce module
elastic/beats pull request #39028
Opened 2024-04-18 06:29 UTC by kush-elastic

## Description
This Pull Request aims to remove dashboards from the recently revamped Salesforce module. The plan is to discontinue support for dashboards created in version `7.15.0`, as the overall Beats framework has ceased support for version `8.X.X` dashboards.

For the newer dashboards, support will continue in the upcoming revamp of the Salesforce Integration, ensuring that the latest features and functionalities are available for users.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
- Relates

2024-04-18 07:08 UTC, shmsr requested changes

2024-04-18 07:08 UTC, shmsr commented on CHANGELOG.next.asciidoc
> +- Remove Dashboards from Revamped Salesforce module. {pull}39028[39028]
```suggestion
- Remove dashboards from the revamped Salesforce module. {pull}39028[39028]
```

2024-04-18 07:09 UTC, shmsr approved these changes

2024-04-22 17:17 UTC, shmsr commented on CHANGELOG.next.asciidoc
> +- Remove dashboards from the revamped Salesforce module. {pull}39028[39028]
We do not need this. Ultimately one changelog goes i.e., for module. No need for this?

2024-04-22 17:18 UTC, shmsr approved these changes
Let's remove the changelog and the rest looks good.

2024-05-02 06:54 UTC, kush-elastic commented
Hey @tommyers-elastic,
We need your approval on this PR as part of removing dashboards from Salesforce module.

2024-05-15 10:29 UTC, tommyers-elastic approved these changes

2024-05-16 06:00 UTC, merged