Add error check to groupToEvents so we don't blindly add error values
elastic/beats pull request #39404
Opened 2024-05-03 21:18 UTC by fearful-symmetry

## Proposed commit message

fixes https://github.com/elastic/beats/issues/38140

This adds an error check to the `eventMap` in `groupToEvents()` so we don't report an error where there isn't one.

I almost never touch any of the windows code, so feel free to ignore this until CI is green.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

2024-05-05 15:21 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane (Team:Elastic-Agent-Data-Plane)

2024-05-06 13:19 UTC, leehinman requested changes
code LGTM

Needs a changelog entry

2024-05-06 15:32 UTC, leehinman approved these changes
suggestion on changelog to include issue.

2024-05-06 15:32 UTC, leehinman commented on CHANGELOG.next.asciidoc
> +- Fix error handling in perfmon metrics {pull}39404[39404]
```suggestion
- Fix error handling in perfmon metrics. {issue}38140[38140] {pull}39404[39404]
```

2024-05-07 14:40 UTC, faec approved these changes

2024-05-10 06:33 UTC, merged