Rename apache2.module.error into apache.module.error in the Apache error integration
elastic/beats pull request #39481
Opened 2024-05-09 06:44 UTC by herrBez

## Proposed commit message

[Filebeat][Apache] Rename field apache2.module.error into apache.module.error in the Dashboard

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

None

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- #39480 

## Use cases

## Screenshots

<img width="878" alt="image" src="https://github.com/elastic/beats/assets/6976484/f797193b-f2eb-44d2-a3c1-20c5af0b9ff8">

The original saved search uses apache2.error.module, while the correct field apache.error.module (added by me) shows that it is actually populated with a meaningful value.

## Logs

2024-05-09 06:46 UTC, shmsr commented
Nice find. Can you also open a PR for the integrations repo? See: https://github.com/search?q=repo%3Aelastic%2Fintegrations+path%3A%2F%5Epackages%5C%2Fapache%5C%2Fkibana%5C%2F%2F+apache2&type=code

2024-05-09 06:47 UTC, shmsr commented
Please add an entry to the changelog.

2024-05-09 07:02 UTC, herrBez commented
Thank you. I think I addressed both points now :)

2024-05-09 07:08 UTC, shmsr requested changes

2024-05-09 07:08 UTC, shmsr commented on CHANGELOG.next.asciidoc
> +- apache: Rename field apache2.module.error into apache.module.error in the apache error visualization. {issue}39480[39480] {pull}39481[39481]
```suggestion
- Rename the field "apache2.module.error" to "apache.module.error" in Apache error visualization. {issue}39480[39480] {pull}39481[39481]
```

2024-05-09 07:09 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-39481/detail/PR-39481/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-39481/detail/PR-39481/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-39481/detail/PR-39481/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-39481/detail/PR-39481/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2024-05-09T06:34:17.974Z&rangeTo=2024-05-09T06:54:17.974Z&transactionName=BUILD+Beats%2Fbeats%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=6cf6009fe97e7d777b69ce59ebd4be3c&transactionId=63b990d61228e48b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats





* Duration: 25 min 43 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->
















## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate the packages and run the E2E tests.


- `/beats-tester` : Run the installation tests with beats-tester.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2024-05-09 07:09 UTC, shmsr commented
Changes LGTM. However, I would like another member of my team to review this as well before we merge.

2024-05-17 06:49 UTC, shmsr approved these changes

2024-05-24 05:45 UTC, ishleenk17 commented
@shmsr @devamanv : I think this can be merged in beats as well?

2024-05-24 05:57 UTC, herrBez commented
I see some failures in the build, but I hardly believe they are related with the change introduced here:
https://github.com/elastic/beats/pull/39481/checks?check_run_id=25345121364

2024-05-28 07:37 UTC, shmsr commented
@herrBez CI is passing. Let's merge?

2024-05-28 08:04 UTC, merged

2024-05-28 08:05 UTC, herrBez commented
Done. Thank you for the help and support!