Add multifragment rpc support
elastic/beats pull request #40206
Opened 2024-07-11 20:11 UTC by nicholasberlin

## Proposed commit message
If nfs is being transported over TCP and an RPC message is split into multiple record fragments (very rare), Packetbeat will stop issuing callbacks until the rawData stream overflows and resets. Overflow occurs at 10MB of stream data.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

## Related issues

-

## Use cases

## Screenshots

## Logs

2024-07-11 20:21 UTC, elasticmachine commented
Pinging @elastic/sec-linux-platform (Team:Security-Linux Platform)

2024-07-11 21:55 UTC, efd6 commented on packetbeat/protos/nfs/rpc.go
> +
```suggestion
```

2024-07-12 02:12 UTC, Trinity2019 approved these changes

2024-07-12 13:05 UTC, marc-gr approved these changes

2024-07-15 07:42 UTC, haesbaert requested changes

2024-07-15 07:42 UTC, haesbaert commented on packetbeat/protos/nfs/rpc.go
> +			}
I don't think this is correct, the fragments will be on further TCP packets, they won't be on the same packet.
To implement this you would have to buffer each fragment, waiting until you get the last, then join then and create a XDR below with `newXDR`

2024-07-15 08:08 UTC, haesbaert commented on packetbeat/protos/nfs/rpc.go
> +	partialMessage = rawData[4:fragmentSize]
```suggestion
	partialMessage = rawData[4:fragmentSize - 4]
```
Unless I'm missing something:
fragmentSize includes the header, partialMessage skips over the header, so it should subtract it.

2024-07-15 08:20 UTC, haesbaert commented on packetbeat/protos/nfs/rpc.go
> +func parseFragment(rawData []byte) (partialMessage []byte, fragmentSize int, isLast bool) {
```suggestion
func parseFragment(rawData []byte) (partialMessage []byte, fragmentSize uint, isLast bool) {
```

2024-07-15 08:20 UTC, haesbaert commented on packetbeat/protos/nfs/rpc.go
> +	fragmentSize = 4 + int(header&rpcSizeMask)
```suggestion
	fragmentSize = 4 + uint(header&rpcSizeMask)
```

2024-07-16 14:12 UTC, haesbaert commented on packetbeat/protos/nfs/rpc.go
> +	partialMessage = rawData[4:fragmentSize]
I thought it was size, please disregard :)

2024-07-16 16:24 UTC, haesbaert approved these changes

2024-07-25 18:05 UTC, andrewkroh commented on CHANGELOG.next.asciidoc
> + - Fix mishandling of fragmented RPC records
```suggestion
 - nfs protocol: Fix mishandling of fragmented RPC records. {pull}40206[40206]
```

(give more context and the PR number)

2024-08-29 22:01 UTC, andrewkroh approved these changes

2024-08-29 22:02 UTC, andrewkroh commented
@nicholasberlin Anything left to do on this PR?

2024-08-29 23:11 UTC, nicholasberlin commented
I have not been able to test this with real world data. It seems to be a very rare scenario. I feel pretty good about the code, but realistically, it's untested.

2026-06-05 16:42 UTC, ricardoamaro commented
Closing this PR.

After review, multifragment RPC reassembly cannot be made reliable within Packetbeat's current wire-dump capture model. Packetbeat captures packets as they enter the network stack and can drop packets between the kernel and userland. A single dropped packet desyncs it from the kernel TCP window, which makes reassembling a multifragment RPC record over a long-lived NFS connection unreliable regardless of how the parser is patched.

Rather than keep code that gives a false impression of correctness, we are closing this and tracking the findings and the path forward (IPFIX/Netflow for high-scale traffic tracking, and eBPF in-kernel assembly via quark for protocol-level fidelity) in an internal investigation issue.

Path forward reference: quark unification RFC elastic/security-integrations#417

Thanks @nicholasberlin for the work here. The analysis is preserved.

2026-06-05 16:42 UTC, closed without merging