Application pool status
elastic/beats pull request #40612
Opened 2024-08-26 09:57 UTC by anil-elastic

## Proposed commit message

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

## Author's Checklist
To get all the application pool name and status, "**Get-IISAppPool**" command used. "Get-IISAppPool" will only be executed in windows powershell environment.
**Make sure to have powershell on the running machine.**

Using this PR, along with existing details, status of all the applicationpool also be available.

- [ ]

## How to test this PR locally

## Related issues

- Closes #39061 

## Use cases

## Screenshots

## Logs

2024-08-29 03:20 UTC, lucian-ioan commented
After fixing the CI issues, you will need to also update fields.yml/data.json in the _meta folder.

2024-08-29 03:25 UTC, lucian-ioan requested changes
After fixing the CI issues, you will need to also update fields.yml/data.json in the _meta folder. Preferably add 2 sample json events, one for a running app pool and one for a stopped one.

I expect this will not be a breaking change for existing dashboards.

2024-09-21 17:27 UTC, parilsanghvi commented
Hello @anil-elastic,

I hope you're doing well. I was wondering if there is any estimated timeline for when PR might be merged. I would greatly appreciate any updates on its progress.

Thank you for your time and all your hard work!

Best regards,
Paril Sanghvi

2024-10-21 04:19 UTC, parilsanghvi commented
Hi @lucian-ioan @anil-elastic , just following along with the progress of this PR—are there any updates or next steps planned? Curious to see where things are headed. Thanks!

2024-10-21 09:39 UTC, anil-elastic commented
Hi @parilsanghvi,

We can expect the PR to be review ready this week. We will ask the team to review.

2024-11-18 00:03 UTC, lucian-ioan commented
Hi @parilsanghvi,

Unfortunately, @anil-elastic is no longer part of Elastic so this one is back to me.

Just to confirm, is just the new field `"status":"started"/"stopped"` sufficient in this case?

If yes, I'll just copy this PR and make it ready for review.

2024-11-19 05:50 UTC, parilsanghvi commented
Hi @lucian-ioan sad to hear about Anil's exit.

This Page has information about the IIS Application Pool States.
[ApplicationPool State Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.applicationpool.state?view=iis-dotnet)

Valid values are Starting, Started, Stopping, Stopped, and Unknown.

2024-12-23 17:54 UTC, parilsanghvi commented
Hi @lucian-ioan  ,

I hope you’re doing well. I wanted to kindly follow up on this pull request.

If possible, could the relevant labels be reapplied and a review scheduled when convenient? I really appreciate the team’s time and consideration in addressing these updates.

2025-04-03 05:12 UTC, lucian-ioan commented
Closing this as original owner is no longer working on it. Reopening in last mentioned PR.

2025-04-03 05:12 UTC, closed without merging