[WIP] Add registry to Filebeat's diagnostic
elastic/beats pull request #41795
Opened 2024-11-26 18:02 UTC by belimawr

State: PoC works. PR created to see if any of the tests break and to share progress.

## Proposed commit message

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Use cases

## Screenshots

## Logs

2024-11-27 19:54 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane (Team:Elastic-Agent-Data-Plane)

2024-11-27 19:59 UTC, cmacknz commented
1. Is there a limit to how big the contents of the `${path.home}/registry` directory can get? If there isn't a limit in Filebeat itself, I think the diagnostics collection here needs a size limit of some sort. Otherwise if we accidentally create a huge registry diagnostics won't work at all.
2. Can a more restrictive pattern be used instead of just taking everything in the directory? Perhaps you can only take files with permissions that match the filebeat user and group? This is to stop arbitrary data from being uploaded to Fleet and then decompressed later by an unsuspecting user or engineer.

2024-11-27 20:10 UTC, belimawr commented
> 1. Is there a limit to how big the contents of the `${path.home}/registry` directory can get? If there isn't a limit in Filebeat itself, I think the diagnostics collection here needs a size limit of some sort. Otherwise if we accidentally create a huge registry diagnostics won't work at all.
> 2. Can a more restrictive pattern be used instead of just taking everything in the directory? Perhaps you can only take files with permissions that match the filebeat user and group? This is to stop arbitrary data from being uploaded to Fleet and then decompressed later by an unsuspecting user or engineer.

1. No there isn't, I've been thinking about it, I believe gRPC has a limit, so in my mind that was a kind of a guardrail. A limit for the payload (gziped "file") is easy to add. It's hard for me, at the moment, to gauge what would be an ideal limit for a high load environment like Kubernetes. The log file is caped at 10Mb, however the checkpoint is unbound. Given compression, I'd say at least 20Mb to be on the safe side.
2. Yes, that can be implemented, all files that make up the registry are well known. The registry itself is in the data folder of Elastic-Agent, so there should be no extra data there. The only reason I can think of to have some files there we do not want is if some malicious actor adds something there. Anyways, I agree it's an nice extra security feature.

I'll implement those changes.

2024-11-27 20:20 UTC, cmacknz commented
> The log file is caped at 10Mb, however the checkpoint is unbound. Given compression, I'd say at least 20Mb to be on the safe side.

The Fleet server upload API used to get diagnostics as an action probably has a limit, I'm not sure what it is by default off the top of my head. I would expect it is ~100 MB so if we go with 20 MB we need to make sure we don't push ourselves past that in real use cases.

The few compressed gzipped diagnostics I have laying around are all <5 MB now for reference.

2024-11-27 20:21 UTC, cmacknz commented
The Fleet settings aren't super clear on what the upload file size limit is, maybe there isn't one? The files are chunked as part of the implementation. https://github.com/elastic/fleet-server/blob/4132a505f0c759e332a890fdf701b8ff238cf91a/fleet-server.reference.yml#L200-L214

2024-12-16 12:06 UTC, VihasMakwana approved these changes
LGTM apar from cmments

2024-12-16 12:06 UTC, VihasMakwana commented on filebeat/input/v2/compat/compat.go
> +
I don't think we need this commented out code. Correct?

2024-12-17 21:59 UTC, cmacknz requested changes
Requesting changes until comments get addressed.

2025-01-06 15:38 UTC, belimawr commented
All review comments have been addressed.

The failure from TestRegistryIsInDiagnostics has been fixed
The failure from TestFilestreamMetadataUpdatedOnRename is addressed by https://github.com/elastic/beats/pull/42213
The failure from TestTranslateGUIDWithLDAP is unrelated to this PR and I cannot reproduce it

2025-01-07 19:00 UTC, cmacknz commented on filebeat/beater/diagnostics.go
> +	tarFile, err := os.Create(dst)
This will be empty if there are no matches, can we avoid including an empty .tar file to avoid people looking into it and wondering if it is supposed to be empty?

If the registry directory exists without a log or filestream input, the regexes will never match for agent Filebeat sub-processes that don't run either of those input types so this will be common.

2025-01-07 19:09 UTC, cmacknz commented on x-pack/filebeat/tests/integration/registrydiagnostics_test.go
> +func TestRegistryIsInDiagnostics(t *testing.T) {
Add a test case that does not use a filestream or log input

2025-01-07 22:06 UTC, belimawr commented on filebeat/beater/diagnostics.go
> +	registryPath := filepath.Join(dataPath, "registry")
Yes, the registry is created very early during Filebeat's start up, even when using the [benchmark input](https://www.elastic.co/guide/en/beats/filebeat/8.17/filebeat-input-benchmark.html) the registry folder, `meta.json` and `log.json` are created.

Given that they exist in this very simple case, I rather have them in the diagnostics then trying to be clever and detect when the registry is actually being used by one of the inputs.

2025-01-07 22:15 UTC, belimawr commented on filebeat/beater/diagnostics.go
> +	tarFile, err := os.Create(dst)
As I mentioned on https://github.com/elastic/beats/pull/41795#discussion_r1906096881 the registry folder is always there and contain some data. Also other inputs can use the registry, from the top of my head: `log`, `filestream` and `journald` all use the registry.

The tar file from this "empty" registry is 3.5kb, the gziped is 228 bytes, it's so little I don't see any problems of having it in the diagnostics. It also works as a sort of "snapshot" of the registry, even if empty, which is a helpful information to have.

2025-01-08 00:51 UTC, cmacknz commented on filebeat/beater/diagnostics.go
> +	tarFile, err := os.Create(dst)
I don't care about the impact of the size, rather the analysis impact of knowing when its worth decompressing and looking at

A lot of inputs don't use the registry at all, my suspicion is people and tooling will waste time looking at the empty ones because there's no other way to know if its useful besides memorizing which inputs use the registry.

2025-01-22 17:18 UTC, cmacknz commented on filebeat/beater/diagnostics.go
> +	tarFile, err := os.Create(dst)
Spoke to Tiago about this, the registry isn't empty by default even if unused so detecting this is too annoying.

2025-01-22 17:18 UTC, cmacknz approved these changes

2025-01-23 20:55 UTC, merged