[Metricbeat] Windows Module add wmi metricset
elastic/beats pull request #42017
Opened 2024-12-12 15:57 UTC by herrBez

## Proposed commit message

[Metricbeat][Windows] Add experimental wmi metricset

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

This PR does not have impact to existing use-cases

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- https://github.com/elastic/beats/issues/29072
- https://github.com/elastic/beats/issues/8614
- [External] https://github.com/eskibars/wmibeat/issues/4

## Use cases

As a windows user I want to leverage WMI (and in particular WQL, SQL for WMI) to extract detailed system information and metrics. 

## Screenshots

## Logs

2024-12-12 16:29 UTC, strawgate commented
One of the challenges with running arbitrary WMI queries is that WMI queries can be extremely slow and certain WMI queries can actually result in changes to the system -- have we considered whether or how we might provide timeout functionality for running WMI queries?

2024-12-13 08:13 UTC, herrBez commented
> One of the challenges with running arbitrary WMI queries is that WMI queries can be extremely slow and certain WMI queries can actually result in changes to the system -- have we considered whether or how we might provide timeout functionality for running WMI queries?

About the timing issues: I don't see a parameter in the library to stop a query after X seconds (I would need to understand if the underlying library/WMI have a similar mechanism). Or do you have a suggestion by any chance?


About the "can actually result in changes to the system": with the current implementation we can only build queries of type `SELECT p1 [,p*] FROM Class WHERE ...`. This should prevent changes to the system, right?

2024-12-13 10:25 UTC, herrBez commented on metricbeat/modules.d/system.yml
That's obviously a mistake

2024-12-13 10:25 UTC, herrBez commented on metricbeat/modules.d/windows.yml.disabled
That's obviously a mistake

2024-12-13 16:26 UTC, strawgate commented
A WMI query does whatever the underlying WMI provider decides it should do. This means a developer can create a WMI provider which upon a `Select * from MyCustomProvider`, performs a change to the system.

A common bad actor example is the win32_product provider. When queried, the win32_product provider verifies the integrity of all installed MSI packages on the system. For any products where integrity cannot be verified it performs a repair install of the MSI.

You have to read quite a bit of documentation to land on this fact:
```
The Win32_Product class enables you to enumerate the software installed on a computer, provided the software was installed by using the Windows Installer.
```
...
```
Warning  Win32_Product is not query optimized. Queries such as "select * from Win32_Product where (name like 'Sniffer%')" require WMI to use the MSI provider to enumerate all of the installed products and then parse the full list sequentially to handle the “where” clause. This process also initiates a consistency check of packages installed, verifying and repairing the install. With an account with only user privileges, as the user account may not have access to quite a few locations, may cause delay in application launch and an event 11708 stating an installation failure. For more information, see [KB Article 794524](https://support.microsoft.com/kb/974524).
```

This means a simple `select name from Win32_Product where (name like 'Google Chrome%')` can take upwards of an hour to complete and can result in significant changes to the underlying system.

2024-12-24 15:26 UTC, herrBez commented
Hi @ishleenk17, @tommyers-elastic , I implemented all changes we discussed offline and the dataset is ready for review.

I am having a very hard-time in making the CI/CD pipeline work. Could you help me shred some lights? In particular, I am not able to understand how to fix the error reported here https://github.com/elastic/beats/actions/runs/12483185235/job/34838540533?pr=42017.

2024-12-26 14:53 UTC, ishleenk17 commented
@herrBez 

- To make this module part of the Agent, please add the module to [agenbeat.spec.yml ](https://github.com/elastic/beats/blob/6916b77453a37ad9095b7414aced1f5d61ccdb28/x-pack/agentbeat/agentbeat.spec.yml#L4).
- Please run make update BEATS=metricbeat in the beats directory.

2025-01-02 09:49 UTC, herrBez commented
Hi Ishleen, thank you for the help. 

> Please run make update BEATS=metricbeat in the beats directory.

I receive the error as part of the execution of the command and I don't understand how to fix it.

2025-01-29 10:38 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/utils.go
> +	defer cancel()
this just ensures the context is always cleaned up when the query completes within the timeout?

2025-01-29 10:38 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/utils.go
> +				tailMessage = "successfully. The result will be ignored"
seems a shame to throw away the result. perhaps we can revisit this in a later PR?

2025-01-29 10:38 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +	if config.WarningThreshold == 0*time.Second {
nit: 0*time.Second == 0, so just `0` is enough.

2025-01-29 10:38 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +	if config.WarningThreshold == 0*time.Second {
do we document anywhere that this default to the collection period?

2025-01-29 10:38 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +						// If the function is not found let us fetch it and cache it
what's the reason we do this, instead of just calling the functions?

2025-01-29 12:12 UTC, herrBez commented on go.mod
> +	github.com/go-ole/go-ole v1.2.6
Hi, I think this dependency was indirect from the wmi library (which uses go-ole 1.2.6 https://github.com/microsoft/wmi/blob/master/go.sum#L3 ) and when I started using it as a standalone library to fix the type issue it became a fully-fledged dependency.

By reading the release notes I don't see breaking changes 🤔

2025-01-29 13:01 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +// We assume that it is **always** defined for every property to simiplifying
Not that I am aware of, but given that I addressed the panic problem I removed the comment, because I have no information to sustain such a strong statement :)

2025-01-29 13:06 UTC, herrBez commented on go.mod
> +	github.com/go-ole/go-ole v1.2.6
Nevertheless, I would probably stick with the same library version. WDYT?

2025-01-29 13:31 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +	layout := "20060102150405.999999-0700"
The WMI time strings are formatted `20060102150405.999999-070` (they only have three digits for the timezone).

By looking at the documentation https://pkg.go.dev/time#pkg-constants I thought we were forced to have either 4 or 2 digits, while we have three in the string. So I thought to reduce the case to 4 digits.

It seems to work also by using 3 digits. Should I go with three digits?

2025-01-29 13:32 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +	//   If the string does not end with a digit, it's not an uint64, sint64, datetime
At least in my experience it's always `+000` (or three digits for the timezone). I could not find a reference however.

2025-01-29 13:32 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +		panic("Error retrieving the wmi property type")
Fix the code to deal with the error without panic.

2025-01-29 13:35 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +				tailMessage = "successfully. The result will be ignored"
I agree, once it's closed, I will open a PR for this

2025-01-29 13:40 UTC, herrBez commented on metricbeat/module/windows/wmi/wmi.go
> +						// If the function is not found let us fetch it and cache it
> If you are referring to the if:

I am doing this because there are many cases where we don't apply a transformation (example all integers in all architectures but 64).

> If you are referring to the caching of the function
There are queries with more than one line as a result (but share the same schema) and without the caching we would have the "CIMType" workaround for every string.

2025-01-29 13:57 UTC, tommyers-elastic commented on go.mod
> +	github.com/go-ole/go-ole v1.2.6
totally fine with me 👍

2025-01-29 13:57 UTC, herrBez commented on metricbeat/docs/fields.asciidoc
> +[float]
I am not entirely sure where does this float come from 🤔 . Can it be because the `fields.yml` is essentially empty?

2025-01-29 13:57 UTC, tommyers-elastic commented on metricbeat/metricbeat.reference.yml
> +      # Namespace for this specific query. Uncomment to override the default namespace.
yep that help a lot - thanks !

2025-01-29 14:07 UTC, herrBez commented on metricbeat/module/windows/wmi/utils.go
> +	//   If the string does not end with a digit, it's not an uint64, sint64, datetime
I am not entirely sure I am following this documentation https://learn.microsoft.com/en-us/windows/win32/wmisdk/cim-datetime .

2025-01-29 15:19 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/utils.go
> +	//   If the string does not end with a digit, it's not an uint64, sint64, datetime
👍 seems like it's ok

2025-01-29 15:20 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/utils.go
> +	layout := "20060102150405.999999-0700"
yeh i think you can any format you want, so let's go with 3 if it works.

2025-01-29 15:21 UTC, tommyers-elastic commented on metricbeat/docs/fields.asciidoc
> +[float]
no idea - but i don't think it's a blocker, we can revisit documentation later if we need to.

2025-01-29 15:26 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +						"namespace": m.config.Namespace,
one more thing: is this accurate - the namespace could be overwritten for the specific query, right?

2025-01-29 15:28 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +						"host":      m.config.Host,
and i think we should probably leave `host` to the `add_host_metadata` processor, which will use ecs-compliant field names (in this case `host.name`)

2025-01-29 15:29 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +						"host":      m.config.Host,
sorry never mind, the agent can be running on a different host to where the queries are being executed, and `host` is in the metricset field scope, so this is all fine. please ignore.

2025-01-29 15:34 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +						// If the function is not found let us fetch it and cache it
it only saves cycles if we have fields with the same names in the same collection though, right? are the field names always unique between namespaces? because this would apply the same conversion there too i think (same field name, different namespace).

2025-01-29 15:38 UTC, herrBez commented on metricbeat/module/windows/wmi/wmi.go
> +						// If the function is not found let us fetch it and cache it
Wow, great catch! This is (surely) unique for query but not for Namespace (or at least I would not do this assumption).

Let me move the definition at the query level. This will save cycles if we have X results for the same query.

2025-01-29 15:44 UTC, herrBez commented on metricbeat/module/windows/wmi/wmi.go
> +						// If the function is not found let us fetch it and cache it
Addressed in https://github.com/elastic/beats/pull/42017/commits/b01e730e5b97700de1fda209c65816853bcec6dd

2025-01-29 16:29 UTC, tommyers-elastic commented on metricbeat/module/windows/wmi/wmi.go
> +	if config.WarningThreshold == 0*time.Second {
just wanted follow up to ensure this gets addressed in the future - we should ensure we document that there is a default timeout period.

2025-01-30 03:12 UTC, leehinman reviewed
I think you should probably add `metricbeat\module\windows\wmi` to the `.github/CODEOWNERS` with your team as the owners.

otherwise code looks OK to me

2025-01-30 05:48 UTC, ishleenk17 commented
@herrBez : We should also add entry in CHANGELOG.next.asciidoc

2025-01-30 06:15 UTC, jlind23 approved these changes

2025-01-30 06:35 UTC, VihasMakwana approved these changes

2025-01-30 06:47 UTC, VihasMakwana commented on metricbeat/module/windows/wmi/wmi.go
> +						convertedValue, err := convertFun(fieldValue.(string))
Can we do `fieldValueString, ok := fieldValue.(string)` and use `fieldValueString` instead?
I'd avoid panics.

2025-01-30 06:48 UTC, VihasMakwana requested changes
@herrBez I've added a comment. Otherwise, LGTM

2025-01-30 07:10 UTC, herrBez commented on metricbeat/module/windows/wmi/wmi.go
> +						convertedValue, err := convertFun(fieldValue.(string))
Hi Vihas, 

I addressed the comment here https://github.com/elastic/beats/pull/42017/commits/e076caa1a753bc0e234a13ffa1c179dd05656b8d . Let me know if it's  okay.

Checking the type conversion is redundant (because of the if), but probably better adding a check more (You never know if in the future the conditions may change).

2025-01-30 07:16 UTC, herrBez commented on metricbeat/module/windows/wmi/wmi.go
> +						convertedValue, err := convertFun(fieldValue.(string))
https://github.com/elastic/beats/pull/42017/commits/35304c577711622bcf182c603e1e45d3095d907c I made the comment easier to read

2025-01-30 07:39 UTC, VihasMakwana approved these changes

2025-01-30 07:54 UTC, herrBez commented
Can someone help me understand why buildkite/docs-build-pr is failing? From the log I cannot understand what is the problem.

2025-01-30 12:49 UTC, leemthompo commented on metricbeat/docs/modules/windows.asciidoc
> +      # namespace: "root\\cimv2" # Overrides the metric----
```suggestion
      # namespace: "root\\cimv2" # Overrides the metric
      ----
```

2025-01-30 12:50 UTC, leemthompo commented on metricbeat/docs/modules/windows.asciidoc
> +      # namespace: "root\\cimv2" # Overrides the metric----
I think this commenting out the code delimiter might be the issue

2025-01-30 15:24 UTC, merged