[metricbeats][mongodb] handle extra collstats metrics
elastic/beats pull request #42171
Opened 2024-12-27 11:24 UTC by stefans-elastic

## Proposed commit message

[metricbeats][mongodb] handle extra collstats metrics

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes #42003

## Use cases

## Screenshots

<img width="1508" alt="Screenshot 2024-12-27 at 11 24 18 AM" src="https://github.com/user-attachments/assets/7e533482-2338-4247-b2a2-c698a563b873" />

## Logs

2025-01-16 19:53 UTC, shmsr commented
Here are a few suggestions:

```diff
diff --git a/metricbeat/module/mongodb/collstats/_meta/fields.yml b/metricbeat/module/mongodb/collstats/_meta/fields.yml
index 27c4f989a7..a4a09f8d09 100644
--- a/metricbeat/module/mongodb/collstats/_meta/fields.yml
+++ b/metricbeat/module/mongodb/collstats/_meta/fields.yml
@@ -117,19 +117,19 @@
         - name: stats.avgObjSize
           type: long
           description: >
-            The average size of an object in the collection.
+            The average size of an object in the collection (in bytes).
         - name: stats.storageSize
           type: long
           description: >
-            The total amount of storage allocated to this collection for document storage.
+            The total amount of storage allocated to this collection for document storage (in bytes).
         - name: stats.totalIndexSize
           type: long
           description: >
-            The total size of all indexes.
+            The total size of all indexes (in bytes).
         - name: stats.totalSize
           type: long
           description: >
-            The sum of the storageSize and totalIndexSize.
+            The sum of the storageSize and totalIndexSize (in bytes).
         - name: stats.max
           type: long
           description: >
diff --git a/metricbeat/module/mongodb/collstats/collstats.go b/metricbeat/module/mongodb/collstats/collstats.go
index 64f345c8d2..c760845d0f 100644
--- a/metricbeat/module/mongodb/collstats/collstats.go
+++ b/metricbeat/module/mongodb/collstats/collstats.go
@@ -90,7 +90,7 @@ func (m *Metricset) Fetch(reporter mb.ReporterV2) error {
 
 	totals, ok := result["totals"].(map[string]interface{})
 	if !ok {
-		return errors.New("collection 'totals' are not a map")
+		return errors.New("collection 'totals' is not a map")
 	}
 
 	if err = res.Err(); err != nil {
@@ -147,9 +147,13 @@ func (m *Metricset) Fetch(reporter mb.ReporterV2) error {
 
 func fetchCollStats(client *mongo.Client, dbName, collectionName string) (map[string]interface{}, error) {
 	db := client.Database(dbName)
-	colStats := db.RunCommand(context.Background(), bson.M{"collStats": collectionName})
+	collStats := db.RunCommand(context.Background(), bson.M{"collStats": collectionName})
+	if err := collStats.Err(); err != nil {
+		return nil, fmt.Errorf("collStats command failed: %w", err)
+	}
+
 	var statsRes map[string]interface{}
-	if err := colStats.Decode(&statsRes); err != nil {
+	if err := collStats.Decode(&statsRes); err != nil {
 		return nil, fmt.Errorf("could not decode mongo response for database=%s, collection=%s: %w", dbName, collectionName, err)
 	}
 
diff --git a/metricbeat/module/mongodb/collstats/data.go b/metricbeat/module/mongodb/collstats/data.go
index cef81df7c3..e9600fb83e 100644
--- a/metricbeat/module/mongodb/collstats/data.go
+++ b/metricbeat/module/mongodb/collstats/data.go
@@ -30,9 +30,12 @@ func eventMapping(key string, data mapstr.M) (mapstr.M, error) {
 		return nil, err
 	}
 
+	// NOTE: splitKey handles the case where the collection can have "." in the name
+	database, collection := names[0], names[1]
+
 	event := mapstr.M{
-		"db":         names[0],
-		"collection": names[1],
+		"db":         database,
+		"collection": collection,
 		"name":       key,
 		"total": mapstr.M{
 			"time": mapstr.M{
@@ -111,11 +114,11 @@ func mustGetMapStrValue(m mapstr.M, key string) interface{} {
 }
 
 func splitKey(key string) ([]string, error) {
-	names := strings.SplitN(key, ".", 2)
+	dbColl := strings.SplitN(key, ".", 2)
 
-	if len(names) < 2 {
+	if len(dbColl) < 2 {
 		return nil, errors.New("collection name invalid")
 	}
 
-	return names, nil
+	return dbColl, nil
 }
diff --git a/metricbeat/module/mongodb/collstats/data_test.go b/metricbeat/module/mongodb/collstats/data_test.go
index a921d14d72..eefd800c21 100644
--- a/metricbeat/module/mongodb/collstats/data_test.go
+++ b/metricbeat/module/mongodb/collstats/data_test.go
@@ -21,7 +21,7 @@ package collstats
 
 import (
 	"encoding/json"
-	"io/ioutil"
+	"os"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
@@ -30,8 +30,7 @@ import (
 )
 
 func TestEventMapping(t *testing.T) {
-
-	content, err := ioutil.ReadFile("./_meta/test/input.json")
+	content, err := os.ReadFile("./_meta/test/input.json")
 	assert.NoError(t, err)
 
 	data := mapstr.M{}
```

2025-01-16 19:56 UTC, shmsr commented
Also, can you also write a better commit message; helps in future when we need to revisit the changes.

2025-01-16 19:56 UTC, shmsr commented
But yes, rest looks good!

2025-01-16 19:57 UTC, shmsr requested changes

2025-01-16 19:57 UTC, shmsr commented on metricbeat/module/mongodb/collstats/data.go
> +			"nindexes":       mustGetMapStrValue(data, "stats.nindexes"),
Any reason to not add fields like -- capped?

https://github.com/huggingface/Mongoku/blob/39b0d564433f1a68f3e7ea9bff482ca290e4f027/lib/Collection.ts#L11

Also, see the list here: https://github.com/DataDog/integrations-core/blob/bef0a2f2971ff01176689794aaa7eb0bb0b37a9e/mongo/datadog_checks/mongo/metrics.py#L140

If we are getting them, can we please add?

2025-01-16 20:01 UTC, shmsr commented on metricbeat/module/mongodb/collstats/collstats.go
> +		go func(eventReporter mb.ReporterV2, mongoClient *mongo.Client, group string) {
TIP: Also, without bounded concurrency, errgroup is cleaner way to implement this: https://pkg.go.dev/golang.org/x/sync/errgroup

2025-01-17 10:35 UTC, ishleenk17 commented on metricbeat/module/mongodb/collstats/collstats.go
> +		go func(eventReporter mb.ReporterV2, mongoClient *mongo.Client, group string) {
Agree to this: 
For large datasets, the number of goroutines can overwhelm the system. Let's use workerpool to limit the concurrency.

2025-01-17 10:35 UTC, ishleenk17 commented on metricbeat/module/mongodb/collstats/collstats.go
> +			collStats, err := fetchCollStats(mongoClient, names[0], names[1])
Better naming for names[0], names[1] please

2025-01-17 10:36 UTC, ishleenk17 commented on metricbeat/module/mongodb/collstats/data.go
> +			"nindexes":       mustGetMapStrValue(data, "stats.nindexes"),
There are quite a lot of fileds which we get here @shmsr .
We planned to list down the most useful one.

2025-01-17 14:52 UTC, stefans-elastic commented on metricbeat/module/mongodb/collstats/data.go
> +			"nindexes":       mustGetMapStrValue(data, "stats.nindexes"),
I've replaced WaitGroup with errgroup. Btw, I set goroutins limit to 10 like was suggested in the example. Is 10 a good limit or should I change it to something else?

2025-01-17 14:52 UTC, stefans-elastic commented on metricbeat/module/mongodb/collstats/collstats.go
> +		go func(eventReporter mb.ReporterV2, mongoClient *mongo.Client, group string) {
I've replaced WaitGroup with errgroup. Btw, I set goroutins limit to 10 like was suggested in the example. Is 10 a good limit or should I change it to something else?

2025-01-17 14:53 UTC, stefans-elastic commented
@ishleenk17 @shmsr thank you for your reviews!
I've made the requested changes, please take a look

2025-01-20 16:13 UTC, shmsr approved these changes

2025-01-20 17:16 UTC, merged